### ISSUE TITLE
Adicionar Piwik / Google Analytics

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#100]
Precisamos testar nossa própria coleta de métricas. Deve haver correlação entre as métricas que adquirimos e as coletadas pelo Google Analytics.

**Comment by sahrosa** [comment]
Usar o GA apenas no protótipo, no caso?

**Comment by cv** [comment]
Provavelmente, sim – depois trocamos para o Piwik que o governo já tem, mas isso pode levar um tempo, ainda. Enquanto isso, vamos de GA mesmo. Que tal?

**Comment by sahrosa** [comment]
Eu apoio totalmente!

**Comment by caduvieira** [comment]
Depois do Snowden falar sobre a espionagem do governo brasileiro houve uma determinação em não se utilizar o GA no governo. Não sei de onde veio e o @nitaibezerra ou o @chris-redfield podem falar mais.

**Comment by cv** [comment]
Bom ponto, @caduvieira – também estávamos receosos em recomendar o uso do GA.

Realisticamente, qual a expectativa deveríamos ter em relação ao tempo necessário para adicionar o novo site ao Piwiki?

**Comment by caduvieira** [comment]
Não tenho ideia de tempo. Creio que a @garotadpi pode te ajudar nisso. O pessoal de dados abertos tem contato com a Presidência podem te falar um pouco mais também.

**Comment by nitaibezerra** [comment]
Temos usado o GA no dados.gov.br até hoje. O Piwik sempre foi uma promessa
para nós e não passou disso. No início participamos das discussões que
provocaram a adesão do Piwik, mas não estamos mais envolvidos.
Também desconheço a existência de uma restrição formal.

[]s

2015-03-12 17:30 GMT-03:00 caduvieira <notifications@github.com>:

**Comment by oliviagj** [comment]
@sahrosa e @erickpintor, precisamos fazer uma avaliação sobre o GA e o Piwik para dizer prós e contras de cada uma das duas ferramentas, pois o @mformiga fará consultas internas no Governo sobre possíveis restrições ao GA e essa visão será útil para ele definir em que direção levar a conversa e o que argumentar, caso necessário. Qual a gente prefere? Por quê?

**Comment by erickpintor** [comment]
Acredito que seja difícil, pelo menos neste momento, dar preferência a uma ferramenta ou outra.

Nossa experiência até então com o Piwik indica que as chamadas à sua API aberta são relativamente lentas. A reposta do servidor pode ser lenta o suficiente para inviabilizar utilização de seus dados no Guia de Serviços sem investir esforços para implementar mecanismos de cache ou coleta pró-ativa dos dados.

Acredito que em termos de velocidade de resposta e estabilidade, GA possa nos atender melhor.

Não sabemos ainda quais tipos de métricas iremos precisar e, principalmente, se ambas as ferramentas oferecem APIs suficientes para suportar nossas analises e hipóteses. Neste caso, minha sugestão seria pegar uma das métricas que precisamos implementar (por exemplo #150) e implementar nas duas ferramentas afim de entender melhor as nossas opções.

O aprendizado gerado pode assim, servir de justificativa para a escolha da ferramenta.

O que acham?

**Comment by cv** [comment]
:+1: @erickpintor

**Comment by sahrosa** [comment]
:+1:

**Comment by jeankirchner** [comment]
:+1:

**Comment by erickpintor** [comment]
Refletindo um pouco mais sobre o assunto e relembrando parte das revelações do Snowden (citado acima), chegamos a outro ponto interessante na discussão sobre Piwik vs GA, que é a questão da privacidade do cidadão.

Considerando que os dados de navegação dos usuários podem ser cruzados a fim de mapear o comportamento de um indivíduo na rede, ao utilizarmos uma ferramenta de coleta de métricas que envia os dados para um serviço terceirizado, estamos quebrando a privacidade de nossos usuários.

Neste caso o Piwik se mostra mais seguro pois, mesmo coletado as mesmas informações que outras ferramentas, temos como garantir que estas informações serão usadas de forma consciente e que nossos usuários irão se manter anônimos.

Tendo isso em mente, temos que refletir se este é um critério que exclui o GA como uma possibilidade. Caso sim, não precisamos mais experimentar as duas opções e devemos então focar em contornar as restrições que o Piwik oferece.

O que acham?

**Comment by mformiga** [comment]
Certamente precisaremos ter a continuidade dos registros no Pwiki. Acredito
que se o GA facilita o trabalho de coleta de métricas pelos motivos já
expostos, poderíamos utilizá-lo temporariamente ao longo do desenvolvimento
deste trabalho.

2015-03-26 16:56 GMT-03:00 Erick Pintor <notifications@github.com>:

**Comment by erickpintor** [comment]
Adicionamos o Piwik ao novo Guia de Serviços utilizando o mesmo código do site atual.

Apenas ambientes com profile ```monitoring``` habilitado irão coletar métricas. Assim, não iremos poluir o servidor com dados de teste enquanto desenvolvemos a aplicação.

```html
<script type="text/javascript" th:if="${#arrays.contains(@environment.getActiveProfiles(),'monitoring')}">
```

@cv @jeankirchner Vocês provavelmente vão ter que levar isso em consideração durante a issue #69 .

**Comment by jeankirchner** [comment]
@erickpintor Blz, por enquanto o profile "monitoring" não está ativo,
 vamos estudar isso melhor quando a infra no lado da DTI estiver disponível
para trabalharmos em cima. Provavelmente vai rolar uma parametrização em
cima do empacotamento, dependendo do ambiente.
