### ISSUE TITLE
Revisar imagem p/ OGP

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#103]
O [OpenGraph](http://ogp.me) pede uma imagem de 200x200 px para servir como logotipo do artigo a ser compartilhado.

**Comment by cv** [comment]
@mformiga e @servicosgovbr/dge - podemos usar essa imagem do perfil do twitter do MPOG por enquanto?

![image](https://cloud.githubusercontent.com/assets/5445/6629123/484c06ee-c8ea-11e4-9e6d-155f1b0fc9a1.png)

**Comment by almeidafab** [comment]
@cv qual seria a conta do twitter (do mpog ou do governo eletrônico)? Também precisaria de uma justificativa para encaminhar para o responsável.

**Comment by cv** [comment]
As imagens foram alteradas para não termos problemas com identidade visual confusa entre entidades. Para conferir os resultados do que está exposto em OGP no Guia:

https://developers.facebook.com/tools/debug/og/object/
