### ISSUE TITLE
Listar serviços por público-alvo

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#107]
(cidadão, empresas)

**Comment by oliviagj** [comment]
#104 #105 #106 #107 devem incluir (ou não) a inclusão de um link para cada uma dessas listas na coluna da esquerda.

**Comment by sahrosa** [comment]
Estou estudando isso nos portais que usamos como comparativo para que a gente possa criar uma seleção nossa, e que faça sentido aos nossos serviços. Abaixo dois exemplos de separação de público-alvo em guias de serviços.

**No México:**
- Mulher
- Adolescente
- Idoso
- Indígena
- Imigrante
- Criança
- Pessoa com Deficiência
- Servidor Público

**Nos Estados Unidos:**
- Cidadão
- Criança
- Negócio
- Visitante
- Idoso
- Servidor Público
- Desenvolvedor

**Comment by cv** [comment]
@sahrosa nos dados de hoje, só temos a separação entre cidadão e empresa. Se a gente for mapear para outros desdobramentos, teríamos que fazer um mutirão e passar de serviço em serviço, reclassificando todos. Acho que é uma boa ideia, mas não para o Release 0.

Podemos criar uma hipótese que revisita isso no futuro (Release 2, talvez) quando tivermos ferramental melhor para editar os serviços.

**Comment by sahrosa** [comment]
De acordo!

**Comment by cv** [comment]
@erickpintor, que tal usar paginação alfabética (que já está pronta nas listagens de órgãos e serviços)? Assim a gente ganha tempo para pensar na busca avançada / facetada, e volta a essas páginas depois, implementando mais públicos-alvo depois, com o ferramental de edição em mãos.

**Comment by erickpintor** [comment]
@cv Pode ser.

**Comment by almeidafab** [comment]
bug reportado na #284
