### ISSUE TITLE
Busca avançada / filtros

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#109]
Precisamos fazer a análise, @mformiga

**Comment by jeankirchner** [comment]
Esse ticket ainda fica para o Release 0? Uma versão mais avançada da busca não é obrigatória para o lançamento, correto?

**Comment by jeankirchner** [comment]
Em relação à esse ticket, é bom lembrar que o próprio servicos.gov.br tem busca avançada, e nós podemos analisar no Piwik o uso desse recurso, e anexar neste cartão.

**Comment by erickpintor** [comment]
Podemos fazer uma analise mais profunda, porém, eu me lembro que os usuários geralmente recorrem à busca avançada quando não encontram o que procuram na busca comum. 

No caso, a própria utilização do formulário de busca avançada é um forte indício de que a busca não está madura o suficiente para atender as necessidades dos cidadãos.

**Comment by sahrosa** [comment]
Estou fechando o cartão pois está fora do escopo, ok @mformiga @almeidafab @gustavo-freitas? :)
