### ISSUE TITLE
Link p/ versão antiga

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#110]

**Comment by oliviagj** [comment]
@mformiga e @almeidafab vão providenciar que haja dois ambientes paralelos enquanto a versão clássica ainda estiver disponível.

**Comment by sahrosa** [comment]
Meus 5 centavos: eu não chamaria de versão clássica, pois isso remeteu a sites versão m. x sites desktop (versão clássica) durante muito tempo antes dos sites se tornarem responsivos. Vamos pensar em algo diferente? Algo como atual x Novo. Atual x Alfa. Etc...

**Comment by cv** [comment]
+1, @sahrosa. Nós mesmos estamos chamando de "versão nova" e "versão antiga", então podemos continuar com isso no texto de ambos os sites. Que tal?
