### ISSUE TITLE
Informações sobre conta

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#111]

**Comment by oliviagj** [comment]
@mformiga e @almeidafab, precisamos do texto que você produziram para isso, por favor.

**Comment by almeidafab** [comment]
O texto que produzimos é o seguinte:

Prezado(a),

O Ministério do Planejamento está aprimorando o Portal Guia de Serviços Públicos do Governo Federal com o objetivo de permitir uma experiência mais agradável de navegação aos serviços.

Enquanto desenvolvemos o novo portal, não será possível a realização de cadastro e o acesso à sua página personalizada. Os gestores responsáveis pelas informações dos serviços continuarão com acesso.

Esclarecemos ainda que as informações dos serviços continuarão disponíveis para pesquisa no portal.

Agradecemos sua compreensão.

**Comment by cv** [comment]
Link: http://gds-alpha.herokuapp.com/conteudo/sua-conta
