### ISSUE TITLE
Informações da página "Contato" mais convenientes

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/portal-de-servicos#112]
Informações visíveis no site atual no link "[Contato](http://www.servicos.gov.br/faleconosco)" tem mais serventia nas paginas de cada órgão listado.

O @caduvieira deu um exemplo muito bom de como estas informações podem ser marcadas de forma semântica, na página do [MDS](http://gds-alpha.herokuapp.com/orgao/ministerio-do-desenvolvimento-social-e-combate-a-fome-mds), e acho que devemos seguir uma linha parecida.

Estes são os órgãos com informações existentes no guia atual:

- [x] Ministério da Educação
- [x] Ministério da Previdência Social
- [x] Ministério da Saúde
- [x] Ministério da Justiça
- [x] Ministério do Trabalho e Emprego	
- [x] Ministério do Desenvolvimento Social e Combate à Fome	
- [x] Receita Federal	
- [x] Ministério do Planejamento	
- [x] Ministério do Turismo	
- [x] Secretaria de Aviação Civil	
- [x] Banco Central do Brasil	
- [x] Ministério da Agricultura, Pecuária e Abastecimento	
- [x] Ministério da Fazenda	
- [x] Ministério da Pesca e Aquicultura

**Comment by cv** [comment]
Todas as informações disponíveis na página de contato foram movidas para as páginas dos órgãos, mas ainda precisam de revisão (e talvez alguma edição).

**Comment by cv** [comment]
Alguém se habilita, @servicosgovbr/devs? :)

**Comment by jeankirchner** [comment]
Falta alguma coisa ainda? Eu vi os commits e tem muita coisa feita, sobrou algo?
