### ISSUE TITLE
Limpar duplicação de itens das linhas da vida

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/portal-de-servicos#113]
Implementar o mapeamento de linhas da vida conforme análise do #55:

- [x] Abrir um negócio -> Administrar um negócio
- [x] Administrar um negócio -> Administrar um negócio
- [x] Adolescentes -> Adolescentes
- [x] Aposentar-se -> Aposentar-se
- [x] Aproveitando o tempo livre -> Aproveitar o tempo livre
- [x] Cuidando da saúde -> Cuidar da saúde
- [x] Emitindo meus documentos -> Emitir documentos
- [x] Estudando -> Estudar
- [x] Garantindo meus direitos -> Garantir direitos
- [x] Indo para outro país -> Viajar
- [x] Mantendo um veículo -> Manter um veículo
- [x] Meu Negócio -> Administrar um negócio
- [x] Meu negócio -> Administrar um negócio
- [x] Obter Crédito e Apoio financeiro -> Obter crédito e apoio financeiro
- [x] Pagando contas e impostos -> Pagar contas e impostos
- [x] Prestando serviço militar -> Prestar serviço militar
- [x] Procurando emprego -> Trabalhar
- [x] Ter filhos -> Ter uma família
- [x] Ter uma casa -> Ter uma casa
- [x] Ter uma família -> Ter uma família
- [x] Trabalhando -> Trabalhar

O ideal é que estes mapeamentos sejam fáceis de alterar, mas não é necessário neste momento fazer nenhum tipo de CRUD ou área de administração. Podemos implementar o mapeamento usando algum arquivo de configurações. É OK se precisarmos gerar  um novo pacote / deployment e reimportar o XML legado caso eles tenham que ser alterados.

**Comment by sahrosa** [comment]
Concordo com os teus pontos @almeidafab, sobre: "Viajar para o exterior" ser melhor, e "procurando emprego" e "trabalhar" serem diferentes :)

Sobre "ter uma família" e "ter filhos", eu não entendo bem a diferença. Vou dar uma estudada melhor sobre isso, mas se tiver alguma informação importante, é só falar!

**Comment by cv** [comment]
Pensei em juntar "procurando emprego" e "trabalhando" pelo número de serviços na primeira ser bastante reduzido, e de certa forma um tanto desconexo: http://gds-alpha.herokuapp.com/linha-da-vida/procurando-emprego

Mesma coisa sobre "ter uma família" e "ter filhos" (1 serviço cada, respectivamente).

**Comment by jeankirchner** [comment]
Esse mapeamento é simplesmente um "de -> para" de termos/frases, conforme eles são lidos do xml legado? 

Acredito que por enquanto um arquivo de configuração seja melhor. Assim caso um mapeamento melhor for identificado, a mudança é simples.

**Comment by cv** [comment]
@jeankirchner sim, um `Map<String, String>` lido do `application.yaml` seria suficiente. [Esta thread do SO](http://stackoverflow.com/questions/24917194/spring-boot-inject-map-from-application-yml) tem informações relevantes.

**Comment by sahrosa** [comment]
Faz todo o sentido, @cv, criar apenas itens que possuam conteúdos para o cidadão. 

Eu comecei a analisar como são organizadas as linhas da vida lá fora, pra gente definir um modelo pro Brasil (mas não para um release 0 ou 1, necessariamente). Uma das coisas que acho que vai ser legal é ter macro áreas como essas (abaixo), junto com as micro e seus serviços:

**Minha Família**
- Nascimento
- Morte
- Adoção
- Casamento
- Separação
- Adolescência
- Deficiência
- Tempo Livre
- Manter um veículo
- Viajar para o exterior
- Comprar uma casa
- Pensões
- Prestar serviço militar
- Cuidar da saúde
- Emitir documentos
- Meus direitos
- Filhos

**Negócios**
- Administrar um negócio
- Abrir um negócio
- Obter crédito e apoio financeiro
- Pagar contas e impostos

**Emprego**
- Primeiro emprego
- Procurando emprego
- Direitos
- Deveres
- Férias

**Aposentadoria**
- Para mulher
- Para homem
- Para pessoa com deficiência

**Comment by almeidafab** [comment]
"Ter uma família" é uma macro categoria de "ter filhos" com a @sahrosa citou. 
Minha sugestão é a seguinte: para a versão que irá para produção retirar "Ter uma familia" e o serviço associado a ela ir para "Trabalhar" porque no meu entedimento tem mais haver com um trabalhador do que família. Com isso não ficaria mais fácil criar macro categorias em releases futuros como a samantha sugeriu?

**Comment by augusto-herrmann** [comment]
Um serviço não pode estar em mais de uma categoria ao mesmo tempo?

**Comment by cv** [comment]
Pode sim, @augusto-herrmann – temos vários exemplos do tipo no XML atual. Para este cartão, especificamente, queria deixar qualquer atividade que envolvesse remapear, serviço a serviço, algum campo. Renomear uma linha da vida ou órgão, por exemplo, pode ser feito sem isso,

**Comment by jeankirchner** [comment]
A #55 Também comenta sobre uma possível normalização da parte de eventos das linhas de vida. Que acham ter um ticket para isso?

**Comment by cv** [comment]
Podemos criar, mas me parece que a categorização dos eventos está muito, muito suja. 




Acho que é melhor partir para o ferramental de recategorização quando chegar essa hora. 



- cv

**Comment by jeankirchner** [comment]
@sahrosa essa tradução de termos, vai ser feito por meio de uma configuração simples por enquanto. Essa à seguir é o que está sendo usado por enquanto, nesse formato mesmo. Qualquer mudança é muito fácil fazer, só incluir novos, remover, ou alterar.

        Abrir um negócio:  Administrar um negócio
        Administrar um negócio:  Administrar um negócio
        Adolescentes:  Adolescentes
        Aposentar-se:  Aposentar-se
        Aproveitando o tempo livre:  Aproveitar o tempo livre
        Cuidando da saúde:  Cuidar da saúde
        Emitindo meus documentos:  Emitir documentos
        Estudando:  Estudar
        Garantindo meus direitos:  Garantir direitos
        Indo para outro país:  Viajar
        Mantendo um veículo:  Manter um veículo
        Meu Negócio:  Administrar um negócio
        Meu negócio:  Administrar um negócio
        Obter Crédito e Apoio financeiro:  Obter crédito e apoio financeiro
        Pagando contas e impostos:  Pagar contas e impostos
        Prestando serviço militar:  Prestar serviço militar
        Procurando emprego:  Trabalhar
        Ter filhos:  Ter uma família
        Ter uma casa:  Ter uma casa
        Ter uma família:  Ter uma família
        Trabalhando:  Trabalhar

**Comment by sahrosa** [comment]
Show de bola @jeankirchner!

Pessoal, minha sugestão de organização para o Release 0 é a de usarmos o nome da categoria (administração de um negócio) ao invés da ação (administrar um negócio). Ficaria mais ou menos assim:

![image](https://cloud.githubusercontent.com/assets/2932644/6677416/8a845e54-cc0e-11e4-8e61-6bd9cd328b0a.png)

Portanto o de:para fica assim ó:

```
Abrir um negócio:  Administração de um negócio
Administrar um negócio:  Administração de um negócio
Adolescentes:  Adolescentes
Aposentar-se:  Aposentadoria
Aproveitando o tempo livre:  Tempo livre
Cuidando da saúde:  Saúde
Emitindo meus documentos:  Emissão de documentos
Estudando:  Educação
Garantindo meus direitos:  Meus direitos
Indo para outro país:  Viagens para o exterior
Mantendo um veículo:  Veículos
Meu Negócio:  Administração de um negócio
Meu negócio:  Administração de um negócio
Obter Crédito e Apoio financeiro:  Crédito e apoio financeiro
Pagando contas e impostos:  Contas e impostos
Prestando serviço militar:  Serviço militar
Procurando emprego:  Emprego
Ter filhos:  Família e filhos
Ter uma casa:  Casa
Ter uma família:  Família e filhos
Trabalhando:  Trabalhar
```

**Comment by jeankirchner** [comment]
Uma vez que os títulos forem normalizados, vai gerar algumas linhas da vida duplicadas. A solução discutida até o momento é fundir as linhas da vida, colocando os eventos de todas as duplicadas dentro da mesma linha da vida. E no caso de eventos duplicados, serão removidas as duplicadas idênticas.

**Comment by sahrosa** [comment]
O que acham desse modelo de organização (abaixo) de eventos da linha da vida, @mformiga e @almeidafab? 

```
ATUAL : SUGERIDO
Abrir um negócio:  Administração de um negócio
Administrar um negócio:  Administração de um negócio
Adolescentes:  Adolescentes
Aposentar-se:  Aposentadoria
Aproveitando o tempo livre:  Tempo livre
Cuidando da saúde:  Saúde
Emitindo meus documentos:  Emissão de documentos
Estudando:  Educação
Garantindo meus direitos:  Meus direitos
Indo para outro país:  Viagens para o exterior
Mantendo um veículo:  Veículos
Meu Negócio:  Administração de um negócio
Meu negócio:  Administração de um negócio
Obter Crédito e Apoio financeiro:  Crédito e apoio financeiro
Pagando contas e impostos:  Contas e impostos
Prestando serviço militar:  Serviço militar
Procurando emprego:  Emprego
Ter filhos:  Família e filhos
Ter uma casa:  Casa
Ter uma família:  Família e filhos
Trabalhando:  Trabalhar
```

O que eu gosto neste modelo, é que quando o usuário clica em algum desses eventos da linha da vida, ao chegar na sua página,  encontram o texto **"Aposentadoria"** ao invés de **"Aposentar-se"**. Isso quer dizer que ele vai encontrar serviços relacionados a aposentadoria, algo abrangente, e não à ação de se aposentar, algo específico. Este se assemelha ao formato que o Reino Unido e Nova Zelândia utilizam.

A outra opção é manter a ação **"Administrar um negócio"**, no sentido da ação de realizar algo, ao invés de usar o **"Administração de um negócio"**.   Este se assemelha ao formato que a Noruega utiliza.

Nos avisem para que possamos editar (ou não) essas nomenclaturas :-)

**Comment by mformiga** [comment]
Favor inserir o everson nesta discussão


Abrir um negócio:  Administração de um negócio
Administrar um negócio:  Administração de um negócio
Adolescentes:  Adolescentes*- **Adolescentes está mais para
público-alvo específico, abre margem para muitos outros*

Aposentar-se:  Aposentadoria*- Melhor mesmo, até porque há desaposentadoria*

Aproveitando o tempo livre:  Tempo livre

*- Não acha que ficaria mais difícil de entender do que se trata ?
Colocaria aproveitar o tempo livre*


Cuidando da saúde:  Saúde

*- Assim fica igual à área de interesse do VCGE, ou seja, repetido.
Colocaria Cuidar da saúde.*


Emitindo meus documentos:  Emissão de documentos

Indo para outro país:  Viagens para o exterior

Estudando: Educação

*- Assim fica igual à área de interesse do VCGE, ou seja, repetido.
Colocaria Estudar.*

Garantindo meus direitos: Meus direitos Mantendo um veículo: Veículos

*- Colocaria "manter um veículo"*


Meu Negócio:  Administração de um negócio
Meu negócio:  Administração de um negócio
Obter Crédito e Apoio financeiro:  Crédito e apoio financeiro
Pagando contas e impostos:  Contas e impostos
Prestando serviço militar:  Serviço militar
Procurando emprego:  Emprego

*- Ver comentários sobre "Trabalhar"*


Ter filhos:  Família e filhos
Ter uma casa:  Casa

*- Acho que seria melhor habitação.*


Trabalhando:  Trabalhar

*- acho que este item pode juntar com emprego, ficando apenas "Trabalhar"*






2015-03-19 18:21 GMT-03:00 Samantha Rosa <notifications@github.com>:

**Comment by almeidafab** [comment]
O @mformiga levantou um ponto importante. Temos de tomar cuidado para não termos duas formas de categorização quase que iguais mas com nomes diferentes (linhas da vida e categorias do VCGE). Talvez esses nomes que estão parecidos com o VCGE podemos deixá-los com a escrita que estava antes.

**Comment by sahrosa** [comment]
Excelentes pontos @almeidafab e @mformiga! Vou dar uma olhada nas sugestões de vocês e organizar de acordo com o que conversamos agora.

**Comment by jeankirchner** [comment]
Conforme:
http://governoeletronico.gov.br/acoes-e-projetos/e-ping-padroes-de-interoperabilidade/vcge

Podemos sugerir mudanças para o VCGE, se acharmos interessante alguma
categorização mais refinada.

Só não sei o quão difícil/fácil é para fazer essas sugestões.

**Comment by eversonaguiar1** [comment]
Pessoal, foi realizado a pouco um estudo de migração do vcge 1.0 para o 2.0 por um colega da SLTI para o sistema e-SIC de solicitação de informações da Lei de acesso  a Informação da CGU. Estamos conversando internamente sobre se isso e se poderá ser útil para o projeto...
