### ISSUE TITLE
Visibilidade para requisitos transversais

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#115]

**Comment by oliviagj** [comment]
@mformiga e @almeidafab vão verificar junto à DTI e/ou Serpro a possibilidade de deixar à mão um plano de contingência, muito provavelmente uma opção de rapidamente reverter o domínio ou redirecionar o usuário para a versão clássica do Guia de Serviços,

**Comment by cv** [comment]
Depois do 169f6e5, a performance fica mais fácil: exceto o POST de feedback e a importação inicial, todos os acessos ao ElasticSearch (e ao Guia, portanto) são somente-leitura. Podemos estabelecer políticas de caching bem agressivas.

**Comment by cv** [comment]
Fiz alguns testes preliminares na nova infraestrutura da Amazon EC2. A máquina é bem menor do que as que teremos em produção (1gb RAM, 512 Mb SSD, 1 core) e parece aguentar bem:

```
This is ApacheBench, Version 2.3 <$Revision: 1430300 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 172.31.16.13 (be patient)
Finished 4030 requests


Server Software:        Apache-Coyote/1.1
Server Hostname:        172.31.16.13
Server Port:            80

Document Path:          /
Document Length:        17205 bytes

Concurrency Level:      1
Time taken for tests:   60.000 seconds
Complete requests:      4030
Failed requests:        0
Write errors:           0
Total transferred:      70307380 bytes
HTML transferred:       69336150 bytes
Requests per second:    67.17 [#/sec] (mean)
Time per request:       14.888 [ms] (mean)
Time per request:       14.888 [ms] (mean, across all concurrent requests)
Transfer rate:          1144.32 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.2      0      10
Processing:     7   14  27.8     11    1702
Waiting:        7   14  27.5     11    1676
Total:          7   15  27.8     12    1702

Percentage of the requests served within a certain time (ms)
  50%     12
  66%     18
  75%     20
  80%     20
  90%     23
  95%     27
  98%     35
  99%     41
 100%   1702 (longest request)
```

**Comment by jeankirchner** [comment]
Tem algo mais específico que queremos nesse ticket, ou a medição já feita é o suficiente?

**Comment by erickpintor** [comment]
@jeankirchner Acho que já temos como parte do Piwik. Mas vale a pena dar uma conferida.

**Comment by jeankirchner** [comment]
Uma idéia é fazer alguns testes de fumaça usando selenium (ou simplesmente uma série de links com curl ou algo do gênero), rodando alguma ferramenta que faz o profiling (próprio ApacheBench?), e publicar os reports em alguma coisa parecida com o https://coveralls.io, só que para performance.

Não sei se existe alguma, alguém conhece?
