### ISSUE TITLE
Montar a página do Guia de Estilos

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/portal-de-servicos#119]
Fontes, tipografia, padrões de botões e suas interações, etc. Construir um style guide "vivo" que poderemos ir modificando ao longo do ano.

**Comment by sahrosa** [comment]
Além dos estilos visuais que iremos incluir nesse style guide, fico pensando se não podemos ter uma área para o tom de voz que o Guia quer usar com os cidadãos, sabem?

Como humanizar é uma das nossas oportunidades que aprendemos com os mapas de experiência, lá na Inception, seria lindo se pudéssemos trabalhar em conjunto para definir alguns guias de escrita para que os órgãos possam se basear. A gente chama isso de "brand persona": assim como temos personas para entender quem são os usuários, podemos ter a nossa persona de quem está do outro lado, atendendo o cidadão. É um homem ou uma mulher? Essa "pessoa" que está atendendo fala de forma mais amigável ou é direta ao ponto?

Essas decisões nos ajudam a definir como são as mensagens de erro, as confirmações de envio de formulários, textinhos explicativos, etc. Sei que isso não é prioridade nos primeiros releases, mas é minha grande paixão e acredito que podemos ir construindo algo bem legal para atender ainda melhor os cidadãos :)

Um exemplo excelente para isso é o MailChimp: http://voiceandtone.com/

Acho melhor até criar uma issue diferente para isso, certo?

**Comment by caduvieira** [comment]
A Silvia pediu para a Cátia `encarnar` essa persona. Creio que o
@almeidafab pode falar sobre isso.
Em 13/03/2015 16:48, "Samantha Rosa" <notifications@github.com> escreveu:

**Comment by almeidafab** [comment]
Esse guia de estilos funcionaria também como um script para nos ajudar a responder os questionamentos dos cidadãos?
A Cátia responde a maioria dos emails que chegam e eu ajudo nos emails mais técnicos, quando há problemas no sistema. Tenho umas respostas padrão, acredito que a Cátia também tenha. Na montagem desse guia ajudaria se eu enviasse alguns emails respondidos pela gente?

**Comment by sahrosa** [comment]
Movendo o assunto do guia de linguagem para a #137

**Comment by jeankirchner** [comment]
Eu acho isso muito relevante, principalmente pela consistência que eu
espero nos sites do governo, já sabendo como o conteúdo está estruturado,
escrito, tom de voz, enfim.

E acho que esse pode ser um dos ítens à ser incluído na parte de Conteúdo
do Modelo de Maturidade, e acho que vai ser a documentação mais forte em
tentar manter os serviços e a evolução do projeto na linha, junto com
devidos evangelizadores apontados. Como o @caduvieira falou, a Cátia seria
um exemplo de uma dessas pessoas para ajudar a manter as coisas na linha.

O que acham?

**Comment by sahrosa** [comment]
Concordo @jeankirchner! Só vamos manter essa conversa na #137 pra acabar não misturando as coisas (bagunça que eu comecei ehehehe)

**Comment by sahrosa** [comment]
Enquanto não vai saindo o grid (tá acabando!!) vamos começando a ter um Guia de Estilos! A ideia é ter um /guia-de-estilos com isso tudo lá, pra facilitar muito a nossa vida. Mas por enquanto temos uma imagem pra dar a ideia.

![guia de estilos](https://cloud.githubusercontent.com/assets/2932644/6854939/314ca6bc-d3d3-11e4-951f-5d960d1eda45.jpg)

**Comment by caduvieira** [comment]
Sugestão: fa-tty para contato.
Fa-futbol-o para tempo livre ficar diferente da aposentadoria.
Em 26/03/2015 16:14, "Samantha Rosa" <notifications@github.com> escreveu:

**Comment by almeidafab** [comment]
@sahrosa tem alguma url criada para o guia de estilos?

**Comment by cv** [comment]
@almeidafab http://servicosgovbr.github.io/guia-de-servicos/design/index.html
