### ISSUE TITLE
Serviços relacionados

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#129]
Removemos a exibição de serviços relacionados quando migramos para o novo estilo, e gostaríamos de tê-los de volta.

A considerar:

- Usar o mesmo estilo das linhas de destaques?
- Quais campos determinam a relação? Título e Descrição, apenas?

**Comment by cv** [comment]
Poderemos utilizar os novo campo de palavras-chave da v3 para realizar esta busca.

**Comment by sahrosa** [comment]
Oi @mformiga @almeidafab @gustavo-freitas! Estou fechando o cartão pois está fora do escopo.
