### ISSUE TITLE
Compatibilidade de URLs de busca

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#130]
Alguns sites do governo, como o MEC, usam links diretos para a URL `/search?SearchableText=`.

Ao migrar para a nova plataforma, não podemos quebrar estes links.

**Comment by jeankirchner** [comment]
Esse é o único link que vamos nos preocupar, ou um levantamento ainda deve ser feito?

**Comment by jeankirchner** [comment]
Isso já está sendo trabalhado ou já foi resolvido? pergunto por causa dos cards #132, #133...

Ou é um card mais amplo em relação à esse problema de links?

**Comment by cv** [comment]
Este já foi resolvido pelo PR #133 – mas se o levantamento da #132 apontar novos problemas, vamos criar novos cartões.
