### ISSUE TITLE
Conteúdo no tema branco

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/portal-de-servicos#136]
Ajustar o protótipo para o tema branco.

**Comment by sahrosa** [comment]
Primeiro teste usando o tema branco! 

![image](https://cloud.githubusercontent.com/assets/2932644/6756303/a2e9228a-cf07-11e4-8183-c0e2ccdb2cd6.png)

Minhas impressões: 
- Fica neutro, como comentamos na reunião-em-pé, o que converge com a idea de ser um site que engloba os serviços de todos os outros portais (que são azuis, verdes, amarelos).  
- Por ser um tom mais tranquilo, mais sereno, passa mais tranquilidade em termos de cores, o que pode ser bom para o cidadão procurando informações importantes pra sua vida.
- Foi preciso modificar algumas cores de azul para cinza (pontos 1,2,3,4 de acessibilidade, por exemplo) para ficar harmônico.
- Em resumo, gostei.

E vocês, o que acham? :)

**Comment by cv** [comment]
Gostei bastante :+1:

**Comment by eversonaguiar1** [comment]
gostei também... o governo trabalha muito com o verde...

**Comment by almeidafab** [comment]
muito bom!

**Comment by mformiga** [comment]
Os argumentos também são bons para justificar a escolha.

**Comment by oliviagj** [comment]
eu também gostei muito :-)

**Comment by sahrosa** [comment]
Obrigada pelas opiniões, pessoal! 

Só pra dar um preview pra vocês de como estou testando os estilos na página inicial, para posteriormente colocarmos em prod quando tivermos h1, h2, p, etc definidos. Estou gostando mas ainda temos bastante coisas pra testar :)

![gds pagina inicial_v1](https://cloud.githubusercontent.com/assets/2932644/6786689/a4d840aa-d16c-11e4-993d-1df5f79571b5.jpg)

**Comment by cv** [comment]
Não esquece de revisar os estilos de alto contraste, @sahrosa! ;)

**Comment by sahrosa** [comment]
Obrigada pelo lembrete, @cv! Acabei de ver aqui e vou ajustar!

**Comment by sahrosa** [comment]
Ajustes visuais:

- [ ] Destaques principais
- [ ] Filtro de A-Z
- [ ] Perguntas frequentes

**Comment by almeidafab** [comment]
@sahrosa o estilo dos serviços em destaque vai mudar ainda?

**Comment by sahrosa** [comment]
Oi @almeidafab! Não precisamos mudar agora, mas podemos mudar conforme aprendermos sobre o uso/sentirmos necessidade. 

O desenho inicial está diferente do modelo que estamos usando agora (menos destaques, ícones azuis, etc). Acho que como está agora ainda não está 100%, mas está cumprindo seu papel. 

Vocês tem feedbacks sobre os destaques para que possamos dar uma melhorada? :)

**Comment by almeidafab** [comment]
oi @sahrosa. Não tenho feedback, é que eu tinha visto a imagem que vc postou neste card e a área de serviços em destaque está um pouco diferente do alpha. Mas concordo com vc, podemos esperar e aprender conforme o uso.
