### ISSUE TITLE
Guia de Linguagem

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/portal-de-servicos#137]
Criei essa nova issue para mantermos o guia de linguagem, que seria o guia do tom de voz que o Guia de Serviços irá usar com os cidadãos. Abaixo os comentários que rolaram sobre o assunto:

Aqui o comentário no outro post: 

```
Como humanizar é uma das oportunidades que aprendemos com os mapas de experiência, 
lá na Inception, seria lindo se pudéssemos trabalhar em conjunto para definir alguns 
guias de escrita para que os órgãos possam se basear. A gente chama isso de 
"brand persona": assim como temos personas para entender quem são os usuários, 
podemos ter a persona de quem está do outro lado, atendendo o cidadão. É um 
homem ou uma mulher? Essa "pessoa" que está atendendo fala de forma mais 
amigável ou é direta ao ponto?

Essas decisões nos ajudam a definir como são as mensagens de erro, as confirmações 
de envio de formulários, textinhos explicativos, etc. Sei que isso não é prioridade 
nos primeiros releases, mas é minha grande paixão e acredito que podemos ir 
construindo algo bem legal para atender ainda melhor os cidadãos :)

Um exemplo excelente para isso é o MailChimp: http://voiceandtone.com/
```

Em cima disso @caduvieira comentou:

```
A Silvia pediu para a Cátia `encarnar` essa persona. Creio que o
@almeidafab pode falar sobre isso.
```

E @almeidafab respondeu:
```
Esse guia de estilos funcionaria também como um script para nos ajudar a responder 
os questionamentos dos cidadãos? A Cátia responde a maioria dos emails que chegam 
e eu ajudo nos emails mais técnicos, quando há problemas no sistema. Tenho umas 
respostas padrão, acredito que a Cátia também tenha. Na montagem desse guia 
ajudaria se eu enviasse alguns emails respondidos pela gente?
```

Sobre as perguntas de vocês, seria ótimo se pudermos ver alguns emails respondidos sim, aí podemos trabalhar a partir disso pra criar esse modelo consciente de como nos comunicarmos com o cidadão :)

**Comment by sahrosa** [comment]
Vamos continuar a conversa sobre guia de linguagem ter relação com níveis de maturidade aqui, @jeankirchner, @mformiga e @almeidafab!

**Comment by sahrosa** [comment]
Pessoal, criei uma documentação inicial para auxiliar a escrever conteúdos mais relevantes. Muito foi baseado em conceitos do gov.uk e em materiais sobre content design: http://servicosgovbr.github.io/guia-de-servicos/conteudo/index.html

Acho que está suficiente para o momento, e podemos ir melhorando conforme a necessidade! 

Quanto ao brand persona, acho que podemos marcar uma conversa específica sobre isso, para entender melhor e propor algo. O que acha @almeidafab? :)

**Comment by almeidafab** [comment]
gostei da documentação @sahrosa nada muito extenso que possa desaminar quem vai escrever o serviço. Vou homologar esse cartão e podemos marcar outra conversa sobre brand persona, sem problemas.

**Comment by sahrosa** [comment]
Show!!
