### ISSUE TITLE
Revisão do conteúdo

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/portal-de-servicos#142]
- [x] Linhas da vida
- [x] Fale com o governo
- [x] Sobre o Guia
- [x] Página do Órgão (revisão simples do que já está proposto)
- [x] Perguntas frequentes
- [x] Acessibilidade
- [x] [Agradecimento do feedback](http://ec2-54-94-244-36.sa-east-1.compute.amazonaws.com/conteudo/obrigado-pela-contribuicao)

Informações úteis estão ok, não há confusão entre o que está em informações úteis e canal de prestação

**Comment by cv** [comment]
Exemplos de serviços com problemas nos canais de prestação na #56 (que está bloqueada pendente esta revisão)

**Comment by oliviagj** [comment]
@mformiga: Silvia está tentando envolver o Bruno (ASEGE) nesta atividade

**Comment by oliviagj** [comment]
Desdobrada para #163

**Comment by almeidafab** [comment]
Após analisar o campo "Informações Úteis" e alinhar com o @mformiga, chegamos a conclusão de que é melhor não mexer nessas informações. Ex.: alguns serviços tem telefone nesse campo mas funciona muito mais para tirar dúvidas do que executar propriamente o serviço. Colocar essa informação no canal poderia direcionar a execução do serviço para esse telefone e o órgão não estar preparado para suportar tal demanda.
Nós estamos concentrando essa revisão de conteúdo na análise das linhas da vida com os serviços. Vou ajudar Bruno e Everson nisso.

**Comment by cv** [comment]
Mais uma página que vale a pena revisar: a de [agradecimento do feedback](http://ec2-54-94-244-36.sa-east-1.compute.amazonaws.com/conteudo/obrigado-pela-contribuicao).

**Comment by almeidafab** [comment]
Pessoal, achamos melhor deixar as linhas da vida sem o texto introdutório. Na página de cada linha aparecer somente o título e os serviços relacionados a ela.
