### ISSUE TITLE
Navegação pela tecla tab

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/portal-de-servicos#143]
Com destaque

**Comment by almeidafab** [comment]
@cv ainda vemos algumas melhorias na navegação pelo teclado. O portal brasil e o site da secom são bons exemplos (brasil.gov.br e secom.gov.br). Nesses portais a navegação pelo tab começa na barra brasil e o foco possui uma borda com destaque. Na versão alpha a navegação pelo teclado começa no cabeçalho depois vai para barra brasil e depois volta para o conteúdo. Não tem uma sequencia lógica.

Ver no eMAG (http://emag.governoeletronico.gov.br/):
"Recomendação 4.4 – Possibilitar que o elemento com foco seja visualmente evidente" e "Recomendação 1.4 – Ordenar de forma lógica e intuitiva a leitura e tabulação"

**Comment by sahrosa** [comment]
Oi @almeidafab! Só pra confirmar, para ficar no padrão, o que precisamos fazer é inverter o início e começar pela barra brasil em 1º lugar ao invés dos botões de acessibilidade?

**Comment by almeidafab** [comment]
@sahrosa conversei com o @caduvieira para tirar minha dúvida. O alpha está correto mesmo, falha minha, apenas uma observação na ordem: depois que o foco sair da barra brasil, ele deve ir primeiro para bloco de conteúdo (barra de busca e destaques) e não para o menu da esquerda. O menu da esquerda vem depois do conteúdo.

**Comment by sahrosa** [comment]
Criei um novo cartão #304 pra esse ajuste, @almeidafab!
