### ISSUE TITLE
Feedback complementar no topo da Início

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/portal-de-servicos#144]
exemplo de referência: http://beta.australia.gov.au/ e http://beta.australia.gov.au/content/about-beta

![image](https://cloud.githubusercontent.com/assets/8646350/6830800/f7cc4966-d2fa-11e4-879a-dba44987489f.png)

**Comment by jeankirchner** [comment]
Nessa parte:

 Não
Dê sua opinião:

Parece que está um pouco colado um no outro.

**Comment by erickpintor** [comment]
Não há formatação formulário de feedback, apenas marcações html.
O layout está sendo ajustado pela @sahrosa e o @cv como parte da revisão do grid e criação do guia de estilos.

**Comment by cv** [comment]
Sim, isso está sendo resolvido pela #119 e #136.
