### ISSUE TITLE
Aprimorar pedido de feedback

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/portal-de-servicos#146]
A frase não está boa, sugere que houve um problema

**Comment by erickpintor** [comment]
Alguém já tem alguma sugestão de texto?

**Comment by oliviagj** [comment]
Sugestão pronta não, mas a gente comentou de exemplos de outros sites, né não, @sahrosa? você lembra?

**Comment by sahrosa** [comment]
Exemplos na issue #41

**Comment by cv** [comment]
Outra sugestão vinda da reunião de ontem: colocar o pedido de feedback mais ao topo da página, próximo (ou até em substituição) ao link para o site antigo, no arquivo `barra-versao-antiga.html`.

**Comment by oliviagj** [comment]
@cv, essa é a #144

**Comment by cv** [comment]
@oliviagj sim, e acho que dá para fazer as duas ao mesmo tempo. Procede, @erickpintor?

**Comment by erickpintor** [comment]
Estamos pensando em mudar um pouco o formulário.

No momento ele direciona o usuário a uma resposta negativa, o que não é ruim se observarmos do ponto de vista que precisamos entender os pontos de dor para o usuário e agir para melhorar sua experiência. Porém, este formato pode inibir feedbacks positivos ou sugestões.

Estamos pensando em fazer uma abordagem diferente. Algo no seguinte formato:

> Você achou o que estava procurando: () Sim () Não.
> Deixe sua opinião: <campo de texto>

O que acham?

Neste caso, eu prefiro manter as tarefas separadas e forcar em cada pedaço de uma vez.

**Comment by caduvieira** [comment]
:+1: para colocar no topo
Em 25/03/2015 16:09, "Erick Pintor" <notifications@github.com> escreveu:

**Comment by jeankirchner** [comment]
+1
() Sim () Não é algo melhor e mais simples ao invés de uma nota (tipo
estrelinhas do IMDB) e acho que ajuda a ter uma visão mais clara se estamos
atendendo ou não expectativas. E a parte escrita é muito bom para
entendermos tanto o comportamento do usuário/forma de pensar, quanto as
dores mais comuns que ele sente.

**Comment by erickpintor** [comment]
Pessoal, a nova versão do formulário de feedback já está no ar.
Por favor, revisem e me mandem feedback ( por aqui e não pelo form :p )

Lembrando que as alterações no layout serão feitas na #144

**Comment by sahrosa** [comment]
Muito bom @erickpintor! Apenas precisamos que o "sim" também venha desmarcado, pra ninguém enviar um "sim" ao invés de "não" sem querer :)

**Comment by erickpintor** [comment]
Pronto @sahrosa :)
