### ISSUE TITLE
Aprimorar página do órgão

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/portal-de-servicos#149]
1. Fontes diversas de informação (Siorg, páginas dos órgãos, etc.)
2. Indicar fontes na página
3. Categorização específica por órgão
4. Vamos colocar destaques? Qual será o critério?

**Comment by oliviagj** [comment]
@mformiga: aqui podemos conversar sobre a idéia de fazer da página do órgão sua carta de serviços

**Comment by jeankirchner** [comment]
@oliviagj, @mformiga isso será tratado pela #175

**Comment by cv** [comment]
Fechando esse cartão, já que as páginas dos órgãos serão revistas pela #444 e #284
