### ISSUE TITLE
Aprimorar seleção de destaques

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/portal-de-servicos#150]

**Comment by oliviagj** [comment]
verificar duplicação

**Comment by erickpintor** [comment]
A título de informação, eu encontrei um bash script que eu estava usando pra pegar alguns dados do Piwik:

```bash
SERVICOS_SUB_TABLE=$(
  curl -s -k "https://estatisticas.presidencia.gov.br/index.php?module=API&method=Actions.getPageUrls&idSite=2&period=range&date=last90&filter_limit=3&format=JSON&token_auth=TOKEN_VAI_AQUI" |
    jq '.[] | select(.label == "repositorioServico") | .idsubdatatable'
)

curl -s -k "https://estatisticas.presidencia.gov.br/index.php?module=API&method=Actions.getPageUrls&idSite=2&period=range&date=last90&idSubtable=$SERVICOS_SUB_TABLE&filter_limit=10&format=JSON&token_auth=TOKEN_VAI_AQUI" |
  jq '.[].label'
```

PS: Removi o token de acesso por motivos de segurança.

Algumas considerações:
Ao buscar por ```Actions.getPageUrls``` o resultado já vem ordenado pelos mais acessados. Porém, a estrutura não é "flat".

```json
[ ...
  {
    "label": "repositorioServico",
    "nb_visits": 1023053,
    "nb_hits": 2475520,
    "sum_time_spent": 51784982,
    "nb_hits_with_time_generation": 2293691,
    "min_time_generation": "0.001",
    "max_time_generation": "681.605",
    "entry_nb_visits": 414753,
    "entry_nb_actions": 1142801,
    "entry_sum_visit_length": 30712005,
    "entry_bounce_count": 209466,
    "exit_nb_visits": 455610,
    "avg_time_on_page": 51,
    "bounce_rate": "51%",
    "exit_rate": "45%",
    "avg_time_generation": 0.617,
    "idsubdatatable": 1147
  }
... ]
```

Para visualizar os itens dentro do nó ```repositorioServico``` é preciso efetuar outra chamada para a API informando o parâmetro ```idSubtable``` com o valor informado pelo JSON anterior. Existe também a opção de passar um parâmetro chamado ```flat```, porém, o Piwik não responde quando requisitado por um período de dadas + uma estrutura flat.

Por isso o bash faz duas chamadas.

**Comment by jeankirchner** [comment]
@erikpintor, quanto à essa parte: `Existe também a opção de passar um parâmetro chamado flat, porém, o Piwik não responde quando requisitado por um período de dadas + uma estrutura flat.`. Eu fiz o request com o parâmetro `expanded=1`, e vem várias sub páginas ao invés de idDataTable.

**Comment by jeankirchner** [comment]
@erickpintor para referência, a url completa que eu usei: https://estatisticas.presidencia.gov.br/index.php?module=API&method=Actions.getPageUrls&idSite=2&period=day&date=yesterday&format=json&expanded=1&token_auth=TOKEN

**Comment by cv** [comment]
Token do Piwik deve ser criado pela #166 antes de mover este cartão para produção.

**Comment by erickpintor** [comment]
Será que não vale a pena considerar um período de tempo maior que o ```yesterday```?
Inicialmente pensei em considerar de 3 ou talvez 5 dias. Faz sentido?

**Comment by jeankirchner** [comment]
@erickpintor colocamos com essa config:
period: month
date: yesterday

ou seja, a partir de ontem, um mês para trás.

Isso agora é configurável, então podemos experimentar melhor quando estiver
em produção.

**Comment by jeankirchner** [comment]
Por enquanto essa página estará acessível pela url "/maisAcessados".
Basicamente não há dados da estrutura atual do site no Piwik para serem
mostrados na página principal, então a página principal continua com a
mesma estratégia, de mostrar os destaques que estão configurados.

**Comment by cv** [comment]
Nos logs:

```
17:59:31.543 09851b7f-1d89-47f2-b3b3-0fa47ba8b30c DEBUG [http-nio-8080-exec-9] b.g.servicos.piwik.PiwikClient - Fazendo requisição ao Piwik: https://estatisticas.presidencia.gov.br?module=API&format=json&idSite=2&token_auth=<TOKEN>&method=Actions.getPageUrls&period=month&date=yesterday
17:59:37.141 09851b7f-1d89-47f2-b3b3-0fa47ba8b30c DEBUG [http-nio-8080-exec-9] b.g.servicos.piwik.PiwikClient - Resposta do Piwik: 200
17:59:37.413 09851b7f-1d89-47f2-b3b3-0fa47ba8b30c INFO  [http-nio-8080-exec-9] b.g.s.frontend.LoggingFilter - 200 OK, in 5872ms
```

Performance inaceitável para a home - ***5.8s*** :(

**Comment by jeankirchner** [comment]
@cv, @erickpintor, @sahrosa - Eu adicionei duas classes para suporter itens com layout em grid automáticamente, sem depender de números fixos. Inspirado nisso aqui: http://neat.bourbon.io/examples/

Em geral, eu acho que tem algumas coisas em termos de código e estruturação do html do portal que podemos ver.

O commit: 1bb5cdb

**Comment by erickpintor** [comment]
Achei muito legal @jeankirchner.

**Comment by jeankirchner** [comment]
Com cache:
19:37:08.966 3e5395b5-7fcf-4f94-85ef-94442334354b DEBUG [http-nio-8080-exec-5] b.g.s.frontend.IndexController - Início - Obter urls Piwik
19:37:08.967 3e5395b5-7fcf-4f94-85ef-94442334354b DEBUG [http-nio-8080-exec-5] b.g.s.frontend.IndexController - Fim - Obter urls Piwik

**1ms** depois do cache.

O cache mais simples encontrado com expiração foi o do guava. Os providos pelo spring não tem nenhuma funcionalidade além de guardar em um mapa, ou teríamos que implementar um próprio.

**Comment by sahrosa** [comment]
Adicionando meus pontos à discussão! Ontem estávamos conversando, @jeankirchner e eu, sobre o tempo de atualização dos destaques, que hoje está em torno de 30 dias, certo? O ponto é que 30 dias é muito tempo pra atualizar sobre serviços sazonais. 

Por exemplo, começa a declaração do imposto de renda e as pessoas procuram muito por isso. A declaração começa e termina em aproximadamente 2 meses, então só iremos começar a mostrar os serviços sobre isso com 1 mês do começo, e 1 mês pro fim do interesse. 

Que tal se formos pra uma linha de uma semana?

**Comment by jeankirchner** [comment]
Concordo com isso, só temos que pensar um pouco em relação à quantidade de
acessos que podemos ter (supostamente uma boa porção da população com
acesso à internet), e possíveis "bots" que podem ser feitos para
influenciar as estatísticas.

Lembrando que hoje a página de mais acessados é ordenada pela quantidade de
visitantes únicos, e não visitas totais. Isso também pode ser alterado
facilmente.
