### ISSUE TITLE
Destaques de mais utilizados (sazonal) na página inicial

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/portal-de-servicos#153]
Há uma implementação de mais acessados (/maisAcessados).

Estávamos esperando uma semana após irmos para produção para termos dados o suficiente no Piwik, para os destaques serem baseados nos serviços mais acessados.

- [x] Testes iniciais, usando dados dos dias que temos
- [x] Testar funcionalidade após primeira semana de produção
- [x] Se não tiver acesso ao Piwik, ou não conseguir obter urls do Piwik, utilizar destaques
- [x] Verificar tratamento de erros

**Comment by cv** [comment]
Adicionei uma nova flag, `FLAGS_DESTAQUES_AUTOMATICOS`, para ligar/desligar o comportamento de buscar dados no Piwik. Como ainda não estamos 100% certos da configuração em todos os ambientes, mantive desligada por default.
