### ISSUE TITLE
Aprimorar texto das Perguntas Frequentes

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/portal-de-servicos#158]
Baseado em dados coletados em produção (Piwik, Feedback), podemos discutir melhor sobre FAQ, ou alguma estratégia para resolver dúvidas dos cidadãos.

**Comment by jeankirchner** [comment]
Acredito que vale à pena coletar dados por algumas semanas antes de um FAQ. Na minha visão focar em conteúdo dos serviços por enquanto vai ajudar mais os cidadãos do que um possível FAQ.

FAQs muitas vezes são utilizados para tratar um sintoma do problema maior, que é os cidadãos não conseguirem encontrar o que estavam procurando.

Que acham @sahrosa, @mformiga, @almeidafab?

**Comment by almeidafab** [comment]
concordo @jeankirchner, acredito que devemos esperar um pouco mais.

**Comment by sahrosa** [comment]
Apoiado! Podemos agendar um review sobre isso daqui a umas duas semanas :)

**Comment by mformiga** [comment]
Sim, apoiado.

**Comment by almeidafab** [comment]
implementado
