### ISSUE TITLE
Colapso no menu de navegação

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/portal-de-servicos#162]
Estamos ajustando o menu, e precisamos que o comportamento da flecha mude quando o menu está fechado no main.js. Não conseguimos fazer isso e precisamos de uma mão, @cv, @erickpintor e @jeankirchner!

**Comment by cv** [comment]
Prontinho! :)

O comportamento do menu em dispositivos móveis (<= 768px) ainda não está definido, no entanto. Vamos criar outro cartão para isso.

**Comment by sahrosa** [comment]
Eba! Valeu @cv!

**Comment by cv** [comment]
Numerei muitos dos commits nas últimas 9 horas (da ca06965 a 3d2db39) que eram para o #164 nesse cartão. Peço desculpas pela bagunça! :disappointed:
