### ISSUE TITLE
Revisar documentação p/ R0

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#164]

**Comment by cv** [comment]
Finalizando este cartão por enquanto. Outras adições aos documentos serão parte dos respectivos cartões.

**Comment by jeankirchner** [comment]
Vou fazer uma revisão geral

**Comment by jeankirchner** [comment]
Revisão feita, a documentação já está bem legal. Também garanti que todos os links estão funcionando.

A maior pendência que eu verifiquei foi em relação à nossa ["definição de serviço"](http://servicosgovbr.github.io/guia-de-servicos/servicos/o-que-e-um-servico.html), considerando a diferenciação entre os serviços que são "Direitos" ou "Deveres".
