### ISSUE TITLE
Criar Token e Site ID Piwik

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#166]
Atualmente, estamos utilizando o token "emprestado" do @mformiga, e um Site ID fixo. O ideal seria ter um token específico para a aplicação, para que administradores do Piwik possam lidar com a segurança do acesso efetivamente, e Site IDs separados para desenvolvimento, teste e homologação e produção.

Não faremos nenhum acesso transacional na API do Piwik, mas é importante ter Site IDs diferentes (para não misturar dados de produção com testes) e tokens diferentes (para controle de acesso dos administradores do Piwik)

**Comment by jeankirchner** [comment]
@mformiga, @almeidafab vocês estavam olhando isso? Só para saber se já tem alguém que iria olhar sobre esse assunto.

**Comment by mformiga** [comment]
Tentamos abrir a solicitação junto ao Serpro mas era necessário ter o ambiente criado. Vamos verificar novamente se dá para adiantar.

**Comment by cv** [comment]
Site ID criado: `52`.

**Comment by cv** [comment]
@mformiga @almeidafab ainda falta o token (32 caracteres), que usamos para acessar a API do Piwik. Sabe se já foi criado também?

**Comment by almeidafab** [comment]
@cv vou verificar com o SERPRO

**Comment by mformiga** [comment]
Serpro diz: O token está dentro de cada conta de usuário, na opção "API" que se encontra no topo da
página do Estatística. Cada conta possui um token.

**Comment by mformiga** [comment]
Segundo serpro vocês podem acessar o pwiki com a conta de vocês que já foi criada:
login: cpf
senha: cpf

**Comment by cv** [comment]
Muito obrigado, @mformiga! :)

Existe uma conta para o próprio Guia? Afinal, não vamos ser nós buscando as listas de mais acessados e outras métricas, mas sim a aplicação em si.

**Comment by mformiga** [comment]
O Serpro ficou de verificar isso agora.

2015-05-20 15:39 GMT-03:00 Carlos Villela <notifications@github.com>:

**Comment by mformiga** [comment]
Não podem criar conta para o próprio guia. Só podem criar associada a um cpf.

**Comment by cv** [comment]
Faz sentido que seja o token associado a alguém do MPOG, então - qual a gente deveria usar? O seu mesmo, @mformiga?

**Comment by mformiga** [comment]
Pode ser.

2015-05-20 17:14 GMT-03:00 Carlos Villela <notifications@github.com>:
