### ISSUE TITLE
Ícones por Área de Interesse

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#167]
Associação entre ícones e linhas da vida pode não ser ideal - @mformiga comentou que talvez seja melhor utilizar áreas de interesse (VCGE) para isso.

**Comment by jeankirchner** [comment]
Acredito que a base desse problema já tratamos, com os ícones do font awesome e à associação de linhas da vida com serviços que temos no (mapemanto de linhas da vida)[https://github.com/servicosgovbr/guia-de-servicos/blob/master/src/main/resources/linhas-da-vida.csv].

**Comment by mformiga** [comment]
Todo serviço obrigatoriamente está relacionado a uma área de interesse do
vcge mas não necessariamente à uma linha da vida já que não há, pelo menos
até então, pretensão de esgotar a linha da vida para cobrir todos os
serviços.

**Comment by cv** [comment]
Não há iconografia para o VCGE, e entendemos que o esforço não será feito como parte desse projeto. Caso um conjunto de ícones seja desenhado para as categorias do VCGE, no entanto, fica fácil adicionar ao Portal e Editor.
