### ISSUE TITLE
Articular inclusão da descrição do órgão no SIORG

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/portal-de-servicos#169]
Descrição para o cidadão, diferente da descrição legal de competência

**Comment by caduvieira** [comment]
A API do siorg está aqui siorg.planejamento.gov.br

**Comment by cv** [comment]
Com o editor de páginas de órgãos  - https://github.com/servicosgovbr/editor-de-servicos/issues/284, essa funcionalidade não se faz mais necessária.
