### ISSUE TITLE
Piwik em ambiente de desenvolvimento

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/portal-de-servicos#171]
- [x] Piwik continua não sendo usado em desenvolvimento local (somente Vagrant)
- [x] `vagrant up` sobe uma instância do Piwik local
- [x] Configuração atualizada
- [x] Documentação atualizada
- [x] Métrica utilizada no Guia é escrita e lida corretamente

**Comment by erickpintor** [comment]
Uma máquina virtual contento uma instância do Piwik na mesma versão utilizada em produção pelo governo foi criada em nosso ```Vagrantfile```. Segue o link para a documentação atualizada:

http://servicosgovbr.github.io/guia-de-servicos/desenvolvimento/deploy-vagrant.html

As outras maquinas virtuais, ```app1``` e ```app2```, foram modificadas para enviarem dados de monitoring para esta instância local. Será necessário criá-las novamente com os seguintes comandos:

```bash
vagrant destroy -f app1 app2
vagrant up
```

Uma vez que todas as maquinas estejam ligadas, você pode acessar o Piwik local usando o endereço ```http://localhost:8084/```. Usuário e senha são ```admin```.

**Comment by almeidafab** [comment]
@cv o script para o ambiente de desenvolvimento ficou pronto, segue mensagem do SERPRO:

"o cadastro para o ambiente de desenvolvimento foi concluído:

Certifique-se de que este código estará em todas as páginas do seu website antes da tag
</body>.


<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(["trackPageView"]);
  _paq.push(["enableLinkTracking"]);

  (function() {
    var u=(("https:" == document.location.protocol) ? "https" :
"http") + "://estatisticas.presidencia.gov.br/";
    _paq.push(["setTrackerUrl", u+"piwik.php"]);
    _paq.push(["setSiteId", "52"]);
    var d=document, g=d.createElement("script"),
s=d.getElementsByTagName("script")[0]; g.type="text/javascript";
    g.defer=true; g.async=true; g.src=u+"piwik.js"; s.parentNode.insertBefore(g,s);
  })();
</script>
"

**Comment by cv** [comment]
Acho que esse comentário é para a #166, @almeidafab -- atualizei lá.
