### ISSUE TITLE
Persistir feedback

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#172]
Persistir feedback entre restarts da aplicação e/ou re-provisionamento das máquinas.

- [x] Reiniciar a aplicação em modo _production_ não apaga os feedbacks
- [x] É possível baixar todos os feedbacks (em JSON, CSV ou XML) para backup
- [x] É possível reimportar um backup (JSON, CSV ou XML) dos feedbacks em outra máquina
- [x] Incluir scripts para uso no rpm, no mesmo caminho onde está o script de execução do guia de serviços (/bin/guia-de-servicos)

**Comment by jeankirchner** [comment]
O que vocês acham de termos índices diferentes:
- Tudo que for informação estática, que será indexado, em um índice (que sempre da para remover, e re-indexar)
- Tudo que tiver que ser persistente, em outro índice?
