### ISSUE TITLE
PDF da carta de serviços

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#175]
- [ ] Gerar PDF com uma carta de serviços básica, por órgão
- [ ] Adicionar índice
- [ ] Adicionar capa
- [ ] Adicionar introdução
- [ ] Adicionar capítulo "Sobre o Órgão"

**Comment by oliviagj** [comment]
mover para Editor

**Comment by erickpintor** [comment]
@oliviagj @cv Acho que o esforço relacionado a esta tarefa ainda reside no próprio guia, não?

**Comment by cv** [comment]
Sim, @erickpintor - rolou uma conversa em BSB sobre onde esta carta deveria ser gerada / mantida. Não estou nem tão certo de que isso é um trabalho para o Guia, no entanto. Pode ser que tenhamos outro repositório / API para isso.

**Comment by mformiga** [comment]
Esta conversa tem que estar bem alinhada com a SEGEP. Pelo menos por enquanto, tem baixa prioriodade.

**Comment by cv** [comment]
Duplicata da #451
