### ISSUE TITLE
Roteiro e estrutura do teste de usabilidade

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/portal-de-servicos#179]
Para o dia 23/04 preciso preparar algumas coisas para realizar o teste de usabilidade e acessibilidade.

- [x] Sala
- [x] Voucher taxi para usuário cego (teremos?)
- [x] Definir roteiro da entrevista
- [x] Definir tarefas a serem realizadas

**Comment by cv** [comment]
http://servicosgovbr.github.io/guia-de-servicos/design/roteiro-teste-de-usabilidade.html

**Comment by eversonaguiar1** [comment]
Pessoal, compartilho abaixo observação da Fernanda que será complementada:


"Há problemas nos icones e na palete, como reporto? Ou serao feitas alterações? "

**Comment by sahrosa** [comment]
Olá @eversonaguiar1, nós ajustamos os problemas de acessibilidade que a Fernanda sugeriu. No entanto sobre os outros pontos;
* As cores que não estavam no padrão foram ajustadas e agora estão de acordo com o Manual de Identidade da SECOM. Apresentamos na reunião da semana passada para a Fabiana e ela e Marcia e está ok.
* Ícones também foram apresentados para Fabiana e combinamos que estariam ok para o uso no Guia de Serviços.

Qualquer dúvida é só avisar!

**Comment by cv** [comment]
@eversonaguiar1, o que falta para mover este cartão?

**Comment by eversonaguiar1** [comment]
estou aguardando a manifestação da coordenação de padrões. falei hoje com o coordenador substituto que já colocou a demanda no radar.
