### ISSUE TITLE
Política de backup do ElasticSearch

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#186]

**Comment by plentz** [comment]
Melhor deixar uma rotina para re-importar os dados pronta do que fazer backup da base(só não é verdade caso a base de dados seja realmente *muito* grande). Se der algum problema no ES, provavelmente tu vai querer re-importar tudo(e até fazer isso frequentemente), já que o elastic search não é [exatamente um exemplo de repositório confiável](https://aphyr.com/posts/323-call-me-maybe-elasticsearch-1-5-0).

**Comment by cv** [comment]
Fechando este cartão - vamos reindexar o ElasticSearch sempre que necessário.
