### ISSUE TITLE
Revisar site dentro das versões do Internet Explorer

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/portal-de-servicos#200]
Precisamos revisar o site no navegador Internet Explorer para ajustar bugs de navegação. O resultado dessa história será novas histórias com bugs encontrados.

**Comment by jeankirchner** [comment]
|Browser + Versao | Uso %|
|:----------------|-----:|
|Chrome (all)| 62.76%|
|Firefox 5+| 9.27%|
|IE 11.0| 8.99%|
|Android 0| 5.52%|
|IE 8.0| 2.53%|
|iPhone 0| 2.16%|
|IE 9.0| 1.3%|
|Safari iPad| 1.26%|
|IE 10.0| 1.24%|
|Opera 15+| 0.64%|
|IEMobile 11.0| 0.63%|
|Opera 0| 0.56%|
|Safari 8.0| 0.47%|
|Other| 0.4%|
|Nokia 0| 0.35%|
|UC Browser 10.2| 0.29%|
|Safari 7.0| 0.2%|
|IEMobile 10.0| 0.16%|
|360 Safe Browser 0| 0.15%|
|Safari 7.1| 0.13%|
|UC Browser 10.0| 0.11%|
|Safari 5.1| 0.09%|
|IEMobile 9.0| 0.08%|
|Phantom 2.0| 0.06%|
|Safari 6.1| 0.05%|
|Chromium (all)| 0.05%|
|Maxthon 4.4| 0.05%|
|Opera 12.1| 0.04%|
|Safari 6.2| 0.04%|
|Firefox 3.6| 0.03%|
|iPod Touch 0| 0.03%|
|Firefox 3.0| 0.03%|
|Safari 5.0| 0.03%|
|IE 7.0| 0.03%|
|IEMobile 0| 0.03%|
|Safari 6.0| 0.02%|
|UC Browser 9.9| 0.02%|
|IE 6.0| 0.02%|
|IE 4.0| 0.02%|
|BlackBerry 0| 0.02%|
|UC Browser 9.5| 0.02%|
|Safari 4.0| 0.01%|
|UC Browser 9.4| 0.01%|
|Beamrise 29.3| 0.01%|
|UC Browser 9.8| 0.01%|
|Sony PS3 0| 0.01%|
|Maxthon 1.0| 0.01%|
|Mozilla 0| 0.01%|
|Firefox 4.0| 0.01%|
|Opera 12.0| 0.01%|
|Opera 12.10| 0.01%|
|Unknown 0| 0.01%|
|Googlebot 0| 0%|
|Firefox 0| 0%|
|Beamrise 27.3| 0%|
|Tencent Traveler 4.0| 0%|

**Comment by erickpintor** [comment]
Os dados do Piwik do Guia de Serviços atual comprovam a necessidade de testar o site na versão 8 do Internet Explorer:

*Relatório de versões de browser ordenados por visitas desde Jan 2015*

Rótulo | Visitas
-------|--------
Chrome 40.0 | 1791575
Chrome 41.0 | 1276562
Chrome 39.0 | 1149349
Chrome 42.0 | 569059
Internet Explorer 8.0 | 286609
Firefox 35.0 | 251948
Internet Explorer 9.0 | 196990
Firefox 36.0 | 163939
Internet Explorer 10.0 | 158268
Desconhecido | 148379
Firefox 37.0 | 114260
Firefox 34.0 | 113849
Safari 4.0 | 94653
Safari 8.0 | 92399
Chrome 38.0 | 79221
Chrome 36.0 | 57779
Chrome 37.0 | 53313
Chrome 35.0 | 42193
Chrome 33.0 | 38181
Safari 6.0 | 37747
Safari 7.0 | 33013
Chrome 34.0 | 29921
Firefox 31.0 | 29406
Firefox 33.0 | 23088
Chrome 31.0 | 21019

**Comment by erickpintor** [comment]
As issues #239, #238 e #237 foram criadas para atacar os principais problemas encontrados até agora.

**Comment by erickpintor** [comment]
Issues #244 e #246 também foram criadas como parte desta análise.

**Comment by erickpintor** [comment]
Acredito que está seja apenas uma análise inicial, dado o estado da aplicação no IE8.
Novas tarefas serão criadas para refinar o trabalho conforme os bugs encontrados forem sendo resolvidos.
