### ISSUE TITLE
Menu hamburguer para linhas da vida

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/portal-de-servicos#216]
Similar ao Portal Brasil:

![screen shot 2015-04-28 at 9 56 09 am](https://cloud.githubusercontent.com/assets/5445/7369965/da5771e2-ed8c-11e4-99b6-6ed1c035bdb6.png)

**Comment by sahrosa** [comment]
Não podemos ter dois burguer icon no mesmo site. Seria o equivalente a ter dois menus laterais, um do lado do outro. Vou pegar essa issue e pensar em um formato pra gente resolver o problema de mostrar todos os serviços.

**Comment by cv** [comment]
A solução ideal seria poder injetar itens no menu da barra de serviços (assim fica tudo no mesmo hamburguer), mas nos pareceu muito complexa pra r0.
