### ISSUE TITLE
Buscar por conteúdo / órgão

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/portal-de-servicos#221]
Hoje, a busca traz apenas serviços.

- [x] Buscar por "mec" deveria trazer a página do [Ministério da Educação](http://ec2-54-94-244-36.sa-east-1.compute.amazonaws.com/orgao/ministerio-da-educacao-mec) nos primeiros resultados 
- [ ] Buscar por "acessibilidade" deveria trazer a [página de acessibilidade](http://ec2-54-94-244-36.sa-east-1.compute.amazonaws.com/conteudo/acessibilidade) do próprio Guia

**Comment by jeankirchner** [comment]
Só o título deste card, não está tão claro, se puderem complementar iria ajudar :)

**Comment by almeidafab** [comment]
@oliviagj a busca por "acessibilidade" ainda não está funcionando.

**Comment by oliviagj** [comment]
@almeidafab você criou um novo cartão para isso?

**Comment by cv** [comment]
@oliviagj #287 :+1:
