### ISSUE TITLE
Barra Brasil não funciona sem JavaScript

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#225]
Ao desabilitar o uso de javascript no navegador, a barra dinâmica não é carregada corretamente, e o rodapé não é carregado corretamente.

**Comment by erickpintor** [comment]
@cv Existe mais um place holder para a barra brasil que aparece quando ela não é carregada:

![image](https://cloud.githubusercontent.com/assets/813042/7375324/1ef54984-edae-11e4-96d4-eef585636220.png)

Eu e a @sahrosa já demos uma melhorada no css dele ontem. Tem mais alguma coisa que deveria aparecer quando o JS não carrega?

**Comment by cv** [comment]
Por enquanto não, criei esse cartão aqui só para acompanharmos.

**Comment by caduvieira** [comment]
Vou utilizar esse CSS e modificar o manual da barra para ficar mais agradável o place holder. Se tiverem mais sugestões podem falar.
