### ISSUE TITLE
Selecionar destaques manuais

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#228]
- [ ] Selecionar 15 serviços que merecem destaque na página principal

**Comment by cv** [comment]
Alguma novidade, @eversonaguiar1?

**Comment by almeidafab** [comment]
@cv o everson ficou de atestado essa semana e talvez semana que vem tb, mas conseguimos finalizar a lista dos 15 serviços para destaque: (estão na ordem dos mais acessados)

Consulta Situação do Requerimento de Benefício Previdenciário
 Fies — Programa de Financiamento Estudantil
 Restituição e Situação da Declaração do Imposto de Renda Pessoa Física – IRPF
 Vagas de Emprego – SINE e Portal Mais Emprego
 Cadastro Único para Programas Sociais do Governo Federal
 Calculadora do Cidadão
 Comprovante de Inscrição e de Situação Cadastral no CNPJ 
 Emissão de Certidão Previdenciária
 Seguro-Desemprego
 Multas de Trânsito - Departamento de Polícia Rodoviária Federal
 Simulação da contagem de tempo de contribuição previdenciária
 Inscrição junto à Previdência Social
 Aqui tem Farmácia Popular
 Emissão da Declaração de Aptidão da Agricultura Familiar – DAP
 Extrato de Benefícios Previdenciários para Declaração de Imposto de Renda
