### ISSUE TITLE
Ajustar o alinhamento dos elementos da página em smartphones

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/portal-de-servicos#230]
Em smartphones os conteúdos estão com margens diferentes, vide imagem anexo. No cenário ideal todos os itens da página teriam a mesma margem (20px).

![alinhamento](https://cloud.githubusercontent.com/assets/2932644/7379532/ecd757d0-edcb-11e4-92fb-e2736eeaa634.jpg)

**Comment by jeankirchner** [comment]
@sahrosa as margens no desktop devem mudar, ou assumir algum padrão também?

**Comment by jeankirchner** [comment]
@sahrosa - tentei tomar o maior cuidado possível para as alterações, da uma olhada rápida se você encontra algum problema...

**Comment by sahrosa** [comment]
Oi @jeankirchner! Ficou muito bom! Só percebi que nas páginas de serviços a margem está maior que no restante:

![image](https://cloud.githubusercontent.com/assets/2932644/7482312/e7839a38-f34c-11e4-9392-cd5d6a2d3434.png)
