### ISSUE TITLE
"Ocorreu um erro" -> erros mais específicos para o usuário quando possível

### ISSUE THREAD

**Issue by kchnr** [servicosgovbr/portal-de-servicos#255]
Alguns "erros" são erros mesmo, e outros podem ser falhas esperadas por alguma ação indevida/não suportada do usuário. Nos casos que conseguimos detectar que não é um erro, mensagens mais amigáveis devem ser apresentadas para o usuário.

Ex: colocar o endereço manualmente de uma página que não existe, ou que foi um erro de digitação por parte do usuário:

![screen shot 2015-05-07 at 17 53 42](https://cloud.githubusercontent.com/assets/576918/7525699/1d9ddce6-f4e2-11e4-99ae-b0b178cd1363.png)

**Comment by jeankirchner** [comment]
@sahrosa: Você teria mais algum caso relevante, ou o que deveria aparecer para o usuário nesses casos?

**Comment by sahrosa** [comment]
Perfeito @jeankirchner! Vamos parear pra pensar num erro mais específico! Vou pensando em algumas formas e te mostro assim que tiver algo. 

Dúvida: Essa mensagem de identificador serve para alguém além de nós?

**Comment by jeankirchner** [comment]
@sahrosa Isso ai, pense nesses tickets como protocolos de atendimento :)

**Comment by cv** [comment]
@sahrosa os _tickets_ servem para correlacionar problemas ocorridos com os logs gerados. Por segurança, não é uma boa detalhar o que aconteceu de errado para o usuário, mas isso não impede que todo tipo de informação vá parar no log daquela transação.

Mais aqui: http://servicosgovbr.github.io/guia-de-servicos/desenvolvimento/seguranca.html

**Comment by sahrosa** [comment]
Podemos usar algo próximo ao  www.brasil.gov.br, lá a [mensagem de erro é assim](http://www.brasil.gov.br/esporte/2015/05/equipe-brasileira-de-tenis-trabalha-por-mais-vagas-olimpicas-no-rio-20165): 

![image](https://cloud.githubusercontent.com/assets/2932644/7544614/014d0648-f5a5-11e4-84b4-247133f9e6cc.png)

**Comment by sahrosa** [comment]
O que acha @jeankirchner? Se achar ok, vou dar o push!

![screen shot 2015-05-13 at 3 38 08 pm](https://cloud.githubusercontent.com/assets/2932644/7618092/229d6aec-f986-11e4-93e6-9575d15db69a.png)

**Comment by cv** [comment]
:+1:
