### ISSUE TITLE
Adicionar texto sobre ouvidorias à página de órgãos

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#257]
Adicionar o seguinte texto às páginas dos órgãos:

"Para fazer uma reclamação, denúncia, sugestão ou elogio em relação a algum serviço deste órgão, contacte sua Ouvidoria [link para a página de dados da ouvidoria do órgão no e-ouv, enquanto não temos API segundo cgu].

Para pedido de informação pública deste órgão, consulte o Sistema Eletrônico do Serviço de Informações ao Cidadão (e-SIC) [link para o e-SIC]."

@mformiga e @almeidafab - vocês têm a lista dos links das ouvidorias à mão?

**Comment by almeidafab** [comment]
Cada órgão será encontrado nessa página (a maioria vai estar em administração direta e autarquia): http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias.
Ex.: o link da ouvidoria do ministério da saúde: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-da-saude-ms

Link do e-SIC: http://www.acessoainformacao.gov.br/sistema/site/index.html

**Comment by mformiga** [comment]
Não podemos esquecer de que há outras informações de contato além de
ouvidoria e sic. Devemos mantê-las.

2015-05-08 17:05 GMT-03:00 Fabrício Almeida <notifications@github.com>:

**Comment by cv** [comment]
Ok, mas quando a informação de contato é apenas a ouvidoria, podemos retirar aquele trecho e manter só o link para o e-ouv, certo?

**Comment by mformiga** [comment]
Certo . Assim ficamos despreocupados em relação à atualização e não temos
problemas como tivemos ultimamente.

2015-05-08 17:19 GMT-03:00 Carlos Villela <notifications@github.com>:

**Comment by mformiga** [comment]
Enquanto não há api podemos ficar monitorando os links por enquanto para
verificar se está retornando o código http correto.

2015-05-08 17:22 GMT-03:00 Mauricio Formiga <formiga.mauricio@gmail.com>:

**Comment by cv** [comment]
Alguns órgãos (secretarias, em particular) não possuem ouvidorias, mas são subordinadas a outros órgãos que têm. Por exemplo, a SNJ não tem ouvidoria, mas o MJ sim.

**Comment by almeidafab** [comment]
Nesses casos @cv a ouvidoria deve apontar para o órgão subordinado. Ex.: a SNJ deve apontar para o MJ. Permanece o mesmo texto: "Para fazer uma reclamação, denúncia, sugestão ou elogio em relação a algum serviço deste órgão, visite o sítio de sua ouvidoria."

**Comment by cv** [comment]
OK, vou adicionar os links para as ouvidorias que faltam no mapeamento, então.

**Comment by almeidafab** [comment]
@cv , o @mformiga tb concorda em retirar "municípios" da lista de orgãos. Os serviços relacionados a ele colocar no Ministério do Desenvolvimento Social e Combate a Fome
