### ISSUE TITLE
Link do "Começar" duplicado em "Canais"

### ISSUE THREAD

**Issue by mformiga** [servicosgovbr/portal-de-servicos#260]
Está confuso ter um botão começar dentro de um contexto e mais adiante ter um canal web com um texto associado a um link apontando para o mesmo lugar do botão. Se for usar o botão, sugiro colocar dentro do contexto correto: ao lado do canal, por exemplo.

**Comment by oliviagj** [comment]
Deixar o link do "começar" exclusivo deste botão. Remover a duplicação em "Canais".
