### ISSUE TITLE
Verificando links quebrados / antigos

### ISSUE THREAD

**Issue by valessiobrito** [servicosgovbr/portal-de-servicos#265]
Na versão Alpha, em http://ec2-54-94-244-36.sa-east-1.compute.amazonaws.com/servico/orientacoes-gerais-sobre-renavam  foi possível detectar que o link para página de serviço/atendimento da Receita quebrou: http://www.receita.fazenda.gov.br/atendcontrib/Atendimento/UnidAtendimento/centroAtendimento.htm

Vocês já pensaram alguma tecnologia para automatizar notificação de links quebrados?  Sugiro implementar a mesma tecnologia que o Wordpress utiliza para verificar menções de links em páginas externas:  Track/Pingback - http://en.wikipedia.org/wiki/Pingback

Em um artigo do Wikipedia, cita várias outras tecnologias possíveis:  http://en.wikipedia.org/wiki/Linkback

**Comment by cv** [comment]
Obrigado por trazer essa discussão à tona, @valessiobrito!

Criei um issue separado para discutirmos a implementação de linkbacks - #270.

Quanto a os links quebrados, temos um script (`scripts/crawler`) que faz esta verificação, e pode ser rodado esporadicamente para detectar quebras nos links internos ao site, bem como aos provenientes do conteúdo externo. Rodei agora há pouco, e ele achou 130 links externos quebrados.

Hoje o Guia de Serviços importa a maior parte do conteúdo de um XML de exportação do site atual, que não é mantido já faz algum tempo. Assim que migrarmos para o [novo formato de cartas de serviço](https://github.com/servicosgovbr/cartas-de-servico) teremos como lidar com alterações no conteúdo (links externos, etc) muito mais facilmente.

**Comment by valessiobrito** [comment]
@cv estava procurando no histórico da Issue o código gerado relacionado a essa atividade; mas acaba que "se perdeu" entre muitos commits.   Uma boa prática/sugestão é mencionar no commit a Issue qual esta sendo tratado aquele commit;  Assim você agrega informação no histórico das Issues relacionando os commits.      Mas em linhas gerais, obrigado por implementarem tal tecnologia/prática no guia s.
