### ISSUE TITLE
Hierarquizar lista de órgãos segundo SIORG

### ISSUE THREAD

**Issue by mformiga** [servicosgovbr/portal-de-servicos#274]

**Comment by cv** [comment]
A hierarquia do Siorg é **enorme** (75 mil elementos, e crescendo). Mostrá-la ao cidadão pode gerar confusão demais para pouco ganho.

Vamos focar na busca, e caso uma apresentação em árvore faça sentido de acordo com a hierarquia no futuro, abrimos outro cartão.
