### ISSUE TITLE
Padronização de entrelinha

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/portal-de-servicos#298]
Conforme sugerido no feedback: entrelinha já estava em 140% em alguns casos, e agora está padronizado.

**Comment by sahrosa** [comment]
O commit foi em outra issue, mas está aqui: https://github.com/servicosgovbr/guia-de-servicos/commit/f82d420f01a42cd9e4b42579f9b07c23bfe9a7a6

**Comment by cv** [comment]
Copiei a mensagem de commit e errei junto :skull: 5e1802e36626767857b078077810b8392aa67345
