### ISSUE TITLE
Pedir feedback sobre a página do serviço

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/portal-de-servicos#303]
Agora que temos a página de cada serviço aqui no Github, podemos solicitar o feedback por serviço. Dois exemplos de como poderia ser o pedido:

Australia
![image](https://cloud.githubusercontent.com/assets/2932644/7704079/8fb95c0e-fe12-11e4-99fc-0b8a0140c09c.png)

Noruega
![image](https://cloud.githubusercontent.com/assets/2932644/7704082/941f4506-fe12-11e4-925f-db11d45c9879.png)

**Comment by jeankirchner** [comment]
@sahrosa o que você acha de termos, além do link de feedback onde já temos, o próprio formulário de feedback já expandido ao fim da página? Após o "voltar ao topo". Ou até algum indicador, e ao clicar expande o formulário?

Acho que é muito cedo para termos formulários de feedback mais específico ou direcionado, considerando que muitas vezes falta o básico de informação?

**Comment by sahrosa** [comment]
Sim!! Acho que vai ser super útil! Podemos fazer algo mais direto, que tal:
* Essa informação foi útil pra você? [ ] Sim [ ] Não
* Quais informações você sentiu falta neste serviço? [campo aberto]

**Comment by sahrosa** [comment]
Olá pessoal, segue abaixo duas versões do pedido do feedback do serviço. Por favor não se prendam no estilo visual (não está finalizado), mas vocês acham que faz mais sentido qual das possibilidades?

1 - Apenas sim/não
![image](https://cloud.githubusercontent.com/assets/2932644/8190625/2534e130-143a-11e5-9d11-691920bbbde9.png)

2 - Sim/não + opinião sobre o que não encontrou
![image](https://cloud.githubusercontent.com/assets/2932644/8190622/1fd5d212-143a-11e5-842e-edfd2ecda552.png)

**Comment by caduvieira** [comment]
Número 2

Em ter, 16 de jun de 2015 15:32, Samantha Rosa <notifications@github.com>
escreveu:

**Comment by almeidafab** [comment]
@sahrosa @mformiga gostei dessa ideia do feedback na página de serviço. Nossa sugestão seria quando o usuário clicasse em "Não" abrisse um campo aberto para ele escrever o que ficou faltando na página do serviço. Além de recebermos o feedback por email, a ouvidoria responsável por aquele serviço também receberia esse email. O que acha?

**Comment by sahrosa** [comment]
Ótima ideia @almeidafab @mformiga! Vamos implementar mostrando a caixa uma vez que o usuário clica na opção "não"! :+1:

**Comment by sahrosa** [comment]
@almeidafab criamos o #413 para incluir essa sugestão que vocês deram acima.
