### ISSUE TITLE
Ajustar navegação por tab

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/portal-de-servicos#304]
Comentário do @almeidafab no #143:

> O alpha está correto mesmo, falha minha, apenas uma observação na ordem: depois que o foco sair da barra brasil, ele deve ir primeiro para bloco de conteúdo (barra de busca e destaques) e não para o menu da esquerda. O menu da esquerda vem depois do conteúdo.

**Comment by sahrosa** [comment]
Oi @almeidafab! 

Estamos analisando aqui, e percebemos que a única diferença entre a nossa ordem de navegação e a ordem do Portal Brasil, é que estamos começando com a navegação de acessibilidade [1,2,3,4] ao invés da Barra Brasil. Vocês lembram @caduvieira @cv porque realizamos a mudança de colocar nessa ordem? 

Podemos manter como está?

**Comment by almeidafab** [comment]
@jeankirchner no firefox não consigo ver a borda, só no chrome. Antes de entrar no menu da esquerda, a navegação do tab deve percorrer a busca e os serviços em destaque primeiro.

**Comment by jeankirchner** [comment]
@almeidafab Boa! Vamos corrigir no Firefox e outros browsers, obrigado por essa verificação. Colocamos essa situação no cartão #324.

E sobre a ordem, só para fins de clarificação, e garantir que vamos fazer a coisa com um entendimento compartilhado. Nós verificamos no portal brasil, e de fato passa pela busca antes, mas porque a busca faz parte do cabeçalho. Logo após a busca, o foco do portal brasil vai para o menu à esquerda.

**Comment by almeidafab** [comment]
@jeankirchner conversei com o pessoal de acessibilidade pq tinha dúvidas sobre esse sequência. O e-mag traz outra sequencia, mas a forma como está hoje está correta tb. Vou homologar esse cartão já que você criou o #324
