### ISSUE TITLE
Texto final da página dos órgãos

### ISSUE THREAD

**Issue by almeidafab** [servicosgovbr/portal-de-servicos#315]
texto enviado por e-mail hoje.

**Comment by cv** [comment]
Aguardar o final da #311 antes de começar este cartão, para evitar conflitos!

**Comment by almeidafab** [comment]
só lembrando que o texto que está em VERDE é a versão final.

**Comment by almeidafab** [comment]
@cv ainda estão aparecendo os textos antigos, vc chegou a atualizar?
