### ISSUE TITLE
Destaque para linha da vida selecionada

### ISSUE THREAD

**Issue by almeidafab** [servicosgovbr/portal-de-servicos#316]
Devemos deixar bem marcado em qual categoria do menu esquerdo o cidadão encontra-se, para que ele não se perca durante a navegação dentro da página de serviços de uma determinada categoria, ou até mesmo dentro de um serviço específico.

**Comment by cv** [comment]
Linhas da vida foram removidas das cartas, então este cartão perde o sentido.
