### ISSUE TITLE
Reduzir qtd de serviços em destaque

### ISSUE THREAD

**Issue by almeidafab** [servicosgovbr/portal-de-servicos#317]
Reduzir a quantidade de 15 para 9 serviços em destaque

**Comment by sahrosa** [comment]
Oi @almeidafab! Que tal mudarmos pra 10 ao invés de 9, assim conseguiremos ter duas colunas com 5 itens cada? Ao invés de 3? 

Inspirado nesse modelo:
![screen shot 2015-05-20 at 4 24 01 pm](https://cloud.githubusercontent.com/assets/2932644/7734496/b7be754a-ff0c-11e4-8d9e-76e924c8a8b3.png)

**Comment by jeankirchner** [comment]
@almeidafab: Fizemos um teste em alterações locais para ver como ficaria com 2 colunas e 10 itens. Esperamos por sua confirmação. Print screen:

![screen shot 2015-05-20 at 18 37 57](https://cloud.githubusercontent.com/assets/576918/7737163/690e9566-ff1f-11e4-9829-01bf3c1c2cb0.png)

**Comment by almeidafab** [comment]
@jeankirchner repassando o feedback da ASEGE, o pessoal prefere 3 serviços por linha
"Boa tarde, Fabrício.
Nós aqui (eu, Izabel e Bruno) gostamos mais da versão com três serviços por linha..."

**Comment by jeankirchner** [comment]
@almeidafab: Aqui vai um print de como ficaria com uma breve descrição nos itens em destaque, isso não seria possível com três serviços por linha, por falta de espaço:

![screen shot 2015-05-21 at 15 30 06](https://cloud.githubusercontent.com/assets/576918/7755994/8bf69754-ffce-11e4-9e25-84729c82d236.png)

**Comment by sahrosa** [comment]
Eu gosto @jeankirchner! Acho que se subirmos o ícone pra cima, usando o azul no ícone+texto sem o background cinza, vai ficar lindão! :+1:

**Comment by cv** [comment]
Por enquanto, mantemos o layout em 3 colunas, sem prévia da descrição, de acordo com a decisão do @BrunoPalvarini e @izabelrsg.

**Comment by almeidafab** [comment]
concordo @cv

**Comment by almeidafab** [comment]
@jeankirchner tem como voltar para 2 colunas x 5 linhas?
