### ISSUE TITLE
Sugestão: O campo de busca não esta destacado o suficiente na página

### ISSUE THREAD

**Issue by Rliedke** [servicosgovbr/portal-de-servicos#349]
Na página principal a caixa de busca poderia ter outra cor.

Ou mudar a cor do subtítulo: "O que você está procurando?" para azul por exemplo, da mesma cor do botão "BUSCAR". Por ser o subtítulo da mesma cor do texto, gera uma certa dificuldade de visualizar o campo de busca.

**Comment by cv** [comment]
O @caduvieira comentou algo semelhante na #341 - tem um mockup lá, também!

**Comment by cv** [comment]
Cartão obsoleto - discussão continua na #449
