### ISSUE TITLE
 Sugestão: Logos, Brasil - Patria Educadora e Acesso a Informação, aparentam ser de muita baixa qualidade e resolução

### ISSUE THREAD

**Issue by juniorvanin** [servicosgovbr/portal-de-servicos#350]
Os logos do rodapé estão em uma qualidade muito ruim, e acessando de um dispositivo com uma tela muito boa (celulares modernos/tela retina), isso fica ainda mais visível.

**Comment by sahrosa** [comment]
@mformiga, @almeidafab, @caduvieira temos estes logos em svg?

**Comment by mformiga** [comment]
@caduvieira poderia perguntar isso para o Edson ou Fernanda ?

**Comment by cv** [comment]
@caduvieira alguma novidade?

**Comment by sahrosa** [comment]
Oi @caduvieira, sabe nos dizer se conseguiremos essas imagens?

Obrigada desde já!! :)

**Comment by almeidafab** [comment]
@sahrosa achei essa página que tem em svg a logo brasil pátria educadora (http://www.secom.gov.br/atuacao/publicidade/marca-de-governo). Fica faltando a logo acesso a informação...

**Comment by almeidafab** [comment]
@sahrosa achei a logo de acesso a informação http://www.acessoainformacao.gov.br/lai-para-sic/sic-apoio-orientacoes/guias-e-orientacoes/marca.zip
O manual está aqui http://www.acessoainformacao.gov.br/lai-para-sic/sic-apoio-orientacoes/guias-e-orientacoes/manual-do-selo-informacao_periodo-eleitoral_web.pdf

**Comment by sahrosa** [comment]
Que ótimo @almeidafab!! Vou organizar pra gente trocar as imagens! Muito obrigada!

**Comment by caduvieira** [comment]
Opa não estava vendo essa issue. Mal

**Comment by sahrosa** [comment]
Pessoal,
este cartão está fora do nosso escopo. Criei um cartão na barra brasil para isso: https://github.com/govbr/barra.govbr/issues/12
