### ISSUE TITLE
Botão "Começar" possui um nome que não corresponde com o que faz

### ISSUE THREAD

**Issue by juniorvanin** [servicosgovbr/portal-de-servicos#351]
O botão com o texto "Começar" nas páginas de serviço, ele redireciona o usuário pra uma página com mais informações ou para a página do governo responsável por aquele assunto. O nome está muito ruim, quem sabe "Saiba mais" ou "Mais informações".

**Comment by cv** [comment]
Oi Junior!

Em quais páginas você viu isso?

Pode ser que tenhamos que adicionar uma terceira ação (hoje temos "Começar" e "Agendar")

**Comment by juniorvanin** [comment]
Olá @cv,
Em quase todas as páginas de serviços que eu visitei, tinha esse botão chamado "Começar", como na página do Fies - < http://ec2-54-94-244-36.sa-east-1.compute.amazonaws.com/servico/fies-programa-de-financiamento-estudantil >. Ao meu ver seria melhor um "Clique aqui para acessar a página do FIES" ou algo mais genérico "Clique aqui para saber mais". Quando eu vejo o botão "Começar",  fico me perguntando  "tá mas começar o que?".

Sobre o botão "Agendar", em alguns momentos fica estranho: < http://ec2-54-94-244-36.sa-east-1.compute.amazonaws.com/servico/pensao-por-morte > parece que vamos agendar um óbito :). Talvez falte uma pequena descrição antes destes botões.

**Comment by sahrosa** [comment]
Oi @juniorvanin, estamos resolvendo essa questão com botões contextualizados no cartão #88. Estou fechando este cartão. Obrigada pela sugestão!
