### ISSUE TITLE
Java 8 pre instalado na imagem base

### ISSUE THREAD

**Issue by viniciusgama** [servicosgovbr/portal-de-servicos#354]
Sugestão: Rodar o 'vagrant up' para configurar um ambiente demora bastante (1h e contando). Pelo que percebi ele instala o java 8 em mais de uma VM e essa é a parte que mais demorada nesse processo. Percebi também que já existe uma imagem base do servicos.gov. Fico imaginando se não seria proveitoso colocar o java 8 instalado como parte dessa imagem, ou talvez tentar reaproveitar o arquivo baixado entre as VMs. Economizaria bastante tempo.

**Comment by cv** [comment]
Ótima ideia, @viniciusgama! :+1:

**Comment by cv** [comment]
Resolvido de outra maneira: nas novas VMs do Vagrant, estamos usando o SaltStack para instalar o OpenJDK 1.8, que fica no Vagrant Cachier (e instala bem mais rápido).

Dá uma olhada: http://github.com/servicosgovbr/vagrant-boxes

**Comment by cv** [comment]
Migramos para Docker :dancer:

**Comment by rogeralmeida** [comment]
Docker para ambiente de desenvolvimento... interessante. Fiquei curioso de saber como vao ficar as tarefas do dia-a-dia de desenvolvimento (hotdeploy, debugging, log collecting, etc...) Acho que vale a pena um blog post sobre isso (Insights?!).
Cheers...

**Comment by cv** [comment]
Acho que para um ambiente de desenvolvimento onde se reinicia a aplicação a toda hora não é lá essas coisas, @rogeralmeida - mas já usei uma diretiva VOLUME no Dockerfile para o código, e funciona bem :)

**Comment by soejima** [comment]
Grande, Roger! =)

Em terça-feira, 18 de agosto de 2015, Roger Almeida <
notifications@github.com> escreveu:

> Docker para ambiente de desenvolvimento... interessante. Fiquei curioso de
> saber como vao ficar as tarefas do dia-a-dia de desenvolvimento (hotdeploy,
> debugging, log collecting, etc...) Acho que vale a pena um blog post sobre
> isso (Insights?!).
> Cheers...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/servicosgovbr/portal-de-servicos/issues/354#issuecomment-132390049>
> .
>


-- 
Henrique Tatsuyuki Soejima
mobile: +55 (11) 981247350
http://about.me/soejima
blog: http://www.deltahumano.com.br
