### ISSUE TITLE
Alguns temas de busca retornam a resultados não relacionados

### ISSUE THREAD

**Issue by Rliedke** [servicosgovbr/portal-de-servicos#355]
Busquei por  ex: "Marisco", "Idosos", "animais" e apareceram resultados não relacionados.
![screen shot 2015-05-22 at 4 34 11 pm](https://cloud.githubusercontent.com/assets/5034279/7778336/a033043c-00a0-11e5-9fe9-5446afb26587.png)

**Comment by gustavo-freitas** [comment]
Considerando que já temos cartões para isso, esse cartão será fechado.
