### ISSUE TITLE
Sugestão: Aparecer na busca "Você quis dizer ..."

### ISSUE THREAD

**Issue by Rliedke** [servicosgovbr/portal-de-servicos#359]
Buscando por "Imformacao" retornaram alguns resultados relativos a informação e importação. 

Uma sugestão seria aparecer para o usuário algo do tipo: "Você quis dizer informação ou importação?" e isto se aplicaria também a typos com somente um resultado.

**Comment by oliviagj** [comment]
Seria lindo, @Rliedke, mas não vai rolar agora. Valeu!
