### ISSUE TITLE
Redirecionar URLs legadas fora do padrão

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#373]

**Comment by erickpintor** [comment]
O @cv implementou um redirecionamento de ```repositorioServico``` para ```servico```. Isso vai resolver boa parte das urls dos serviços legados.

Exemplo:
Url acessada: ```/repositorioServico/calculadora-do-cidadao```
Url redirecionada: ```/servico/calculadora-do-cidadao```

Foram identificadas 280 urls que fora deste padrão que foram compiladas em um relatório e enviadas ao @mformiga para notificarmos os órgãos de que estas urls iram mudar.

Eu tentei gerar um script que tenta buscar no site atual o link correto dos serviços legados afim de criar regras de redirecionamento mais específicas, porém, não há como garantir que a co-relação entre as urls do site antigo e novo estão 100% corretas.

Minha sugestão seria monitorar com atenção os casos de erro ```404``` ao colocarmos o novo site no ar e corrigir as urls com erro mais frequentes caso haja alguma.

**Comment by erickpintor** [comment]
O commit https://github.com/servicosgovbr/guia-de-servicos/commit/3975ddffc82caf2c9a9d7db08cf8dcf405a5ff9b  é da issue #370 
Linkei errado.
