### ISSUE TITLE
Página de serviço: visão do cidadão

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/portal-de-servicos#379]
Trabalhamos bastante no editor, e como o servidor verá as informações de cada serviço, mas pouco está claro para a visão do cidadão, que é o resultado final. Estou fazendo alguns protótipos de como poderá ser essa página, com tudo o que pensamos no editor.

**Comment by sahrosa** [comment]
Uma visão inicial - a mais simples possível - está abaixo. Agora vamos trabalhar em uma versão mais caprichada para mostrar informações (custo, tempo, legislação, órgão) de forma mais inteligente.

![gds -servico_v1](https://cloud.githubusercontent.com/assets/2932644/7868496/e2e40004-0552-11e5-989c-a6e08ed7223e.jpg)

**Comment by sahrosa** [comment]
Segunda versão, agora um pouco mais estruturada.

Pensei em trazer os botões de ação logo no início e também no fim. Não tenho certeza se eles estão bem como estão, mas acredito que dar a ação direto para o cidadão é uma boa forma de facilitar a ação a seguir.

O próximo teste envolve mostrar o custo e o tempo num formato mais amigável (talvez logo abaixo do título do serviço).

O que acham, no geral?

![gds -servico_v2](https://cloud.githubusercontent.com/assets/2932644/7888239/65e17706-060d-11e5-8da2-73d9b901d4ec.jpg)

**Comment by cv** [comment]
Ficou lindo, @sahrosa! Gostei da ideia e colocar as call-to-actions logo abaixo do título, mas fiquei curioso pra ver como isso ficaria num serviço "pobre", com pouco conteúdo...

**Comment by jeankirchner** [comment]
Achei muito legal.

Uma coisa que eu percebi na sessão de colaboração de conteúdos do guia e
pull requests da galera, era a falta de entendimento claro do que
exatamente eram essas ações no começo.
Acho que vale a pena apresentar para algumas pessoas sem tanto contexto,
para ver como elas interpretam essas ações. Porque dependendo o caso, só a
ação "Agendar" (por exemplo) pode não ser tão clara, mas se fosse "Agendar
atendimento" (pode ser um atendimento digital), "Agendar visita" (para
passaporte por exemplo, na polícia federal) fosse mais óbvio.

**Comment by sahrosa** [comment]
Ótimas ideias @cv e @jeankirchner! Vamos testar com pouco conteúdo e também pra ver se os nomes das ações serão claros. Para o nome das ações podem fazer alguns testes e até card sorting! Curti! Vou planejar isso e ir mostrando pra vocês!

**Comment by sahrosa** [comment]
Uma nova versão com alguns ajustes para ficar mais claro quais são as ações disponíveis e também repensando as etapas:

![gds -servico_v3](https://cloud.githubusercontent.com/assets/2932644/7891761/9f1e8b5e-0625-11e5-8ab1-2af845116440.jpg)

**Comment by almeidafab** [comment]
esse último muito bom @sahrosa!

**Comment by jeankirchner** [comment]
+1

**Comment by sahrosa** [comment]
Fiquei pensando em começar a montar essa página no ambiente de dev. Esse conteúdo que está no layout saiu todo do site do FIES. Posso atualizar o conteúdo da página do serviço para podermos começar a montar o css da página, @almeidafab @mformiga?

**Comment by almeidafab** [comment]
@sahrosa esse serviço do FIES é um pouco mais complexo por possuir muitos detalhes relacionados as etapas e documentos. Não podemos atualizar a página e ir pra produção sem o aval do órgão. Podemos até montar a página mas teríamos de mandar para o órgão aprovar. 
Analisando com o @mformiga notamos que nesse layout faltou os canais de prestação. Também achamos que deve ser colocado na parte de documentação o título Documentos Necessários.

**Comment by sahrosa** [comment]
Perfeito @almeidafab e @mformiga, como não estavamos considerando antes, acabou ficando de fora os canais. Vou ajustar isso! :)
