### ISSUE TITLE
Espaçamento na descrição dos órgãos

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#380]
![image](https://cloud.githubusercontent.com/assets/5445/7864657/de0d17a0-0539-11e5-9a23-a6e1fe0ededb.png)

**Comment by erickpintor** [comment]
Não consigo reproduzir o problema. Além do meu próprio MAC, testei no Windows 7 com Google Chrome 26.

![image](https://cloud.githubusercontent.com/assets/813042/7866370/67cc3af6-0545-11e5-98a6-152fe8e23bbd.png)

**Comment by erickpintor** [comment]
@mformiga e @almeidafab, conseguem testar na máquina de vocês e ver se o erro ocorre?
Se ocorrer, preciso saber a versão do browser que da o erro.

**Comment by almeidafab** [comment]
@erickpintor testamos aqui tb e foi difícil reporduzir. Mas no computador da Elen (Win 7 chrome 43) acontece com vários serviços, basta atualizar a página que voltar ao normal, aí se atualizar de novo o erro volta.. bizarro

**Comment by erickpintor** [comment]
@almeidafab Tentei reproduzir em um notebook com Windows 7 e Chrome 43 instalado, porém o erro não ocorreu.

Você pode depor pra Elen testar em nosso [ambiente de alpha](http://gds-alpha.herokuapp.com) pra ver se o problema ocorre lá também?

**Comment by almeidafab** [comment]
@erickpintor ela testou no alpha e bug tb apareceu, segue o print:
![erro2](https://cloud.githubusercontent.com/assets/9214263/7870192/f37aba88-055d-11e5-8be5-df20950a8462.jpg)

**Comment by erickpintor** [comment]
@almeidafab Obrigado pelo screenshot. Ainda não conseguimos reproduzir e nenhuma de nossas máquinas mas, mesmo assim, fizemos alguns ajustes no html.

Vocês poderiam testar novamente e ver se o erro persiste no [ambiente de alpha](http://gds-alpha.herokuapp.com)? Se ocorrer, você poderia salvar a pagina toda e nos enviar por email? Assim podemos avaliar se há algum html incorreto sendo gerado.

**Comment by erickpintor** [comment]
@almeidafab Tem sido bem difícil de identificar este problema sem conseguir reproduzir o erro em nossas máquinas aqui. Vou bloquear ela por enquanto e esperar o @cv ir pra Brasilia.

Assim ele ver o erro pessoalmente e fazer uma análise mais precisa da causa do problema.

**Comment by almeidafab** [comment]
tranquilo

Fabrício

2015-06-01 15:35 GMT-03:00 Erick Pintor <notifications@github.com>:

**Comment by cv** [comment]
Confirmado - no novo release este bug não acontece mais.
