### ISSUE TITLE
Sugestão: Serviços para estrangeiros em outras línguas alternativas ao Português

### ISSUE THREAD

**Issue by pamcdm** [servicosgovbr/portal-de-servicos#381]
A maioria dos estrangeiros não falam português, esta sessão pode ficar mais util e informativa se estiver disponível em espanhol ou ingles.

**Comment by pamcdm** [comment]
Seria interessante levantar dados sobre qual é a lingua mais falada pelos estrangeiros que procuram o Brasil como destino.

**Comment by sahrosa** [comment]
Muito legal a sugestão @pamcdm! Obrigada

**Comment by oliviagj** [comment]
@pamcdm, isso provavelmente voltará para o horizonte do produto no futuro, mas não será desenvolvido agora.
