### ISSUE TITLE
Atalhos de busca

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#384]
Buscar pela sigla de um órgão redireciona à sua página (ex: MEC).

Acreditamos que economizaria um tempo considerável de usuários vindos da página do MEC, e em outros fluxos de busca onde eles procuram pelo órgão, e não pelo serviço.

**Comment by sahrosa** [comment]
Estou fechando o cartão pois está fora do escopo, ok @mformiga @almeidafab @gustavo-freitas? :)
