### ISSUE TITLE
Ajustar a página para funcionar imprimindo apenas o conteúdo do miolo

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/portal-de-servicos#385]
Hoje ao mandar imprimir, aparece também o menu, cabeçalho, etc.

![image](https://cloud.githubusercontent.com/assets/2932644/7871975/6a42304a-056a-11e5-88c6-a85dfbd85fc6.png)

**Comment by cv** [comment]
O IDG não fala nada sobre print stylesheets - tá aqui uma boa oportunidade para contribuir! :)



- cv

**Comment by sahrosa** [comment]
Acabamos de receber um pedido pelo formulário de opinião: "Não está funcionando, não aparece a opção fazer a impressão , por favor, de um jeito nisso urgente..."

**Comment by cv** [comment]
Acho que isso não está relacionado, @sahrosa – o pedido de impressão era provavelmente relacionado a algum formulário de inscrição, darf, etc...

**Comment by cv** [comment]
Ficou assim:

![screen shot 2015-06-03 at 8 47 49 am](https://cloud.githubusercontent.com/assets/5445/7959183/4d4a80f2-09cd-11e5-9487-80de798858c1.png)

**Comment by sahrosa** [comment]
Melhor que a encomenda! :P

Ficou muito bom!

**Comment by almeidafab** [comment]
show de bola! acabei de fazer um teste e me surpreendi quando vi um qrcode na página (ótima ideia!). Uma dúvida: esse qrcode aponta para a pagina inicial, independentemente de qual serviço eu imprima. Seria interessante ou viável apontar para a página específica que se quer imprimir? @cv @sahrosa

**Comment by jeankirchner** [comment]
@almeidafab - o QR code agora está apontando para o serviço específico
