### ISSUE TITLE
Repensar o formato do filtro de letras no celular

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/portal-de-servicos#386]
![image](https://cloud.githubusercontent.com/assets/2932644/7872047/2450594e-056b-11e5-9bb9-adb735f1e841.png)

**Comment by cv** [comment]
Que tal?

![screen shot 2015-05-28 at 7 39 33 pm](https://cloud.githubusercontent.com/assets/5445/7872785/4df32064-0571-11e5-9797-3c5431086327.png)

**Comment by sahrosa** [comment]
Ficou ótimo!
