### ISSUE TITLE
DIRPF tem serviços duplicados

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#387]
Estes dois serviços estão competindo por buscas e têm exatamente o mesmo conteúdo, apenas com títulos diferentes:

- [extrato-do-processamento-da-dirpf-dirpf-declaracao-do-imposto-sobre-a-renda-da-pessoa-fisica-declaracoes-e-demonstrativos](http://servicos.gov.br/servico/extrato-do-processamento-da-dirpf-dirpf-declaracao-do-imposto-sobre-a-renda-da-pessoa-fisica-declaracoes-e-demonstrativos)
- [extrato-do-processamento-da-dirpf-restituicao-do-imposto-de-renda-pessoa-fisica-irpf-restituicao-e-compensacao](http://servicos.gov.br/servico/extrato-do-processamento-da-dirpf-restituicao-do-imposto-de-renda-pessoa-fisica-irpf-restituicao-e-compensacao)

O ideal seria remover um deles, para evitar confundir o usuário. Qual?

**Comment by almeidafab** [comment]
@cv eu entendo que são serviços diferentes, um é a restituição e o outro é a declaração. Concordo que pode confundir o usuário, mas eu não excluiria um deles. O título e a descrição tinham de ser melhorados mas caberia ao órgão fazer essa atualização. O que acha @mformiga?

**Comment by mformiga** [comment]
Sim, @almeidafab, imagino que tenha sido proposital pela Receita. Neste caso, seria mais prudente pedir para o órgão revisar as descrições que estão iguais.

**Comment by cv** [comment]
OK – quem fica com a tarefa de fazer o leva-e-traz com a RFB?

**Comment by cv** [comment]
@almeidafab @mformiga ping

**Comment by mformiga** [comment]
@cv o Bruno Palvarini tem esse contato. Vou enviar mensagem agora para ele e te copiar.

**Comment by almeidafab** [comment]
estava vasculhando o site da receita e observei que esses dois serviços foram fundidos em um só (http://idg.receita.fazenda.gov.br/orientacao/tributaria/declaracoes-e-demonstrativos/dirpf-declaracao-do-imposto-sobre-a-renda-da-pessoa-fisica/extrato-do-processamento-da-dirpf). Sugiro excluir um dos serviços e renomear o outro para "Extrato do Processamento da Declaração do Imposto sobre a Renda Pessoa Física". @cv @mformiga

**Comment by mformiga** [comment]
@almeidafab por mim pode deixar o nome genérico em um deles e excluir o outro.

**Comment by almeidafab** [comment]
isso, pode fazer @cv?

**Comment by jeankirchner** [comment]
@ameidafab vou fazer aqui :)
