### ISSUE TITLE
Página de conteúdo para Darfs

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#388]
Analisando as métricas, diversos usuários estão se perdendo procurando por emissão de Darfs.

Adicionar uma página explicando o que é, como pagar, e quais serviços oferecem sua emissão.

**Comment by cv** [comment]
Adicionei o conteúdo, mas que ainda precisa de revisão (ASEGE? DGE?):

http://dev.servicos.gov.br/busca?q=darf

**Comment by cv** [comment]
Commits relacionados: aa0edbb e06be9a f7de5b6

**Comment by almeidafab** [comment]
@cv, sugestão de @eversonaguiar1 :
"O texto de descrição do serviço refere-se a tributos e os serviços que constam no guia para darf são apenas para ele, mas darf pode ser usado por exemplo, para pagamentos de ligações pessoais realizados nos órgãos, dentre outras formas de recolhimento de despesas para a União. Lembro ainda, por exemplo que um determinado serviço da spu gera um recolhimento por darf que não é propriamente um tributo."

**Comment by almeidafab** [comment]
sugestão de Bruno:
"Dando uma navegada na web, vimos que, em geral, DARFs servem para pagamentos de recetias federais, tributos e contribuições - expandindo tal conceito, ficará bom. A ideia da página ajuda bastante o cidadão."
