### ISSUE TITLE
Criar mockup para serviço da SPU

### ISSUE THREAD

**Issue by almeidafab** [servicosgovbr/portal-de-servicos#390]
na última vinda à bsb, após conversa com o Oto da SPU, @cv ficou de fazer um esboço de como ficaria o serviço no guia (http://atendimentovirtual.spu.planejamento.gov.br/Emissoes/DARF/DARFPedido.asp)

**Comment by jeankirchner** [comment]
@almeidafab Estamos trabalhando em esboços de como os serviços serão apresentados no guia, na #379 .

Esse cartão é para fazer o mesmo, só que para o serviço citado acima especificamente?

**Comment by cv** [comment]
Ainda não, @jeankirchner - esse esboço com o serviço da SPU seria mais integrado, com um formulário para o usuário preencher o número do RIP dentro da própria página do Guia. A #379 é mais genérica, e trata de serviços não-digitais (sem acesso a um webservice, etc) também.

**Comment by cv** [comment]
@almeidafab você tem alguns números RIP válidos para a gente testar o serviço?

**Comment by almeidafab** [comment]
@cv poderia priorizar esse cartão?

**Comment by cv** [comment]
Bloqueado aguardando acesso a dados do serviço.

**Comment by cv** [comment]
@mformiga e Hudson trouxeram mais notícias:

* Iremos implementar o webservice diretamente no sistema novo da SPU
* Esse webservice vai ser uma transação simples, que recebe o RIP e devolve uma mensagem a exibir para o usuário final

**Comment by cv** [comment]
Projeto do mockup criado:

https://github.com/servicosgovbr/ponte-servico-exemplo

Integração contínua:

https://snap-ci.com/servicosgovbr/ponte-servico-exemplo/branch/master

Repositório de pacotes:

https://s3-sa-east-1.amazonaws.com/servicosgovbr/centos/7/

Pacote mais recente:

https://s3-sa-east-1.amazonaws.com/servicosgovbr/centos/7/ponte-servico-exemplo-1.0.9-1.noarch.rpm
