### ISSUE TITLE
Ajustar a mensagem do formulário de opinião

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/portal-de-servicos#393]
Olá pessoal, @jeankirchner e eu estávamos falando sobre os feedbacks que temos recebido, e pensamos se não faz mais sentido reforçar a informação de que este é um canal de opinião e não de comunicação, visto que muitos cidadãos deixam seus dados esperando por uma resposta.

Pensamos em atualizar a mensagem de:
```Por favor, não inclua nenhuma informação pessoal ou financeira, como seus documentos ou dados de cartão de crédito. ``` 
para:
```Este é um formulário de opinião, por favor, não inclua nenhuma informação pessoal ou financeira. Não guardamos dados e não enviamos respostas. Sua opinião será utilizada para melhorar o Guia. ```

**Comment by sahrosa** [comment]
O que acham @almeidafab @cv @mformiga?

**Comment by mformiga** [comment]
@sahrosa tivemos feedbacks que nos ajudam a melhorar o guia ? Os feedback  estao mais em uma direção voltada ao serviço e não ao Guia ?

**Comment by cv** [comment]
@mformiga: no geral, os feedbacks inteligíveis que tivemos até agora foram reclamações relacionadas ao funcionamento de um serviço específico. Daí a ideia desse cartão: deixar claro aos usuários que não faremos uso dessas reclamações, e também que não daremos respostas.

**Comment by mformiga** [comment]
@CV tudo bem, vamos experimentar o texto.
