### ISSUE TITLE
Trocar nome do site

### ISSUE THREAD

**Issue by erickpintor** [servicosgovbr/portal-de-servicos#395]
Segundo sugestão da Silvia, a partir de uma demanda direta do Cristiano, trocar o nome do site de ```Guia de Serviços``` para ```Portal de Serviços```.

- [x] Guia de Serviços -> Portal de Serviços
- [x] guia-de-servicos -> portal-de-servicos
- [x] Github
- [x] Gitter
- [x] Waffle
- [x] Coveralls
- [x] Snap
- [x] Yum / S3
- [x] servicos.github.io
- [x] Favicons
- [ ] Anúncio

**Comment by cv** [comment]
@sahrosa, já terminei de renomear em _quase_ tudo, mas não tenho o fonte dos favicons. Pode gerar um novo com o novo nome?

**Comment by sahrosa** [comment]
Com certeza @cv! Faço rapidinho e te mando!

**Comment by sahrosa** [comment]
@cv tu tem alguma forma de gerar todos os tamanhos automaticamente? Só uma imagem grande é ok?

**Comment by sahrosa** [comment]
![ogp-logo](https://cloud.githubusercontent.com/assets/2932644/8098598/6cf3b95e-0fc8-11e5-803c-5b42a64536ca.jpg)

**Comment by cv** [comment]
Pronto, @sahrosa! Obrigado :)

(Para futura referência, usei esse gerador aqui - http://realfavicongenerator.net/ - bem completo!)
