### ISSUE TITLE
Colocar a página do serviço no ambiente de desenvolvimento

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/portal-de-servicos#398]
De acordo com a #379, na página do serviço precisamos considerar os canais de prestação. Também achamos que deve ser colocado na parte de documentação o título Documentos Necessários.

**Comment by sahrosa** [comment]
Para vocês verem como está ficando: http://ec2-54-94-244-36.sa-east-1.compute.amazonaws.com/servico-novo/programa-de-financiamento-estudantil-fies

**Comment by sahrosa** [comment]
Importante lembrar que as informações estão ali apenas como exemplo, e não serão utilizadas @almeidafab e @mformiga :)

**Comment by caduvieira** [comment]
Ficando show!  Parabéns

Em sex, 12 de jun de 2015 17:42, Samantha Rosa <notifications@github.com>
escreveu:

**Comment by jeankirchner** [comment]
:+1:

**Comment by sahrosa** [comment]
Massa! Pessoal, to testando algumas formas de mostrar as informações de cada etapa (custo, documentos, etc) e tô super na dúvida se realmente faz sentido mostrar os canais de comunicação por etapa ao invés de todos os canais juntos em um único local. Deem [uma olhada aqui e vejam o que acham?](http://ec2-54-94-244-36.sa-east-1.compute.amazonaws.com/servico-novo/programa-de-financiamento-estudantil-fies?pk_campaign=destaque)

Estou pensando se não faria mais sentido ter um único canal por etapa, e um item geral com todos os canais - no início ou fim do serviço. 

![image](https://cloud.githubusercontent.com/assets/2932644/8163302/a4bbc78a-1358-11e5-9c2d-1002899c05da.png)

**Comment by sahrosa** [comment]
Pessoal, depois de várias propostas e discussões chegamos na proposta que queremos levar adiante: [Página do serviço com os canais apenas contextualizados por etapa](http://ec2-54-94-244-36.sa-east-1.compute.amazonaws.com/servico-novo-b/programa-de-financiamento-estudantil-fies?pk_campaign=destaque)

Dessa forma a página fica mais enxuta, e a informação de onde realizar determinada etapa está junto com a etapa em si.

**Comment by almeidafab** [comment]
@sahrosa @mformiga  achamos que realmente deve continuar com vários canais em cada etapa. Achamos também que por uma questão de ordenação, o custo deve aparecer antes dos canais (que por sinal está canais de comunicação, mas na verdade é canais de prestação).
Uma dúvida sobre os botões "Inscreva-se no programa" e "Simule o financiamento". Sob qual critério eles foram criados? Seria um atalho para as etapas? Se sim, como é feita a escolha?

**Comment by sahrosa** [comment]
Oi @almeidafab! Os campos título "canais de prestação" e a ordem (faz todo sentido!!) foram ajustados :)

Quanto aos botões, criei eles a partir do que descobrimos no site do FIES. Estou fazendo uma análise de quais outros botões poderíamos criar, relacionando isso também ao nível de maturidade do serviço (#44), e já temos a seguinte lista:
* Agendar um atendimento
* Inscrever no programa
* Simular financiamento
* Calcular taxas
* Acompanhar 
* Imprimir esta página

Ainda estou analisando, e quando tivermos essas possibilidades bem fechadas, podemos pensar em incluir um campo no Editor para incluir essas informações de forma rápida e já entregar esses botões contextualizados para o cidadão :)

**Comment by almeidafab** [comment]
@sahrosa e não teria mais o botão "Começar"?

**Comment by sahrosa** [comment]
Não @almeidafab, pois teríamos os botões contextualizados ao invés do botão genérico "começar". Estamos criando esses campos no editor no cartão https://github.com/servicosgovbr/editor-de-servicos/issues/86
