### ISSUE TITLE
Exibir última atualização no serviço

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#40]

**Comment by sahrosa** [comment]
Isso existe em diversos sites que analisamos no comparativo. Precisamos definir o que configura uma atualização no serviço e como mostrar!

**Comment by cv** [comment]
Atualizações só vão efetivamente ser feitas quando começarmos a importar dados dos órgãos diretamente (a partir do [Release 2][R2]), já que esta informação não está disponível no XML atual.

[R2]:https://github.com/servicosgovbr/guia-de-servicos/milestones/Release%202

**Comment by alklaser** [comment]
TODO: Escrever como hipótese.

**Comment by oliviagj** [comment]
@alklaser, como indicado pelo @cv, movi essa issue para o release 2 também na planilha do Drive.

**Comment by cv** [comment]
Sobreposto pelo #405
