### ISSUE TITLE
Página de conteúdo para CPF

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#401]
Muitas buscas estão sendo feitas pelo termo "cpf". Seria bom ter uma página de conteúdo similar à da Darf para direcionar melhor os usuários, com uma descrição do que é um CPF, como se inscrever, atualizar e links para outros serviços relacionados.

**Comment by caduvieira** [comment]
+1

Em qua, 10 de jun de 2015 17:11, Carlos Villela <notifications@github.com>
escreveu:

**Comment by cv** [comment]
Já no ar em alpha:

http://ec2-54-94-244-36.sa-east-1.compute.amazonaws.com/conteudo/cadastro-de-pessoas-fisicas-cpf

**Comment by mformiga** [comment]
@cv acabei de enviar mensagem para eles, vamos aguardar.
