### ISSUE TITLE
Importação de páginas de serviços com marcação semântica

### ISSUE THREAD

**Issue by jeankirchner** [servicosgovbr/portal-de-servicos#402]
- [ ] Suportar importação de páginas de serviço dos órgãos, que tiverem marcação semântica na estrutura de serviço já definida
- [ ] Validar serviços importados a partir de páginas dos órgãos
- [ ] Um documento para comunicar/ensinar como essa marcação semântica pode ser feita nas páginas de serviços dos órgãos, referenciando o modelo do serviço e quais "tags" devem ser usadas

**Comment by sahrosa** [comment]
Esse cartão continua valido @jeankirchner?

**Comment by cv** [comment]
Não - iremos fazer com que a importação venha sempre do repositório de cartas, para simplificar a integração. Por outro lado, abrimos as portas para disponibilizar os serviços em outros formatos a partir do próprio portal (PDF, RDFa, JSON-LD, etc), caso outros queiram utiliza-los em seus próprios sites.
