### ISSUE TITLE
Atualizar texto da descrição da etapa

### ISSUE THREAD

**Issue by almeidafab** [servicosgovbr/portal-de-servicos#403]
@jeankirchner conversando com o Maurício achamos que o texto da descrição da etapa está um pouco confuso: "Descreva as principais etapas...Utilize apenas uma linha para cada etapa". Dentro da etapa ele tem de descrever as principais etapas ? Não pensamos em nada melhor mas talvez se fosse algo tipo "Descreva os principais pontos que o solicitante deverá observar para obter..."
O que acha?

**Comment by jeankirchner** [comment]
Muito bom @almeidafab, provavelmente esse era um texto mais genérico de descrição de etapas que acabou ficando depois das mudanças recentes. Vamos melhorar isso

**Comment by jeankirchner** [comment]
"Descreva de forma breve os objetivos dessa etapa, os principais pontos que o solicitante deve observar, e o que deve ser feito para o cumprimento dessa etapa."

O que acha @sahrosa?

**Comment by sahrosa** [comment]
Gosto! Só mudaria um pouquinho: Descreva de forma breve os objetivos dessa
etapa, os principais pontos que o solicitante deve observar, explicando o
que deve ser feito para o cumprimento dessa etapa."
