### ISSUE TITLE
Adicionar metadados sobre cartas

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#405]
Seria útil poder saber qual a versão e timestamp da última atualização do repositório de cartas,  bem como para cada serviço.

Assim, poderíamos linkar para as versões certas dos XMLs no github e editor, e também saber se o scheduler do importador (#406) está funcionando de acordo.

**Comment by sahrosa** [comment]
Fechando este cartão por estar fora do escopo ok @mformiga @almeidafab @gustavo-freitas? :)
