### ISSUE TITLE
Pesquisa por mds no portal

### ISSUE THREAD

**Issue by almeidafab** [servicosgovbr/portal-de-servicos#407]
Ao pesquisar por "mds" no portal, é exibido como primeiro resultado o ministério da previdência (mps) e em segundo lugar aparece o mds. O resultado deveria dar prioridade para mds, não acham?

**Comment by cv** [comment]
A prioridade dos serviços na busca será totalmente revista de acordo com o #443, que permitirá controle sobre as palavras-chave (que já estão na v3 e no editor), então vou fechar este cartão pq ele cai assim que indexarmos a v3.
