### ISSUE TITLE
Pedir feedback dos usuários

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#41]
**Acreditamos que** disponibilizando uma opção para dar feedback do serviço
**Para** o cidadão
**Obteremos como resultado** a percepção real dele em relação à qualidade dos serviços
**Saberemos que atingimos o resultado quando** cidadãos usarem a funcionalidade e a informação enviada possa ser considerada feedback.

Em cada página, ter um formulário pedindo feedback específico do usuário, como no gov.uk:

![screen shot 2015-02-10 at 2 16 29 pm](https://cloud.githubusercontent.com/assets/5445/6130881/70f1c976-b12f-11e4-97e3-94e07e8bd7b5.png)

Registrar:

- [x] Os dois campos do formulário
- [x] Ticket que gerou a página (não o do envio do feedback)
- [x] Timestamp

**Comment by alklaser** [comment]
Hipótese inicial de captura de feedback. Pode-se testar com uma amostra pequena e/ou estar disponível por tempo limitado, permitindo a análise manual do conteúdo textual, que pode por sua vez levar à construção de mecanismos de feedback mais estruturados.

**Comment by alklaser** [comment]
Dúvida: já teremos condições de testar essa funcionalidade com cidadãos reais? Quais são as alternativas?

**Comment by sahrosa** [comment]
Temos várias possibilidades de realizar essa coleta! Podemos ter: 
- Em todas as páginas (usando uma opção como UserVoice).
- Em todas as páginas (no topo ou no rodapé) enviando para um formulário.
- Em determinados serviços ao invés de todas as páginas.

Podemos definir o que atende melhor nossa necessidade. 

Idealmente precisamos colocar isso no site atual (assim como colocamos as métricas na Barra Brasil) para ter dados reais que poderão ser insumo de melhorias.

**Comment by sahrosa** [comment]
Note: @jeankirchner e eu estávamos comentando que podemos seguir esse modelo do gov.uk q

**Comment by sahrosa** [comment]
Note: @jeankirchner e eu estávamos comentando que podemos seguir esse modelo do gov.uk que está na issue. Mas não precisamos perguntar 'o que o usuário estava fazendo?' pois já vamos saber em qual página ele estava. 

Aí assim que tivermos um primeiro modelo, podemos ir melhorando de acordo com as várias possibilidades que temos!

**Comment by cv** [comment]
Não precisamos perguntar o que o usuário estava *fazendo*, já que dá pra inferir pela URL e caminhos de navegação dele… mas não temos dados suficientes pra saber o que ele estava *tentando* fazer, na linguagem dele.

Por mim, manter esse campo é importante para termos mais texto vindo dos usuários. Quero analisar melhor a diferença de vocabulário mais pra frente :)

**Comment by sahrosa** [comment]
Sim! Faz todo sentido. Talvez poderíamos ter algo mais controlado, como opções para selecionar (procurando x, tentando y, outro) + input de texto sobre o problema. Talvez seja mais fácil pra gente analisar depois por já estar melhor categorizado?

**Comment by sahrosa** [comment]
Oi pessoal! Eu vi que mudamos os textos do formulário de feedback. Algum motivo específico? 

Eu imagino que a ideia era deixar mais próximo do GOV.UK, mas acho que ficou muito genérico e pode acabar não gerando as respostas que procuramos. Minha sugestão abaixo:

**Como está:** Ajude-nos a tornar o Guia melhor para você! (*muita gente nem sabe o que Guia*)
**Sugestão:** Dê sua opinião e nos ajude a tornar este Guia de Serviços melhor.

**Como está:** O que aconteceu?
**Sugestão:** O que aconteceu de errado?

**Comment by cv** [comment]
Sobre o primeiro, acho confuso ter duas chamadas para ação na mesma frase (_opinar_ e _ajudar_).

No segundo, acho que explicitar "…de errado" inibe demais qualquer feedback positivo ([o último ponto](https://github.com/servicosgovbr/guia-de-servicos/issues/41#issuecomment-76813064) que o @alklaser delineou na hipótese).

**Comment by sahrosa** [comment]
Sobre a confusão de duas ações, é que a forma como a pessoa vai ajudar é opinando.

Acho que já temos algo bem legal, mas o que podemos fazer é ir melhorando. Podemos pensar sobre essas possibilidades (abaixo), e se acharmos necessário, atualizar pra um novo modelo que possa trazer as informações que queremos receber!

- - - 

Sobre inibir a opinião positiva, eu entendo, mas é porque o modelo que estamos usando é focado em receber a reportação de problemas (como é no gov.uk), mas do jeito que está agora, estamos mascarando ele como receber opiniões:

**Gov.uk:**
![image](https://cloud.githubusercontent.com/assets/2932644/6669339/193d201e-cbd7-11e4-9676-fff9cb3213bd.png)

**Guia de Serviços:**
![image](https://cloud.githubusercontent.com/assets/2932644/6669698/0e2e1e88-cbd9-11e4-9939-d75a87ae522a.png)


Se queremos receber opiniões (ou seja, positivas ou negativas) ao invés de reportar problemas, poderíamos usar um modelo mais próximo com o da **Nova Zelândia**:

![image](https://cloud.githubusercontent.com/assets/2932644/6669487/e7c71df4-cbd7-11e4-8903-47f01e0505d2.png)

Ou algo mais simples como o da **Noruega** (que até nos ajuda analisar se a pessoa conseguiu o que queria ou não): 
 
![image](https://cloud.githubusercontent.com/assets/2932644/6669270/bc56e89e-cbd6-11e4-992d-33526f7af628.png)

Temos também o da **Austrália** como referência:

![image](https://cloud.githubusercontent.com/assets/2932644/6669371/46bf9c4c-cbd7-11e4-8d99-77dbc1cab778.png)

E existem modelos como o da **França**, em que a gente clica o usuário clica em um botão no rodapé e é redirecionado para a página onde ele pode dizer qual o tipo de reportação que ele está fazendo:

![image](https://cloud.githubusercontent.com/assets/2932644/6669435/a1cd3f72-cbd7-11e4-8698-2188185e3601.png)

**Comment by sahrosa** [comment]
Conversamos sobre isso agora na stand up, e podemos tentar priorizar! O que tu acha desses pontos acima, @mformiga?

**Comment by mformiga** [comment]
Algumas considerações:

1. Gostamos do modelo que já está implementado no alpha pois está bem sucinto, agiliza o feedback e contempla várias possibilidades de feedback não excluindo os positivos. Temos visto que quem interage e envia perguntas para o guia não tem o trabalho de saber nem qual o objetivo do portal.

2. Mudaria o texto para "Ajude-nos a tornar o Guia de Serviços melhor para você" e daria um pouco mais de destaque pois acho que na descrição do serviço está parecendo continuidade das informações.

3.  Entendo que esta é uma implementação temporária apenas para coleta de métricas enquanto estamos desenvolvendo este projeto. Mais adiante poderíamos pensar em alguma forma de coletar feedback com formulários não abertos dado que o MP não tem atualmente nem previsão de ter condições para acompanhar as respostas.
