### ISSUE TITLE
Melhoria no feedback do serviço

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/portal-de-servicos#413]
Quando o usuário clicar em "não" sobre ter achado a informação do serviço útil, mostrar uma opção extra: "Quais informações você sentiu falta neste serviço?"

**Comment by sahrosa** [comment]
Essa é uma melhoria da #303. @jeankirchner pode me ajudar a fazer isso?

**Comment by sahrosa** [comment]
Referência de feedback pode ser o https://www.healthcare.gov/what-if-im-pregnant-or-plan-to-get-pregnant/
![image](https://cloud.githubusercontent.com/assets/2932644/8500508/3b44d4c6-2173-11e5-9a2b-dd20836c393f.png)

**Comment by caduvieira** [comment]
Outro tipo de feedback podia ser o do bugmuncher ou o do usersnap. https://usersnap.com/ http://bugmuncher.com/

O participa.br está utilizando uma forma dessa no canto direito inferior com o 'Reportar'

**Comment by sahrosa** [comment]
Fechando este cartão por estar fora do escopo ok @mformiga @almeidafab @gustavo-freitas? :)
