### ISSUE TITLE
Criar página de erro para serviço não existente/encontrado

### ISSUE THREAD

**Issue by jeankirchner** [servicosgovbr/portal-de-servicos#419]
Acreditamos que ao criar uma página de "serviço não encontrado", ao tentar acessar urls como "editar/servico/um-servico", irá ajudar o usuário à diferenciar um erro de servidor interno (500, erro técnico) de algumas situações comuns, como:
- urls desatualizadas, que redirecionam para página não existente
- erros de digitação

**Comment by cv** [comment]
Esta issue está no repositório errado. Vou mover para o editor.
