### ISSUE TITLE
Confusão sobre os botões de ação na página de serviço

### ISSUE THREAD

**Issue by kchnr** [servicosgovbr/portal-de-servicos#425]
Na oficina, com o MJ:
- Confundiram os botões "Começar", "Acessar" e o que eles realmente queriam dizer

**Comment by sahrosa** [comment]
@jeankirchner, acho que esse cartão vai lá pro portal, certo?

**Comment by cv** [comment]
Ou nem vai, já que vamos perder os botões de ação na v3...



- cv

**Comment by sahrosa** [comment]
Sendo tratado na https://github.com/servicosgovbr/editor-de-servicos/issues/91
