### ISSUE TITLE
Preview do serviço no editor

### ISSUE THREAD

**Issue by mformiga** [servicosgovbr/portal-de-servicos#426]
Para que os servidores possam entender o quanto sua edição estará sendo visualizada por cidadãos, precisamos de uma forma de pré-visualização do serviço, antes da sua efetiva publicação.

A pré-visualização (preview) irá auxiliar os servidores a escreverem melhores serviços, pois o feedback do seu trabalho será imediato.

**Comment by sahrosa** [comment]
Vamos incluir um botão para visualização do preview no cabeçalho do editor:

![image](https://cloud.githubusercontent.com/assets/2932644/9008703/7063f064-3772-11e5-9db9-781fdb967df9.png)

O preview será apenas do miolo do conteúdo:

![image](https://cloud.githubusercontent.com/assets/2932644/9008718/8e64372c-3772-11e5-8a03-e9d32fe963aa.png)

**Comment by cv** [comment]
Duplicata do https://github.com/servicosgovbr/editor-de-servicos/issues/75 talvez?

**Comment by sahrosa** [comment]
Verdade @cv! Fechando aqui!
