### ISSUE TITLE
Inserir campo opcional tempo estimado por etapa

### ISSUE THREAD

**Issue by mformiga** [servicosgovbr/portal-de-servicos#432]
Verificar uso na carta de serviços da ANAC http://www2.anac.gov.br/arquivos/pdf/CARTA%20DE%20SERVICOS%20INSTITUCIONAL%20FINAL.pdf

**Comment by sahrosa** [comment]
Oi @mformiga, pode explicar um pouco mais sobre este cartão?

**Comment by mformiga** [comment]
Oi @sahrosa seria um campo com a mesma estrutura do campo "Tempo estimado para realizar esse serviço", só que seria para a etapa (Algo como Tempo estimado para realziar esta etapa) e não obrigatório como o tempo do serviço.

**Comment by cv** [comment]
Tenho a impressão de que adicionar esse campo vai aumentar muito a complexidade do formulário para o editor, sem necessariamente adicionar muito valor (já que o tempo estimado da etapa pode ser explicitado na própria descrição da etapa, caso ele seja importante).

@mformiga, você tem uma ideia de quantos serviços vão ter etapas com tempo estimado?

**Comment by mformiga** [comment]
@cv e @sahrosa, concordamos, por favor podem manter sem este campo e
incluir nas orientações do preenchimento do campo descrição da etapa essa
possibilidade caso exista.

2015-08-04 14:49 GMT-03:00 Carlos Villela <notifications@github.com>:

**Comment by sahrosa** [comment]
Combinado @mformiga! :)
