### ISSUE TITLE
Inserir campo referente aos requisitos e condições a serem satisfeitas pelos demandantes

### ISSUE THREAD

**Issue by mformiga** [servicosgovbr/portal-de-servicos#433]
Alguns casos apontados na carta de serviços da ANAC apontados como requisitos podem ser mapeados para documentos. Porem há outros que estão no campo referente a requisitos e parecem estar mais bem associados a este campo mesmo. Verificar serviço da página 23 da carta (http://www2.anac.gov.br/arquivos/pdf/CARTA%20DE%20SERVICOS%20INSTITUCIONAL%20FINAL.pdf)

**Comment by sahrosa** [comment]
Resolvida da seguinte forma:

![image](https://cloud.githubusercontent.com/assets/2932644/9046960/dffe755e-3a04-11e5-8721-5020595b84da.png)

**Comment by mformiga** [comment]
@sahrosa nesse caso pelo menos um tipo de solicitante é obrigatório e requisitos opcional

**Comment by sahrosa** [comment]
Legal @mformiga! Vou colocar isso na validação então!
