### ISSUE TITLE
Exibir nível de maturidade do serviço

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#44]
"Aqui você pode…"

* Se informar
* Localizar um ponto de atendimento
* Agendar um atendimento
* Simular e calcular taxas e benefícios
* Imprimir e preencher formulários
* Realizar
* Acompanhar

**Comment by sahrosa** [comment]
Estou pensando em como podemos relacionar isso com as linhas da vida e/ou perfis de usuários (ser existirem). Vamos falar!

**Comment by alklaser** [comment]
TODO: Escrever como hipótese.

**Comment by sahrosa** [comment]
A partir do que temos no GdS atual e do que vimos no Estudo Comparativo, levantei quais tipos de conteúdo teremos na página do serviço e em sua página de métricas (incompleto, coloquei apenas para mostrar que teremos). 

Sentem falta de algo? Vamos completando! Pra mim deu mais visibilidade sobre o que podemos ter, e portanto, podermos depois definir o que é Maturidade 1, Maturidade 2, etc... 

![image](https://cloud.githubusercontent.com/assets/2932644/6619100/b2b9864e-c8a6-11e4-879c-156045faecd0.png)

**Comment by sahrosa** [comment]
Achei essa explicação em um artigo, muito interessante e tudo a ver com o que estamos falando aqui:

**Level of online sophistication:** The European Commission, DG Information Society (2001) proposed a four-stage framework for the classification of e-services regarding to the level of online sophistication of these services, as follows:
* **Information:** includes online information about public services (e.g. information necessary to start the processes to obtain the public services available on the websites).
* **Interaction:** downloading of forms (e.g. downloadable or printable forms to start the processes to obtain the public services on the websites) is available.
* **Two-way interaction:** comprises processing of forms, including authentication (electronic forms to start the processes to obtain the public services on the websites). The communication with institutions and persons in charge (via e-mail) and the notification about the case progress is also included in this stage.
* **Transaction:** comprises full electronic case handling of processes by the service provider, including decision, notification, delivery and payment if necessary. 

The services of each lower stage are included in the next higher stage. 

Artigo: http://unpan1.un.org/intradoc/groups/public/documents/nispacee/unpan004382.pdf

**Comment by oliviagj** [comment]
Relacionada a #124

**Comment by caduvieira** [comment]
@sahrosa Gostei do level de integração descrito no artigo também. Poderia ser uma 'estrela' para indicar um serviço integrado. Creio que o serviço piloto do inss almeja isso.

**Comment by sahrosa** [comment]
Fechando cartão por estar fora do escopo, ok @gustavo-freitas @almeidafab @mformiga? :)
