### ISSUE TITLE
Análise do escopo - Piloto do SPU 

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/portal-de-servicos#440]
Criamos este cartão para mapear o que será o escopo do piloto do SPU.

- [x] Analisar o que deve ser feito, se será um mock ou uma integração completa caso o SPU disponibilize o serviço
- [ ] Criar cartões para entregas mínimas, priorizando com '0' (Obrigatório), '1' (Nice to have), '2' (só se não tiver mais nada pra fazer)

**Comment by sahrosa** [comment]
@gustavo-freitas tem que detalhar esta integração

**Comment by oliviagj** [comment]
Escopo movido para o [repositório específico](https://github.com/servicosgovbr/ponte-servico-exemplo/issues/1)
