### ISSUE TITLE
Página inicial do Portal

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/portal-de-servicos#449]
> Solicita-se proposta de revisão da home page devido aos resultados da análise estatística de uso dessa página. 

* Propõe-se simplificação e focalização na caixa de busca. O menu da esquerda poderia ficar em segundo plano (ver opção em http://noticias.gov.br/noticias/)
* Simplificar o texto antes do buscador e sem destaque para o bem vindo pois está repetitiva a palavra Portal de Serviço.
* Sugestão: Bem-vindo! Aqui você poderá encontrar informações sobre serviços públicos, agendar um atendimento, entrar em contato com os órgãos e até começar um serviço.

**Comment by sahrosa** [comment]
Algumas referências:
* [Austrália](http://www.australia.gov.au/)
* [Reino Unido](https://www.gov.uk/)
* [Noruega](http://www.norge.no/en)

**Comment by sahrosa** [comment]
Olá pessoal!

Temos uma nova proposta para a página inicial do Portal! Estou bem feliz com a proposta, e espero que gostem também.

Demos mais "vida" pra página, trazendo elementos mais visuais, e também colocando a cor certa nos links. A busca está muito mais evidente agora, num local mais apropriado. Temos quatro destaques manuais, seguidos das categorias mais acessadas (inicialmente serão categorias definidas). Logo abaixo, os serviços mais acessados. Para cada categoria, temos um ícone (do Font Awesome).

![gds pagina inicial_v4-5](https://cloud.githubusercontent.com/assets/2932644/10010536/08e3d83a-60c3-11e5-9513-f9d7eb39974a.jpg)

**Comment by caduvieira** [comment]
@sahrosa Gostei muito dessa nova forma de exibir. Como sugestão de ícones sugiro o Maki[1] que é voltado para cartografia e muito das categorias podem ser melhoradas como "Segurança e Ordem Pública" com o 'Police' e a categoria "Indústria" com 'Industrial'.

Pode ser utilizado o Fontello para criar essa mistura entre fontawesome e maki escolhendo somente as imagens desejadas. [2]

O Modern Pictogram 'home' pode ser utilizado para Habitação sem confundir o usuário.

[1] https://www.mapbox.com/maki/
[2] http://fontello.com/

**Comment by caduvieira** [comment]
E a busca na página inicial podia ser só uma. Não acha?

**Comment by augusto-herrmann** [comment]
Já comentei isso uma vez pessoalmente, mas acho que vale a pena repetir aqui.

É necessário fazer uma reflexão do que a navegação por categoria agrega de valor para o cidadão. As pessoas realmente, quando vão procurar um serviço, começam selecionando uma categoria e depois refinando? Sugiro usar os dados analíticos de navegação para verificar essa hipótese.

Tenho a impressão de que o mais comum é ou iniciar com uma busca textual ou ir para os serviços em destaque / mais utilizados. Na hipótese de iniciar a navegação por uma busca textual, é natural quando se encontra muito resultados que se queira filtrá-los com refinamentos sucessivos. Uma busca facetada ajudaria muito nos casos que retornam muitos resultados, e as categorias poderiam ser uma das dimensões de uma busca facetada disponíveis para filtrá-los.

**Comment by augusto-herrmann** [comment]
Para ilustrar, segue um exemplo de uso de busca facetada com refinamentos sucessivos: o portal do LexML. Ao clicar os itens no menu da esquerda, os resultados são filtrados e são exibidos apenas os itens cujos valores dos metadados correspondem ao que foi clicado.

![busca facetada do LexML 2015-09-22 14 40 09](https://cloud.githubusercontent.com/assets/1058414/10026428/1fd624ce-6138-11e5-9568-c4fe237f44cb.png)

Note que a tela inicial do LexML tem apenas a busca textual. Esses metadados aparecem apenas após ter sido iniciada uma busca textual. Apenas os valores existentes nos resultados aparecem como opções de filtro (no exemplo, Lei Complementar não aparece entre as opções de categoria de documento, pois não existe nos resultados).

**Comment by sahrosa** [comment]
Oi @caduvieira. Excelentes dicas! 
* Sobre os ícones, vou criar um cartão para mapearmos quais ícones usaremos. Vou dar uma olhada nas duas referências que tu passou.
* Sobre a busca duplicada, eu concordo! Acho que no caso da página inicial precisamos de uma busca mais evidente, e por isso acho que a busca do cabeçalho deveria sumir. O que acham @mformiga?

Oi @augusto-herrmann! Sobre os teus pontos:
* Acredito que termos uma busca facetada não impede o fato de termos categorias. A parte positiva das categorias serve principalmente para a parcela do público que está conhecendo o portal, e quer conhecer os serviços disponíveis. Essa discussão é bem legal, e eu sempre de lembrar da diferença entre recall e recognise. Recall (_lembrar_) é o modelo da busca, onde o usuário é "obrigado" a lembrar o que está procurando. Recognise (_reconhecer_) é o modelo dos destaques (de serviços, categorias, etc) onde ajudamos o usuário a reconhecer coisas que ele pode estar interessado. E a combinação dessas duas formas juntas é o que faz o portal ficar ainda mais completo.
* Sobre a busca facetada, acho que essa é discussão de outro cartão, e entendo o teu ponto e concordo com a importância. Acho que a busca pode e deve ser melhorada ao longo do tempo, não esquecendo que o Portal deve estar sempre vivo e mutante :)

**Comment by almeidafab** [comment]
@sahrosa também gostei muito desse layout. Eu só retiraria os "Serviços populares..." e deixaria apenas os "Serviços em destaque..." acho que o visual ficaria mais limpo. Como @augusto-herrmann falou, acho que a página inicial deve ficar mais "limpa" possível, focando o usuário na busca textual.

**Comment by sahrosa** [comment]
Oi @almeidafab! Concordo com vocês, então minha sugestão é deixarmos menos serviços populares, talvez uns 4 apenas. Mas acho que pode ser importante pra dar um pouquinho mais de opções pro cidadão. Vou testar com poucos e sem nenhum, e aí decidimos qual seguir. Obrigada!!

**Comment by felipecaparelli** [comment]
Olá Samantha,

excelente essa interface, parabéns!
Acredito que a usabilidade e a acessibilidade vão garantir com que as
pessoas consigam contribuir mais facilmente no projeto.

Eu só mudaria a ordem dos itens. Ao invés de alfabética, colocaria por
peso/importância.
E concordo em deixar Serviços em Destaque ao invés de Serviços populares
(esse segundo termo pode remeter a serviços que atendem a população).

Quanto ao questionamento do Augusto, acredito que um simples teste A/B da
página inicial utilizando o modelo baseado em categorias de serviços e
outro com uma busca aberta.

PS: pessoalmente, acredito muito mais no modelo que direciona o usuário, no
caso o categorizado... mas também podem haver algum recurso de busca para
auxiliar usuários mais avançados.

Att,


Felipe Caparelli

*Java Certified Programmer - SCJP*

Para honra e glória do Senhor


WRO Consulting

fone: 11 98766-9741

twitter: @wro_consulting <https://twitter.com/wro_consulting>


2015-09-23 14:25 GMT-03:00 Samantha Rosa <notifications@github.com>:

**Comment by sahrosa** [comment]
Muito obrigada @felipecaparelli :)

Concordo sobre os destaques, acho que não deixei claro acima, mas a proposta é que eles sejam escolhidos por importância e não mostrados em ordem alfabética.

Gostei da dica sobre serviços populares também! Vou repensar essa parte.

Obrigada novamente!

**Comment by felipecaparelli** [comment]
Desejo muito sucesso ao projeto!

[]s,


Felipe Caparelli

*Java Certified Programmer - SCJP*

Para honra e glória do Senhor


WRO Consulting

fone: 11 98766-9741

twitter: @wro_consulting <https://twitter.com/wro_consulting>


2015-09-23 17:38 GMT-03:00 Samantha Rosa <notifications@github.com>:

**Comment by mformiga** [comment]
@sahrosa Seguem sugestões após alguns alinhamentos de nossa equipe:

1. Podemos seguir com a ideia de apresentar as categorias e vermos o resultado a partir do número de acessos.
2. Pedimos para não apresentar neste momento os serviços em destaque. Só vamos utilizar quando realmente for necessário. Pode deixar a implementação da forma como está.
3. Pedimos que coloque os serviços mais acessados no lugar dos serviços em destaque.
4. Pedimos trocar o nome de "Serviços mais acessados do portal de serviços" para "Serviços mais acessados".

Tudo bem ?
