### ISSUE TITLE
Impressão da página de serviços do órgão

### ISSUE THREAD

**Issue by mformiga** [servicosgovbr/portal-de-servicos#451]
Este é um cartão de melhoria e não deve ser considerado neste momento. A ideia é que haja opção semelhante à impressão do serviço para a página do órgão que será a carta de serviços eletrônica. Talvez seja interessante fornecer opção para escolha de serviços a serem impressos desta carta

**Comment by cv** [comment]
Duplicata da https://github.com/servicosgovbr/cartas-de-servico/issues/23.

**Comment by cv** [comment]
@mformiga como conversado ontem, precisamos de uma indicação se existe um equivalente ao IDG,  ou outro documento explicitando normativas de design para documentos impressos do Governo Federal, para dar prosseguimento a este cartão.

**Comment by mformiga** [comment]
@cv tiver reunião com alguns integrantes da Secom ontem e fiz esta
pergunta. Ficaram de verificar. Acabei de enviar uma mensagem questionando
sobre este tema, desta vez copiando a Ascom também. Ao que tudo indica, não
há padrão. Mas vou tentar me certificar.

2015-09-04 15:43 GMT-03:00 Carlos Villela <notifications@github.com>:

**Comment by sahrosa** [comment]
Oi @mformiga! Alguma novidade sobre a existência de um padrão? :)

**Comment by mformiga** [comment]
@sahrosa a Secom já disse que não tem padrão, preciso apenas confirmar com SEGEP se esse padrão existe, pedi para o Everson verificar isso agora

**Comment by gustavo-freitas** [comment]
@mformiga Isso já está sendo desenvolvido em outros cartões. Ver cartão #400.
