### ISSUE TITLE
Formato para o cidadão colaborar com o conteúdo do portal

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/portal-de-servicos#453]

**Comment by cv** [comment]
Depende da #77, em particular do tipo de login que vamos adicionar ao Editor. Caso seja um login aberto (como o Login Cidadão ou outro provedor OAuth2 / OpenID Connect), fica relativamente fácil.

No caso do GERID, não sei se vamos poder habilitar logins que não sejam de servidores públicos.

**Comment by caduvieira** [comment]
+1 para algo em torno do o OAuth2. Agora não acompanhei a discussão da
atualização do OAuth1 para o OAuth2 em que um dos criadores do OAuth1 tirou
o seu nome e suporte do OAuth2.

Em sex, 11 de set de 2015 04:01, Carlos Villela <notifications@github.com>
escreveu:
