### ISSUE TITLE
Mostrar gratuidade abaixo do título

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/portal-de-servicos#459]
Continuação da #447

**Comment by oliviagj** [comment]
é igual à #463?

**Comment by sahrosa** [comment]
@oliviagj a #463 é uma continuação, pois precisamos fazer esse condicional de só mostrar a gratuidade quando efetivamente for gratuito.

**Comment by gustavo-freitas** [comment]
De acordo com conversa com a Sá, essa mudança não está alinhada com a nossa estrutura de informação previamente decidida, onde a gratuidade do serviço é exibida na área de 'Outras Informações'. Fechando cartão.
