### ISSUE TITLE
Feedback não está funcionando no ambiente alpha

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/portal-de-servicos#466]

**Comment by cv** [comment]
Esse não é um problema com celulares, mas na configuração do ambiente de produção. 



- cv

**Comment by sahrosa** [comment]
Mas em produção, no desktop, funciona, @cv.

**Comment by cv** [comment]
Acabei de testar aqui no desktop, e não funcionou da mesma maneira. Ticket:
c1e00a2d7eff

**Comment by sahrosa** [comment]
Opa, verdade! Eu tava olhando em prod. Vou mudar o nome do cartão.
