### ISSUE TITLE
Nomes populares ainda não aparecem na tela de serviços

### ISSUE THREAD

**Issue by kchnr** [servicosgovbr/portal-de-servicos#470]

**Comment by almeidafab** [comment]
o campo legislação tambem não aparece na visualização

**Comment by sahrosa** [comment]
Olá @almeidafab e @mformiga! 

Os nomes populares (quando cadastrados) aparecem na tela na área de "Outras informações", após as etapas, com o texto que combinamos em outro cartão.

Vocês podem ver o exemplo do ["Serviço Teste" aqui](http://104.236.231.239.xip.io/servico/servico-teste).

:)

**Comment by mformiga** [comment]
@sahrosa o link não abre

**Comment by sahrosa** [comment]
Mas que estranho @mformiga! Aqui está abrindo normalmente. Pode tentar de novo? De repente o portal estava em deploy quando tu tentou antes :)

**Comment by sahrosa** [comment]
Oi @almeidafab! A visualização está sendo feita no cartão #75 e ainda não está mostrando a legislação, realmente. Lá no cartão vocês podem dar uma olhada no checklist do que ainda falta para a visualização estar completa :)

**Comment by gustavo-freitas** [comment]
Funcionalidade coberta no cartão #75.
