### ISSUE TITLE
Redirecionamento para domínio "canônico"

### ISSUE THREAD

**Issue by augusto-herrmann** [servicosgovbr/portal-de-servicos#480]
Atualmente o Portal de Serviços pode ser acessado por diversos domínios:

* http://www.serviços.gov.br/
* http://serviços.gov.br/
* http://www.servicos.gov.br/
* http://servicos.gov.br/
* http://www.guiadeserviços.gov.br/
* http://guiadeserviços.gov.br/
* http://www.guiadeservicos.gov.br/
* http://guiadeservicos.gov.br/

Talvez existam ainda outras que não conheço.

Essa multiplicidade [prejudica a SEO](https://www.seo.com/blog/multiple-domains-seo/) e a visibilidade do Portal de Serviços aos motores de busca. Entendo que deveria ser definido um único domínio como sendo o canônico e todas as URLs dos demais domínios deveriam ser redirecionadas para URLs correspondentes no domínio canônico.

Ex.:
http://guiadeservicos.gov.br/servico/prouni-programa-universidade-para-todos?pk_campaign=destaque --> HTTP 301 --> http://www.serviços.gov.br/servico/prouni-programa-universidade-para-todos?pk_campaign=destaque

**Comment by gustavo-freitas** [comment]
@oliviagj devemos alinhar e definir uma solução com o pessoal da DGE?

**Comment by oliviagj** [comment]
@gustavo-freitas acho que é bom iniciar esta conversa com @mformiga, @almeidafab e @cevmelo. A sugestão do @augusto-herrmann me parece fazer todo sentido.

**Comment by oliviagj** [comment]
Ficou definido em reunião em 16/11 que @mformiga e @almeidafab cuidarão disso
