### ISSUE TITLE
Portal apresenta página de erro

### ISSUE THREAD

**Issue by cevmelo** [servicosgovbr/portal-de-servicos#489]
1- Entrar na página http://104.236.231.239.xip.io/servico/carlosteste2?pk_campaign=busca

2- Clicar no link http://104.236.231.239.xip.io/orgao/ministerio-do-planejamento-orcamento-e-gestao-mp o portal apresenta página de erro.

![image](https://cloud.githubusercontent.com/assets/15729050/11070876/d9b335c8-87c4-11e5-9bdc-24fad8106eba.png)

![tp001-2](https://cloud.githubusercontent.com/assets/15729050/11096396/e7cc37d8-8880-11e5-8498-c086da9b9bac.JPG)

**Comment by cevmelo** [comment]
Verificar @gustavo-freitas @sahrosa

**Comment by gustavo-freitas** [comment]
Carlos, tentar novamente, faz favor.

**Comment by sahrosa** [comment]
Está acontecendo o mesmo comportamento pra mim @cevmelo @gustavo-freitas em todos os órgãos. Deve ser algum erro relacionado ao SIORG.

**Comment by cevmelo** [comment]
Também apresenta o mesmo erro:

http://104.236.231.239.xip.io/orgao/ministerio-da-ciencia-tecnologia-e-inovacao-mcti

**Comment by cevmelo** [comment]
Problema parecido em: https://github.com/servicosgovbr/editor-de-servicos/issues/423

@gustavo-freitas @sahrosa

**Comment by gustavo-freitas** [comment]
@cevmelo esse é o mesmo problema do card #493. Estou fechando o card.
