### ISSUE TITLE
Relacionar o conteúdo markdown das áreas de interesse aos destaques da página inicial

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/portal-de-servicos#500]
Continuação do cartão #465 mas depende do cartão https://github.com/servicosgovbr/editor-de-servicos/issues/391

**Comment by oliviagj** [comment]
Associada também ao #498, certo @sahrosa?

**Comment by sahrosa** [comment]
Exato @oliviagj!

**Comment by oliviagj** [comment]
Esse aqui deixa de existir junto com a #498, certo? @mformiga @almeidafab

**Comment by sahrosa** [comment]
Exato @oliviagj. Vou fechar o cartão!
