### ISSUE TITLE
Inverter ordem dos botões da barra do Editor

### ISSUE THREAD

**Issue by almeidafab** [servicosgovbr/portal-de-servicos#503]
@sahrosa @gustavo-freitas Conforme conversa com a SEGEP, eles acharam melhor mudar a ordem dos botões na barra. Seguindo uma ordem natural, primeiro o usuário irá salvar, depois visualizar e em seguida publicar. 

Hoje está assim: "Alterar publicações", "Visualizar" e "Salvar".
Como deveria estar: "Salvar", "Visualizar" e "Alterar publicações"

**Comment by oliviagj** [comment]
@almeidafab @mformiga 
Conforme conversado ontem, 23/11, fecharei este cartão a partir do entendimento de que esta modificação não seria oportuna e poderia mesmo prejudicar a usabilidade do Editor. Para fins de documentação, elenco abaixo os aspectos de destaque dessa análise:
- o "Alterar publicações" (Aceitar/rejeitar alteração) só aparecerá para usuários com perfil de publicador para o órgão específico. Portanto, não afeta a navegação da grande maioria dos casos de uso
- Nos casos de uso em que o "Alterar publicações" estará visível, a expectativa é que o foco principal do usuário (publicador) esteja nesta funcionalidade, logo a posição de destaque dos botões.
