### ISSUE TITLE
Mudança de órgão causa erro

### ISSUE THREAD

**Issue by mformiga** [servicosgovbr/portal-de-servicos#504]

**Comment by mformiga** [comment]
Ao alterar o nome do órgão do serviço "Teste" de Ministério do Planejamento para ANTT aconteceu este erro abaixo.
![image](https://cloud.githubusercontent.com/assets/10866724/11307695/044a5f1c-8fa1-11e5-8be5-b114567ec367.png)

Aproveito para perguntar o que acontece quando criamos um novo serviço de um novo órgão. A página de órgão é criada automaticamente sem a descrição e as informações de contato do órgão ?

**Comment by kchnr** [comment]
Não foi possível reproduzir o bug descrito no cartão. Recentemente foram feitas várias alterações no editor de serviços, após a criação deste cartão, e essas outras alterações provavelmente resolveram este problema.

**Comment by kchnr** [comment]
Não foi possível reproduzir o problema descrito. Várias alterações foram feitas após a criação deste cartão, e provavelmente já resolveram o problema.

**Comment by gustavo-freitas** [comment]
@kchnr @almeidafab @mformiga problema relacionado ao cartão https://github.com/servicosgovbr/editor-de-servicos/issues/448. Fechando o cartão.
