### ISSUE TITLE
Erro na gratuidade do serviço

### ISSUE THREAD

**Issue by mformiga** [servicosgovbr/portal-de-servicos#509]
Ao editar um serviço e informar que há custos associados, o sistema permite publicar o serviço mesmo sem informar nenhum custo. Além disso, conforme discussões iniciais do editor, se o serviço for gratuito, esta informação precisa aparecer para o usuário no portal.

**Comment by sahrosa** [comment]
Oi @mformiga, sobre a informação, mostramos que o serviço não possui custos, conforme imagem abaixo.

![image](https://cloud.githubusercontent.com/assets/2932644/11426364/c61257bc-9442-11e5-87c2-b9195ca8d0a4.png)

Sobre a validação, precisamos investigar.

**Comment by andreleite** [comment]
No ambiente local esse problema não aparece. Assim que o cartão #446 for concluído e o editor voltar a funcionar, testarei em alpha para possivelmente concluir esse card.

**Comment by gustavo-freitas** [comment]
Não conseguimos reproduzir esse problema. Estamos fechando esse cartão.
