### ISSUE TITLE
Adicionar texto ao Mapa do Site

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#51]
http://gds-alpha.herokuapp.com/conteudo/mapa-do-site

**Comment by sahrosa** [comment]
A gente não consegue construir o mapa do site de forma automatizada?

**Comment by cv** [comment]
A implementação atual, que na verdade é só uma página de conteúdo markdown, não permite, mas nada nos impede de gerar algumas partes – listas de linhas da vida, órgãos e áreas de interesse – automaticamente.

Reparei que o estilo do [mapa do site do Portal Brasil](www.brasil.gov.br/mapadosite) é bem diferente, também.

**Comment by sahrosa** [comment]
Legal CV! Podemos pensar nessas automatizações mais pra frente então :) 

Abaixo como o nosso mapa basicamente é (ou vai ser). Estou montando o sitemap e alguns fluxos pra dar conta de todas as páginas que estamos reformulando, sem deixar faltar nada. Sentem falta de algo?

![image](https://cloud.githubusercontent.com/assets/2932644/6534758/c78befe4-c41e-11e4-9eba-ed7f419d50cf.png)

**Comment by cv** [comment]
Tá lindo! :)

Qual a diferença entre uma situação da vida e uma linha da vida?

2015-03-06 16:36 GMT-03:00 sahrosa <notifications@github.com>:

**Comment by sahrosa** [comment]
É que temos '1' linha da vida com 'x' situações – ou eventos – da vida (nascimento, casamento, divórcio, aposentadoria). 

Comentei com @erickpintor e @jeankirchner aqui por cima, e eles tem a mesma visão! A @oliviagj complementou que poderemos num futuro poderemos ter várias linhas da vida por perfil de cidadão (estudante, idoso, etc). Que acha, @cv? 

Outra coisa que Jean falou, e que podemos pensar, é que essa nomenclatura não se faz clara (em vários referências existem nomenclaturas diferentes, como jornada da vida, linha da vida, situações da vida). Mas vou mover essa questão das nomenclaturas para a #55.

**Comment by cv** [comment]
:+1: 

Aliás, podemos fazer o mapa do site em um formato similar ao da imagem acima. Ia ficar bem legal.

**Comment by oliviagj** [comment]
Tá muito bacana! (tô buscando alternativas para "massa" e "legal" :P)

**Comment by oliviagj** [comment]
Turma supimpa, se a @sahrosa começou, não tá começado?
