### ISSUE TITLE
Markdown não funciona

### ISSUE THREAD

**Issue by mformiga** [servicosgovbr/portal-de-servicos#512]
Fiz um teste no campo "descrição" do serviço "teste" inserindo conteúdo que deveria ser um link mas não funcionou.

**Comment by sahrosa** [comment]
Oi  @mformiga, isso tá acontecendo no Portal? Poderia colocar um screenshot  da tela com o erro?

**Comment by sahrosa** [comment]
Oi @mformiga, testamos aqui e vimos que estava com um espaço em branco, por isso o markdown não funcionou. Estou fechando este cartão. O link funciona apenas quando não há espaço entre o colchete e o parênteses.

![image](https://cloud.githubusercontent.com/assets/2932644/11426342/78269bb2-9442-11e5-8569-979cfe386008.png)

**Comment by mformiga** [comment]
@sahrosa Ok.
