### ISSUE TITLE
Revisar texto da página de acessibilidade

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#52]
http://gds-alpha.herokuapp.com/conteudo/acessibilidade

**Comment by sahrosa** [comment]
Note: temos que atualizar para a fonte do texto para Open Sans.

**Comment by oliviagj** [comment]
Precisaremos de um olhar de @mformiga, @almeidafab ou outra pessoa da DGE que manje de acessibilidade nesta estória aqui.

**Comment by erickpintor** [comment]
Os atalhos de teclado estão funcionando corretamente e não há links quebrados no conteúdo da pagina.

No que diz respeito a funcionalidade de alto contraste, os seguintes itens precisam de ajustes:
- Barra com link de feedback no topo da pagina
- Botão de "começar" ou "agendar" um serviço
- Barra Brasil

Issue #161 foi criada para endereçar os ajustes necessários.
