### ISSUE TITLE
Conteúdo da página de órgão vazio

### ISSUE THREAD

**Issue by mformiga** [servicosgovbr/portal-de-servicos#524]
Ao acessar a página de um órgão em produção,  a descrição não aparece. Após algumas tentativas as descrições apareceram mas voltaram a desaparecer.

**Comment by mformiga** [comment]
![image](https://cloud.githubusercontent.com/assets/10866724/12123370/b1da9f26-b3c7-11e5-949f-07a8e3d21a70.png)

**Comment by mformiga** [comment]
@gustavo-freitas  Quando isso acontece, o link para geração da carta eletrônica não funciona.

**Comment by gustavo-freitas** [comment]
@mformiga tens como verificar se esse problema acontece em ambiente de homologação?Considerando que o ambiente de produção não possui a última versão do código, não acho produtivo validarmos funcionalidades em produção. 

Screenshot em ambiente alpha:

![image](https://cloud.githubusercontent.com/assets/2887992/12144010/04c75464-b46c-11e5-8d9e-7e490f7f0021.png)

Screenshot em ambiente de desenvolvimento:

![image](https://cloud.githubusercontent.com/assets/2887992/12144048/4eb646de-b46c-11e5-94df-9fe1edc57984.png)

**Comment by mformiga** [comment]
@gustavo-freitas Não vi acontecer em dev.

**Comment by gustavo-freitas** [comment]
@mformiga conforme conversa anterior, os órgãos que não possuem descrição são órgãos que precisam ter suas páginas criadas. Já tínhamos validado esse comportamento com o @almeidafab no cartão #481. Vou fechar esse cartão, ok?

**Comment by mformiga** [comment]
@gustavo-freitas  Este comportamento acontece em produção para páginas de órgãos que possuem descrição no conteúdo.  Nesse caso, precisamos investigar.

**Comment by mformiga** [comment]
@gustavo-freitas Veja que aconteceu novamente conforme figura abaixo. Dessa vez foi até pior pois não apareceram os serviços do MAPA.

![image](https://cloud.githubusercontent.com/assets/10866724/12150804/04c899b0-b493-11e5-8770-ebb5af4caa6f.png)

**Comment by gustavo-freitas** [comment]
@mformiga não temos a última versão do código em produção. Produção não é um lugar coerente para executarmos nossos testes. Existe alguma situação semelhante acontecendo em ambiente de homologação?

**Comment by gustavo-freitas** [comment]
@maiteb página do órgão MAPA em alpha (com a última versão do código e apontando para cartas-de-servico):

![image](https://cloud.githubusercontent.com/assets/2887992/12151075/661dfa4c-b494-11e5-88cd-24c3e8b439ce.png)

**Comment by mformiga** [comment]
@gustavo-freitas O que você sugere para resolver este caso, então ?

**Comment by gustavo-freitas** [comment]
@mformiga como não existe um cenário problemático na última versão do código, acredito que não temos nenhum caso para resolver. Tão logo esse código estiver em produção, os órgãos que possuem página criadas deverão ser exibidos corretamente, conforme ambiente de homologação (dev) e alpha.

**Comment by gustavo-freitas** [comment]
@mformiga conforme mensagem anterior, não existe correção para realizar nesse cartão. Estou fechando o cartão.
