### ISSUE TITLE
Importar URL para agendamento

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#53]
Hoje estamos importando apenas URLs para prestação do serviço (que muitos serviços legados descrevem erroneamente, aliás).

No caso do Auxílio-Doença, entre muitos outros do INSS, existe um link no bloco "Informações Úteis":

```xml
    <informacoesUteis>
        <informacaoUtil>
            <tipoInformacaoUtil>
                <titulo>Agendamento</titulo>
            </tipoInformacaoUtil>
            <descricao>Agende aqui seu atendimento.</descricao>
            <url>http://www2.dataprev.gov.br/sabiweb/agendamento/inicio.view</url>
```

XML de exemplo completo: https://gist.github.com/cv/f3b13e1e9b3f00953fb5

**Comment by erickpintor** [comment]
String urlAgendamento está disponível no objeto Servico. Refactorings a caminho.

https://github.com/servicosgovbr/guia-de-servicos/commit/e649fe150bd360d407be788f16648d8d3360bb04
