### ISSUE TITLE
Erro de atualização dos containers do docker

### ISSUE THREAD

**Issue by isaacvits** [servicosgovbr/portal-de-servicos#542]
Toda vez que é executado o script de update dos containers do docker, acontece um erro no DeviceMapper e os containers não são atualizados.

**Comment by caduvieira** [comment]
Está sendo feito teste com o overlayfs.

**Comment by caduvieira** [comment]
E essa issue devia estar em servicosgovbr/docker sugiro fechar aqui e reabrir lá.

**Comment by isaacvits** [comment]
Issue transferida para servicosgovbr/docker.
