### ISSUE TITLE
Lentidão no carregamento da carta serviços

### ISSUE THREAD

**Issue by isaacvits** [servicosgovbr/portal-de-servicos#552]
Tanto o portal de serviços e editor de serviços demora muito para carregar a carta de serviços. O editor de serviços esta demorando em média duas horas e portal de serviços em média 10 minutos para carregar os serviços.

**Comment by ricdelima** [comment]
1- Primeiro ponto que gostariamos de destacar é que toda vez que é criada um novo serviço no Portal, também é criado uma Branch no GitHub para aquele serviço. Cada Branch criado é uma cópia do Branch Master com todos os arquivos que existem nele naquele momento mais o arquivo do novo serviço. Assim se o Branch Master tem 1.000 arquivos, quando se cadastrar um novo serviço ele irá criar um Branch com 1.001 arquivos. 
Na forma como foi desenvolvida a arquitetura do Portal está criando milhares de Branchs com milhares de arquivos que não são necessários para aquele Branch, de forma exponencial.

2- Pensamos que poderia ser essa grande quantidade de arquivos em cada Branch que faz demorar 75 minutos para o processo do Editor de Serviços subir, pois atualmente a Carta de Serviços está com 670 Branchs.
Nessa linha fizemos uma Fork da Carta de Serviços original (https://github.com/ricdelima/cartas-de-teste) e para cada Branch apagamos todos os serviços que não o próprio arquivo XML criado quando o serviço foi cadastrado. Assim cada Branch continha apenas o serviço específico do Branch.
Porém o tempo para o processo do Editor subir foi o mesmo, 75 minutos. Logo não é o fato de terem muitos arquivos nas Branchs que fazem o processo demorar tanto.
Verificamos também que, em média, cada serviço demora 8 segundos para ser carregado. Dessa forma quando o Portal, atualmente com 590 serviços, tiver com 3000 serviços, ficará quase impossível reiniciar seu processo.

3- Verificamos que para cada serviço que tenta ser carregado quando o processo do Editor sobe, vários checkouts são realizados em um diretório temporário criado naquele momento. Assim toda vez que o processo sobe, os checkouts são realizados todos novamente.
Nossa sugestão seria que os checkouts fossem criados em um diretório fixo, assim demoraria 75 minutos para subir o processo apenas na primeira vez, mas nas próximas vezes o checkout não teria que ser completo e provavelmente o processo demoraria menos tempo.

4- Outra sugestão seria que quando um serviço for criado e publicado este ficasse contido apenas no Branch Master. Quando uma alteração fosse cadastrada por algum usuário, esta sim ficaria em um Branch novo até que seja aprovada e publicada, assim substituindo o serviço do Branch Master.
Dessa forma o processo de subir o Editor seria de menos de um minuto.

**Comment by cv** [comment]
TODO: descrever processo de inicialização com/sem acesso ao github (git pulls), que podem ser a causa da lentidão

**Comment by caduvieira** [comment]
Uma sugestão pode ter o repositório das cartas em um lugar mais próximo do
portal/editor como um gitlab na ICS. Assim o roundtrip até o repositório
deve ficar menor. E ter um serviço sincronizando esses dois repositórios.
Em 1 de mar de 2016 4:55 PM, "Carlos Villela" <notifications@github.com>
escreveu:

**Comment by cv** [comment]
Vou mover esse cartão para o Editor, já que ao que parece, a carga do Portal está funcionando bem (e o commit mais recente da #551 alivia ainda mais qualquer problema de performance no Portal…)

**Comment by cv** [comment]
Movido: servicosgovbr/editor-de-servicos#520
