### ISSUE TITLE
Erro ao gerar carta de serviços

### ISSUE THREAD

**Issue by mformiga** [servicosgovbr/portal-de-servicos#558]

**Comment by mformiga** [comment]
![geracao de carta de servicos](https://cloud.githubusercontent.com/assets/10866724/13508365/709736a2-e165-11e5-8e07-18fc8c5ddbc5.PNG)

**Comment by mformiga** [comment]
Vamos atualizar o Manual de publicação informando que em versões mais antigas do browser a geração de carta não funciona.

**Comment by cv** [comment]
Qual browser foi usado para reproduzir esse erro, @mformiga?

**Comment by mformiga** [comment]
Firefox versão 24.5.0
