### ISSUE TITLE
Exibir canais de prestação de serviço

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#56]
**Acreditamos que** exibindo os canais de prestação na página do serviço
**Para** o cidadão
**Obteremos como resultado** uma decisão mais informada por parte do cidadão em relação à escolha do serviço
**Saberemos que atingimos o resultado quando** para os serviços com oferta online o cidadão utilizar essa opção na maioria das vezes

No XML atual:

```bash
xmlstarlet sel -t -c '//tipoCanalPrestacaoServico/titulo' -m "text()" src/main/resources/guiadeservicos.xml | sed 's/<\/titulo><titulo>/;/g' | sed 's/<titulo>//g' | sed 's/<\/titulo>//g' | sed 's/<titulo\/>/;/g' | tr ';' '\n' | sort | uniq 
```

```
E-mail
Mobile
Outros
Presencial
Telefone
Web
```

A descrição dos canais está bem suja, infelizmente – um simples mapeamento de strings não vai melhorar significativamente a qualidade da informação.

**Comment by alklaser** [comment]
_Premissa:_ acreditamos que exibindo os canais de prestação de serviço irá ajudar o cidadão a compreender de quais maneiras ele pode executar o próximo passo no serviço. Idealmente qualquer serviço com oferta online deve ser acessado dessa forma.

_O que estamos medindo:_ o uso dos serviços online.

_Aprendemos com isso:_ que o cidadão compreende que pode executar sua solicitação online. É um passo visando a redução de custo operacional e otimização do tempo.

_O que podemos aprender em seguida:_ se o acesso online ao serviço está sendo utilizado, podemos explorar mais as formas de interação com cidadão visando tornar essa relação mais eficaz. 

_O que pode nos surpreender:_ como podemos comparar os acessos via web com os outros? Temos acesso a essas métricas "offline"? Inicialmente podemos assumir que quaisquer outras ações que não a continuidade da solicitação do serviço de forma online signifiquem que o usuário optou pelo acesso offline. Uma análise mais detalhada do padrão de navegação pode nos dizer se esse método de verificação produz resultados confiáveis.

**Comment by oliviagj** [comment]
@mformiga, iniciar verificação deste ponto, pois foi identificado que há erro no .xml em relação a isso. @cv, tem certeza de que tem erro?

**Comment by oliviagj** [comment]
@mformiga, há serviços que estão com essa informação no "informações complementares"

**Comment by cv** [comment]
Vou precisar de uma ajuda para bolar um jeito bom de exibir esses canais. O conteúdo deles varia drasticamente de serviço para serviço, então vamos ter que demarcar bem o conteúdo para que ele faça sentido na leitura. Um exemplo:

http://gds-alpha.herokuapp.com/servico/prorrogacao-do-prazo-de-estada-no-brasil-vistos

![screen shot 2015-03-26 at 12 54 48 pm](https://cloud.githubusercontent.com/assets/5445/6850369/8ac8cc64-d3b7-11e4-84e3-b26934580aed.png)

**Comment by cv** [comment]
Outros serviços que podem ajudar a definir o problema melhor:

- [Prorrogação do Prazo de Estada no Brasil (vistos)](http://gds-alpha.herokuapp.com/servico/prorrogacao-do-prazo-de-estada-no-brasil-vistos)
- [Permanência definitiva no Brasil](http://gds-alpha.herokuapp.com/servico/permanencia-definitiva-no-brasil)
- [Conversão de moedas](http://gds-alpha.herokuapp.com/servico/conversao-de-moedas)
- [Carteira de Trabalho e Previdência Social - CTPS](http://gds-alpha.herokuapp.com/servico/carteira-de-trabalho-e-previdencia-social-ctps)

**Comment by cv** [comment]
Aguardando feedback relacionado aos comentários acima.
