### ISSUE TITLE
Instalação na esfera estadual

### ISSUE THREAD

**Issue by thiagoaos** [servicosgovbr/portal-de-servicos#568]
Senhores, gostaria de instalar essa solução na esfera estadual, para ser utilizada como catalogo de serviços no Estado da Bahia.

Estou repassando para área de infraestrutura a solicitação de instalação em um ambiente de homologação, e passei como referência o link http://servicosgovbr.github.io/portal-de-servicos/implantacao/documento-de-implantacao.html.

É possível instalar esta solução para outra esfera? Neste link contam todas as informações sobre a instalação do portal e editor? 

Dando uma lida no documento verifiquei que menciona outro projeto desta conta, como o cartas-de-servicos, e que pede solicitação de uma conta do github com leitura e escrita para o repositório? É realmente preciso permissão para escrita?

**Comment by isaacvits** [comment]
@thiagoaos nesse link tem todas as informações para implantação do portal de serviços, mas qualquer dúvida estamos a disposição (apenas um detalhe não é necessário executar o build-all, as imagens estão no docker hub). Em relação a cartas-de-servicos como você apenas fará leitura não é necessário uma conta.A cartas-de-servicos é um pouco grande, talvez seja melhor você usar o outro projeto cartas-de-teste que contém um repositório menor.

**Comment by thiagoaos** [comment]
Obrigado @isaacvits. Vou dar uma estudada para entender melhor como funciona essa parte de cartas-de-serviço, para tentar criar uma específica para a nossa realidade.

**Comment by gomex** [comment]
@thiagoaos Eu sou de Salvador, ou seja, tenho interesse pessoal nessa implantação. Se precisar de ajuda na parte do Docker, pode contar comigo.

**Comment by thiagoaos** [comment]
Boa tarde @gomex . A ferramenta (portal e editor) foi instalada aqui no estado. O cliente final vai testar se vai atender necessidades. Não estou responsável por essa atividade de instalação, a equipe de infraestrutura que está. Porém tento facilitar algumas coisas para a área responsável. 

Na documentação de implantação do guia não informa um usuário/senha da administração para acessar o editor. Qual seria o procedimento para acessar o editor e criar novos usuários para os órgãos? Tem algum interface para manter os usuários ou é necessário acessar diretamente o banco de dados?

**Comment by gomex** [comment]
Como comentaram no gitter:
"olha o script de migrations tem um script pra criação de usuário"
Chegou a olhar isso?

**Comment by thiagoaos** [comment]
Bom dia @gomex. Cheguei a dar uma olhada agora, vou criar os usuários. Obrigado. Vou fechar o ticket aqui e tirar minhas dúvidas pelo gitter, obrigado  pela ajuda.
