### ISSUE TITLE
Adicionar ferramental para compilar SASS/SCSS -> CSS

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#59]
[WRO4J](https://code.google.com/p/wro4j/), talvez?

- [x] Integrar ao Gradle
- [x] Compilar arquivos sempre
- [x] Garantir que arquivos compilados sobrescrevem os anteriores ao reiniciar o serviço
- [ ] Integrar ao IntelliJ (stretch goal)

**Comment by cv** [comment]
WRO4J parece meio complicado demais. [gradle-compass](https://github.com/robfletcher/gradle-compass) faz tudo que a gente precisa, acho (e usa jruby por baixo dos panos, que pode ser mais simples de integrar, mantendo a independência de plataforma).

**Comment by cv** [comment]
Promissor: http://davydotcom.com/blog/2014-12-21-spring-boot-with-the-asset-pipeline

**Comment by lqust** [comment]
SASSSaaS? /cc @dudadornelles

**Comment by cv** [comment]
@lqust não vejo motivo pra depender de um serviço externo pra isso. Queria ter a opção de rodar os builds offline, se possível.

**Comment by erickpintor** [comment]
Sobre integrar ao IntelliJ, não parece necessário uma vez que os arquivos vão ser compilados pelo ```gradle``` enquanto são alterados em qualquer IDE.

Hoje, basta executar o projeto com ```./gradlew bootRun``` e alterar o css / scss a vontade.

**Comment by caduvieira** [comment]
@erickpintor Concordo. Não precisa integrar com o IntelliJ.
