### ISSUE TITLE
Migalhas-de-pão não oferecem contexto

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#67]
- [x] Adicionar ao menos um nível de categorização nas páginas de serviço 
- [x] Corrigir link das páginas de conteúdo estático

**Comment by sahrosa** [comment]
Quando estamos na primeira página, mostramos a página inicial:

![image](https://cloud.githubusercontent.com/assets/2932644/6452586/81f30d8e-c115-11e4-80ee-58a5bab10e89.png)

Sinto falta de mostrar a página inicial, quando estou num nível secundário:

![image](https://cloud.githubusercontent.com/assets/2932644/6452575/6e95e824-c115-11e4-9d73-e1864276ef31.png)
