### ISSUE TITLE
Empacotar artefatos

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#69]
- [x] Atualizar Vagrantfile
- [x] Provisionar CentOS 7
- [x] Provisionar ElasticSearch
- [x] Provisionar Java 8
- [x] RPM da aplicação
- [x] Script para inicialização (systemd)
- [x] Configurações padrão (portas, clustering do ElasticSearch, etc)
- [x] Logs e logrotate diário
- [x] Usuário, grupo e permissões restritivas
- [x] Criar chave IAM para EC2 (em ./secrets)
- [x] Criar instância na EC2 (free tier é suficiente)
- [x] Atualizar configuração do Snap
- [x] Atualizar documentação
- [x] Redirecionar gds-alpha no Heroku para a máquina nova

**Comment by cv** [comment]
Arquivos JAR gerados pelo Gradle já estão sendo mantidos pelo Snap.

**Comment by jeankirchner** [comment]
Isso ainda é necessário?

[] Criar chave IAM para EC2 (em ./secrets)
[] Criar instância na EC2 (free tier é suficiente)

**Comment by cv** [comment]
A chave já está lá – só usá-la para montar o circo :)

**Comment by jeankirchner** [comment]
1 - Vamos usar o Vagrant no EC2? Ou apenas vamos rodar o script de provisionamento lá, e usar os artefatos gerados do snap-ci?
2 - É para criar um RPM, para instalar mais fácil no EC2?

**Comment by cv** [comment]
Vagrant é só uma maneira de a gente garantir que as máquinas criadas estão se comportando (e um jeito barato de testar os scripts de provisionamento).

O ambiente que o Snap vai fazer deploy (que vou chamar de pre-prod) vai ficar na EC2, já que não dá pra testar nada muito mais sério com o deployment atual que temos no Heroku.

Depois de pre-prod, teremos homologação (já nos servidores do DGE) e produção (idem).

RPMs são mais fáceis de instalar e manter se a sua distribuição alvo é RH-based. No nosso caso, CentOS 7 e quem sabe o RHEL equivalente.

Então, fica assim:

| Categoria | Dev Local | Dev Virtual | Pre-Prod | Homologação | Produção |
|----|----|----|----|----|----|
| OS | Mac, Linux, etc | CentOS 7 | CentOS 7 | CentOS 7 | CentOS 7 |
| Deployment | Não precisa | Manual | Automático | Manual | Manual |
| Porta | 8080 | 8081 | 8080 | 8080 | 8080 |
| ElasticSearch | Embedded | Cluster | Cluster | Cluster | Cluster |
| Provisionamento | Manual | Bash + RPM | Bash + RPM  | Bash + RPM  | Bash + RPM  |

PS: Não acho que vamos precisar de Chef ou Puppet. Não me parece que instalar o que for preciso para provisionar a máquina com nginx + elasticsearch + app depende desse maquinário todo.
