### ISSUE TITLE
Página para Órgão

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#80]
Idêntico a #79, mas para órgãos.

**Comment by sahrosa** [comment]
**Para fazer:**
- Colocar os serviços em ordem alfabética, para ter uma ordem lógica.
- Colocar o título para os três serviços destacados. Talvez "Serviços destacados" já serviria!
- Fonte nos títulos dos três serviços em Open Sans (está arial).

**Para pensar/testar:**
- Hierarquia entre a "Migalha-de-pão" x "Órgão" x "Nome do Órgão". Vou fazer uns testes visuais para pensarmos como pode ficar mais adequado :)
- Seria interessante ter um filtro dentro dos serviços do órgão? Podemos testar algo!
- Penso que iconografia funciona em proporções menores, como por exemplo, na linha da vida, que teremos uma quantidade limitada de itens. Se tivermos um ícone para cada serviço, poderemos necessitar milhares de ícones, e isso se tornaria inviável! Vamos testar algumas possibilidades! No guia de estilo existem apenas ícones de conteúdo (texto, foto) e funcionalidade (imprimir, agendar). 
- Faria sentido trazer a sigla do órgão junto ao nome completo? Alguns órgãos são muito mais conhecidos por suas siglas!

**Comment by sahrosa** [comment]
Testando a ideia de um ícone por item da linha da vida (aposentadoria, viajar para o exterior, etc). Estou usando o http://fortawesome.github.io/Font-Awesome/ e gostando muito :)

![image](https://cloud.githubusercontent.com/assets/2932644/6833632/69f6949e-d30d-11e4-9849-afd13dcd1cc8.png)

**Comment by caduvieira** [comment]
Muito bom! E com permissão de uso GPL. Beleza! Tem o 'money' para 'Crédito e Apoio Financeiro' que pode ser usado também. E Gavel para algo da Justiça

**Comment by jeankirchner** [comment]
:+1: Sigla do órgão

- Acredito que ícones funcionem melhor em categorias bem alto nível (talvez
algumas jornadas da vida), e quando eu entrar eu sei +- que os serviços se
referem à aquele ícone/nome categoria mais macro
- Nem precisa de muitos ícones para começarem a se confundir entre si - até
por questão de ícones serem pequenos, naturalmente as imagens devem ter o
mínimo de pequenos detalhes possível
- O exemplo de layout da imagem, me dá a impressão que cada serviço tem na
sua frente o ícone da sua categoria mais alto nível, e acho que isso ajuda
bastante à contextualizar e fica legal, sempre prestando atenção na
quantidade total de ícones
- Acredito que deveriamos ter um único campo de busca para o contexto da
página como um todo, se o filtro que você fala é só uma opção específica
para fazer a busca só em órgãos, me parece legal. Agora se você se refere à
mais um campo de busca dentro da página órgãos ou o campo de busca ser
contextual à página de órgãos, acho que isso pode começar a ficar confuso,
acredito que devemos ter um campo de busca único que os usuários ganham
muita confiança.

- Além dos 3 serviços mais destacados, talvez seria legal uma forma de eu
ter acesso à uma lista em ordem de mais acessados? Visto a sazonalidade de
uso de serviços, à serviços comuns que podem sair desses 3+

**Comment by caduvieira** [comment]
Dei um +1 para https://github.com/FortAwesome/Font-Awesome/issues/6010 fa-government-building
