### ISSUE TITLE
Gerar tickets para cada request

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#81]
Implementar [requisito não-funcional](https://github.com/servicosgovbr/guia-de-servicos/blob/master/docs/desenvolvimento/requisitos-nao-funcionais.md#tratamento-de-erros) para gerar um número de ticket para cada requisição e usá-la para identificar todas as ações logadas.

- [x] Criar ServletFilter que gera tickets
- [x] Criar ServletFilter que loga detalhes das requisições (incl tickets)
- [x] Adicionar ServletFilter para todos requests
- [x] Configurar o logback para exibir dados nas linhas de log

**Comment by caduvieira** [comment]
@cv aonde eu posso ver esses tickets gerados? somente no Log?

**Comment by cv** [comment]
Sim, eles são o primeiro campo logado:

```
fcf3d1e1-0f9d-445c-9660-35fe172a847f INFO  [http-nio-8080-exec-1] b.g.s.frontend.LoggingFilter - Request: GET /
fcf3d1e1-0f9d-445c-9660-35fe172a847f INFO  [http-nio-8080-exec-1] b.g.s.frontend.LoggingFilter - Remote host: 0:0:0:0:0:0:0:1 null
fcf3d1e1-0f9d-445c-9660-35fe172a847f INFO  [http-nio-8080-exec-1] b.g.s.frontend.LoggingFilter - User-Agent: curl/7.37.1
```

(Estamos logando o UUID todo, para evitar algum caso raro de ambiguidade)
