### ISSUE TITLE
Limitar acesso a URLs sensíveis

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#83]
URLs públicas:

- [x] /
- [x] /busca
- [x] /conteudo/{id}
- [x] /error
- [x] /health
- [x] /linha-da-vida/{id}
- [x] /navegar/{id}
- [x] /orgao/{id}
- [x] /robots.txt
- [x] /servico/{id}
- [x] /publico-alvo/{id}

URLs privadas:

- [x] /autoconfig
- [x] /beans
- [x] /configprops
- [x] /dump
- [x] /env
- [x] /info
- [x] /jolokia
- [x] /mappings
- [x] /metrics
- [x] /shutdown
- [x] /trace

É provável que exista alguma configuração do próprio Spring-Boot para isso.

Quando `/jolokia` for limitada, é importante adequar a configuração do Snap.

**Comment by cv** [comment]
Adicionei mais um teste de integração (`FrontendTest`) que também vai precisar ser alterado quando o acesso a `/info` for protegido.

**Comment by erickpintor** [comment]
Acho que não. Estou restringindo acesso apenas para o profile de ```prod```.

**Comment by erickpintor** [comment]
Enquanto o endpoint ```/health``` não está sendo utilizado, ele irá permanecer inativo.

**Comment by caduvieira** [comment]
Está aparecendo o /env e np /metrics em prod com a seguinte mensagem
![image](https://cloud.githubusercontent.com/assets/3831408/7776499/ca8805a2-0091-11e5-9ca3-f2ed774c4a20.png)

Esse é o esperado ou deveria ser como os outros e dar "Esta página não existe"? Creio que seja melhor deixar padronizado.

Info, jolokia estão abertos também.

No /shutdown deu página de erro.

**Comment by caduvieira** [comment]
O /info ainda está aparecendo mas não vejo problema com ele. Tem algum problema em estar aberto que não vejo?

**Comment by cv** [comment]
No `/info`, não. Aliás, vamos manter o `/health` aberto também, só que com a flag `ENDPOINTS_HEALTH_SENSITIVE` ligada (o que impede informações sobre espaço em disco, etc de aparecer).
