### ISSUE TITLE
Mapear Área de Interesse no VCGE

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#84]
Áreas de Interesse (listadas em #57) não parecem estar em uma categorização uniforme, e diversos serviços estão mapeados em áreas das quais não pertencem.

Mapear áreas de interesse para seus pontos corretos no [VCGE](http://vocab.e.gov.br/id/governo#esquema)  – utilizando [o de-para](http://www.governoeletronico.gov.br/acoes-e-projetos/e-ping-padroes-de-interoperabilidade/vcge) já disponibilizado.

- [x] Importar arquivo [de-para](http://www.governoeletronico.gov.br/biblioteca/arquivos/vcge-depara-01/download) existente
- [x] Alterar importação para utilizar a categoria correta do VCGE 2 nos serviços
- [x] Adicionar seção de áreas de interesse no menu à esquerda

**Comment by alklaser** [comment]
**Vamos ou não usar as linhas da vida como navegação principal?**

Acho que a melhor forma é testar os dois (ou mais) tipos de navegação possível e medir qual está levando o cidadão mais rapidamente ao serviço que ele necessita.

**Comment by sahrosa** [comment]
Eu acredito e gosto da solução de linha da vida. 

Em casos como a França, a navegação fica ainda mais "humana" quando é utilizado o seguinte forma: "E se eu quiser comprar uma casa?" - "E se eu estiver grávida?" e até "E se eu perder um familiar querido?". Essa humanização faz com que o usuário não se sinta sem opções na frente de um computador frio. E é isso que queremos, que o cidadão consiga resolver seus problemas com facilidade!

Claro que isso funciona para o médio/longo prazo pois precisamos testar as possibilidades (com o que já existe e o que iremos propor a partir dos aprendizados atuais). 

Para o Release 1, talvez realizar um card sorting pode ser uma forma de já melhorar um pouco.

**Comment by almeidafab** [comment]
Concordo com a @sahrosa também gosto de categorizar baseado em situações da vida. Talvez não precisamos decidir entre uma ou outra, podemos usar as duas formas. No portal da Noruega (http://www.norge.no/en) eles utilizam as duas maneiras, uma espécie de áreas de interesse e situações da vida.

**Comment by alklaser** [comment]
Pessoalmente também prefiro as linhas da vida. Daí o que temos de fazer é confirmar se para os cidadãos essa é também a melhor opção.
