### ISSUE TITLE
Busca fonética para o Elastic Search

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/portal-de-servicos#86]
Hoje se procurarmos por 'indentidade' ao invés de 'identidade' por exemplo, não encontramos resultados.

**Comment by caduvieira** [comment]
Sugiro Metaphone pt-br.

https://github.com/ruliana/MTFN
https://code.google.com/p/metaphone-standards/source/browse/MetaphonePtBr.wiki?repo=wiki
http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/phonetic-matching.html

**Comment by cv** [comment]
Implementação, específica para o ElasticSearch, da análise fonética do
português:

https://github.com/timotta/elasticsearch-fonetica-portuguesa

**Comment by caduvieira** [comment]
@cv usando o exemplo da Rosa esse algoritmo codificou 'indentidade' para 'INDENTIDADE' e 'identidade' para 'IDENTIDADE'

**Comment by cv** [comment]
Talvez seja melhor pensar em usar a [API de sugestões (did-you-mean)][DYM] do ElasticSearch, mesmo que por baixo dos panos. Ela dá bastante flexibilidade em relação à quantidade de erro tolerada em erros de ortografia (afinal, foi feita pra isso).

[DYM]:http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-suggesters.html

**Comment by sahrosa** [comment]
Estou fechando o cartão pois está fora do escopo, ok @mformiga @almeidafab @gustavo-freitas? :)
