### ISSUE TITLE
Migrar CSS para SASS

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#87]
- [x] Dividir CSS em conjuntos lógicos
- [x] Juntar definições agrupadas por IDs em regras únicas do SASS
- [ ] Agrupar definições idênticas em funções SASS
- [x] Reduzir número de resets necessários
- [ ] …

**Comment by cv** [comment]
Com as revisões no grid - #92 - faz mais sentido mover essa issue e continuar qualquer trabalho específico em issues mais focadas.

**Comment by barbarawolffdick** [comment]
Uhm, eu acho que esse issue ta resolvido, né? Movemos tudo, já. Agora de fato são outras coisas acontecendo.
