### ISSUE TITLE
Revisão do grid

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/portal-de-servicos#92]
Com o grid atual (imagem abaixo), temos algumas dificuldades para acomodar as informações do site.

![image](https://cloud.githubusercontent.com/assets/2932644/6563132/788598d0-c67d-11e4-8b9f-1520f335474c.png)

A coluna da esquerda (de menu) é o principal ponto a ser revisado, pois no grid atual possui apenas 150 px, e portanto, faz com que as informações fiquem quebradas (segunda imagem) como no exemplo do Portal Brasil.

![image](https://cloud.githubusercontent.com/assets/2932644/6563153/a54b9608-c67d-11e4-90b4-47afac154b79.png)

**Comment by sahrosa** [comment]
Estou trabalhando na proposta de revisão de grid abaixo, onde teremos 12 colunas. A área que antes era 960 pixels se torna 1040, ou seja, adquirindo 40 pixels a mais. 

Pensando na "responsividade" e modularidade, temos 4 breakpoints principais (desktop, tablet, maior mobile e menor mobile). 

A proposta ainda não está concluída, e está aberta a sugestões!

![image](https://cloud.githubusercontent.com/assets/2932644/6563204/0481c066-c67e-11e4-89c8-c4e464f47c5b.png)

**Comment by sahrosa** [comment]
Pesquisei hoje pela manhã (valeu a ajuda @erickpintor) sobre as resoluções usadas no site atual, e vimos que 12% dos visitantes únicos do Guia utilizam resolução de 1024 x 768. Analisamos o último mês (12%), e também nos últimos 6 meses (13%), ou seja, o uso da resolução de 1024 caiu apenas 1%.

Isso quer dizer que uma parcela de 12% de usuários precisam visualizar o site em menos de 1040 (minha proposta anterior de grid). Isso é bastante gente.

Por isso estou testando uma nova possibilidade, que é usarmos um grid de 980, com apenas 20 pixels a mais que o grid atual, e garante uma visualização  mas que garante uma coluna de menu com 215 pixels, e ainda possui 12 colunas, o que nos ajuda a organizar melhor o conteúdo interno. 

O que acham?

![image](https://cloud.githubusercontent.com/assets/2932644/6581667/4df8d4d2-c737-11e4-8155-2dd768b98b38.png)

**Comment by cv** [comment]
E se a gente usar 3 colunas num grid de 960, ficando com 240 pixels? 




Ainda sobra bastante espaço para o conteúdo (9 colunas) e a gente não precisa mexer nas quebras atuais (fone, tablet, desktop, impressão). 



- cv

**Comment by sahrosa** [comment]
Hoje o nosso protótipo, por exemplo, está totalmente fora do grid atual (imagem abaixo). 

![image](https://cloud.githubusercontent.com/assets/2932644/6602093/44e24c40-c7f8-11e4-9e19-c93e3dfefb35.png)

No entanto concordo plenamente contigo, CV, sobre não precisar mexer nas quebras atuais (só acho que precisamos flexibiliza-las - pois temos alguns tables maiores que 768 e celulares maiores que 320).

Então sugiro o seguinte: vou finalizar o grid novo com a maior proximidade do grid atual, mas repensando esses espaços internos de acordo com as nossas necessidades (principalmente de menu que não pode ser apenas 150 e diferentes colunas de conteúdo).

**Comment by sahrosa** [comment]
Outra coisa que me faz preferir o modelo de 980 (ou 1040) ao 960 é que conseguimos ter quebras exatas na malha de 10 x 10 pixels. Ter essas quebras exatas não é algo obrigatório, mas um "desejável": não precisamos ser pixel perfect, mas se tivermos quebras exatas entre as colunas, isso cria naturalmente uma estabilidade óptica entre todos os elementos e não precisamos nos preocupar com itens desalinhados, etc.

**Comment by sahrosa** [comment]
Só um comentário. A @barbarawolffdick lembrou que é importante lembrar que estamos falando de duas coisas: uma delas é o grid visual (discutido aqui) e a outra é aplicar ele no CSS em %, para funcionar responsivamente!

**Comment by oliviagj** [comment]
@sahrosa, tá ficando massa! essa diferença que a @barbarawolffdick colocou é bem importante. bóra ver se é o caso de criar um card para a outra etapa. outra coisa, vamos conversar sobre o andamento disso aqui amanhã ou segunda, junto com a conversa sobre priorização do escopo para o novo Release 0.

**Comment by sahrosa** [comment]
Perfeito!

**Comment by sahrosa** [comment]
Última atualização do grid: tentando usar o tamanho atual de 960px. Tentando essa possibilidade pois se usarmos um grid 980 vamos ficar diferentes de todos os outros portais... dessa forma mantemos os breakpoints que já existiam, como o @cv comentou! Hoje pela manhã, @barbarawolffdick vai me dar uma super mão pra gente começar a implementar isso em css responsivo! 

![image](https://cloud.githubusercontent.com/assets/2932644/6687854/9cc8e5d8-cc8d-11e4-8100-5c65cb1efc7e.png)
