### ISSUE TITLE
Revisar texto "Sobre o Guia"

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#96]
[/conteudo/sobre-o-guia](http://gds-alpha.herokuapp.com/conteudo/sobre-o-guia)

**Comment by sahrosa** [comment]
Estou pensando nisso seriamente se tornar um pequeno destaque na home, afinal:
- Precisamos ensinar as pessoas que o site está em constante melhoria.
- Muitas pessoas chegam no site e não encontram o que querem, e vão embora. Se pelo menos mostrarmos para que o site serve (mesmo que não seja para a sua necessidade do momento), pelo menos elas começam a entender que esse espaço existe.

Entre outros cenários! Vou testar num macro wireframe e compartilhar com vocês! :)

**Comment by cv** [comment]
Adorei a ideia – um texto pequeno, informal e informativo sobre o que o Guia pode fazer encaixado entre a barra de busca e os destaques ia ficar ótimo.

Só falta alguém produzir a cópia… Voluntários? :)

**Comment by sahrosa** [comment]
Texto modificado: O objetivo deste guia é facilitar o acesso dos cidadãos aos serviços prestados pelos diversos órgãos do Governo Federal. Aqui você poderá encontrar informações úteis, começar um serviço e até agendar visitas a agências do governo.
