### ISSUE TITLE
Revisão SEO 

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/portal-de-servicos#97]
Definir Title + Description + Open Graph (conforme imagem) + Keywords (se fizer sentido) + Tags de busca (se fizer sentido)

![image](https://cloud.githubusercontent.com/assets/2932644/6619842/c38b9eee-c8ab-11e4-8f78-55a5f72fe12d.png)

**Comment by cv** [comment]
O Facebook tem um debugger ótimo para isso:

https://developers.facebook.com/tools/debug/og/object?q=gds-alpha.herokuapp.com

**Comment by cv** [comment]
Marcado como 'para prod', agora que os campos obrigatórios no OGP e algumas outras propriedades que o Google lê estão preenchidas. À medida que acharmos novas alterações, vamos criando cartões novos.

**Comment by sahrosa** [comment]
Show!

**Comment by sahrosa** [comment]
Temos que revisar algumas coisas:

- [ ] Padrão de Title (página inicial + páginas internas)
- [ ] Description
- [ ] Open Graph (og:image, og:title, og:description)

**Comment by almeidafab** [comment]
@sahrosa @cv o texto da tag "og:description" está desatualizado, o correto é: "O objetivo deste ambiente é facilitar o acesso aos serviços prestados pelos diversos órgãos do Governo Federal. Aqui você poderá encontrar informações úteis, agendar um atendimento, entrar em contato com os órgãos e até começar um serviço."

**Comment by sahrosa** [comment]
Vou atualizar @almeidafab!
