### ISSUE TITLE
Adicionar Google Breadcrumbs

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#98]
https://developers.google.com/structured-data/breadcrumbs

**Comment by caduvieira** [comment]
Escolher entre o que exatamente? Entre formatos, RDFa ou Microdata? Ou qual vocabulário, Schema ou Data-vocabulary?

**Comment by cv** [comment]
Já temos os breadcrumbs (`migalhas-de-pao.html`), então acho que usar marcação microdata faz mais sentido.
